# Generated by Django 6.0.1 on 2026-09-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0033_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название автосалона')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Название автосалона (EN)')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='autosalon/logos/', verbose_name='Логотип')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='autosalon/covers/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Описание (EN)')),
                ('phone', models.CharField(blank=True, default='', help_text='Резервный номер для кнопки «Написать», если у машины не указан отдельный менеджер', max_length=50, verbose_name='Телефон / WhatsApp автосалона')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('work_hours', models.CharField(blank=True, default='', help_text='Например: Пн–Вс 09:00–19:00', max_length=200, verbose_name='Режим работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('place_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autosalons', to='core.placecategory', verbose_name='Категория платформы')),
            ],
            options={
                'verbose_name': 'Автосалон',
                'verbose_name_plural': 'Автосалоны',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('generation', models.CharField(blank=True, default='', max_length=150, verbose_name='Поколение / комплектация')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'С пробегом')], default='used', max_length=10, verbose_name='Состояние')),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('suv', 'Внедорожник'), ('crossover', 'Кроссовер'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('coupe', 'Купе'), ('wagon', 'Универсал'), ('convertible', 'Кабриолет')], default='', max_length=20, verbose_name='Тип кузова')),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег, км')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро'), ('gas', 'Газ')], default='', max_length=10, verbose_name='Топливо')),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('robot', 'Робот'), ('cvt', 'Вариатор')], default='', max_length=12, verbose_name='Коробка передач')),
                ('drive_type', models.CharField(blank=True, choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], default='', max_length=5, verbose_name='Привод')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объём двигателя, л')),
                ('power_hp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность, л.с.')),
                ('color', models.CharField(blank=True, default='', max_length=60, verbose_name='Цвет')),
                ('vin', models.CharField(blank=True, default='', help_text='Виден только в кабинете салона, не показывается публично', max_length=32, verbose_name='VIN-номер')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('KGS', 'сом'), ('USD', '$')], default='KGS', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('available', 'В наличии'), ('reserved', 'Забронирована'), ('sold', 'Продана'), ('hidden', 'Снята с продажи')], default='available', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Описание (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autosalon.autodealership')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='autosalon/cars/', verbose_name='Фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='autosalon.car')),
            ],
            options={
                'verbose_name': 'Фото автомобиля',
                'verbose_name_plural': 'Фото автомобиля',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DealershipMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('director', 'Директор'), ('manager', 'Менеджер')], default='manager', max_length=20, verbose_name='Роль')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='autosalon.autodealership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autosalon_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к автосалону',
                'verbose_name_plural': 'Доступы к автосалону',
                'unique_together': {('user', 'dealership')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='autosalon.dealershipmembership', verbose_name='Ответственный менеджер'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, default='', verbose_name='Сообщение')),
                ('source', models.CharField(choices=[('car_page', 'Страница автомобиля'), ('dealership', 'Страница автосалона')], default='car_page', max_length=20, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('won', 'Сделка'), ('lost', 'Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, default='', verbose_name='Заметка менеджера')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='autosalon.car')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='autosalon.autodealership')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='autosalon.dealershipmembership', verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
    ]
