# Generated by Django 6.0.1 on 2026-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosalon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Продана когда'),
        ),
    ]
