# -*- coding: utf-8 -*-
"""
Полные данные меню кафе AURA (Ош, Салиева 10/2) — 3 языка (RU/KY/EN), цены, фото-слаги.
Составлено по PDF-меню (сентябрь 2026).
"""

CATEGORIES = [
    # ── 1. Пасты ─────────────────────────────────────────────────────────────
    {
        "name_ru": "Пасты", "name_ky": "Макарондор", "name_en": "Pasta",
        "items": [
            dict(name_ru="Паста Фетучини с курицей", name_ky="Тоокчон фетучини паста",
                 name_en="Fettuccine Pasta with Chicken",
                 desc_ru="Курица, вегета, чёрный перец, лапша фетучини, сливки, сыр пармезан, укроп, кинза, помидор",
                 desc_ky="Тоок эти, вегета, кара мурч, фетучини лапшасы, каймак, пармезан быштагы, укроп, кинза, помидор",
                 desc_en="Chicken, vegeta seasoning, black pepper, fettuccine pasta, cream, parmesan, dill, cilantro, tomato",
                 price=350, photo="pasta_fetuchini_kuritsa"),
            dict(name_ru="Паста с курицей", name_ky="Тоокчон паста", name_en="Chicken Pasta",
                 desc_ru="Курица, вегета, чёрный перец, лапша спагетти, сливки, сыр пармезан, укроп, кинза, помидор",
                 desc_ky="Тоок эти, вегета, кара мурч, спагетти лапшасы, каймак, пармезан быштагы, укроп, кинза, помидор",
                 desc_en="Chicken, vegeta seasoning, black pepper, spaghetti, cream, parmesan, dill, cilantro, tomato",
                 price=350, photo="pasta_kuritsa"),
            dict(name_ru="Макорошки с сосиской", name_ky="Сосискалуу макарон", name_en="Macaroni with Sausage",
                 desc_ru="Сосиска, вегета, чёрный перец, макарон, сливки, сыр пармезан, укроп, кинза, помидор",
                 desc_ky="Сосиска, вегета, кара мурч, макарон, каймак, пармезан быштагы, укроп, кинза, помидор",
                 desc_en="Sausage, vegeta seasoning, black pepper, macaroni, cream, parmesan, dill, cilantro, tomato",
                 price=300, photo="makoroshki_sosiska"),
        ],
    },
    # ── 2. Завтраки ──────────────────────────────────────────────────────────
    {
        "name_ru": "Завтраки", "name_ky": "Таңкы тамактар", "name_en": "Breakfast",
        "items": [
            dict(name_ru="Каша рисовая", name_ky="Күрүч боткосу", name_en="Rice Porridge",
                 price=200, photo="kasha_risovaya"),
            dict(name_ru="Каша овсяная", name_ky="Овс боткосу", name_en="Oatmeal Porridge",
                 price=200, photo="kasha_ovsyanaya"),
            dict(name_ru="Яйцо жареное (1 шт)", name_ky="Куурулган жумуртка (1 даана)", name_en="Fried Egg (1 pc)",
                 price=35, photo="yaico_zharenaya"),
            dict(name_ru="Яйцо варёное (1 шт)", name_ky="Кайнатылган жумуртка (1 даана)", name_en="Boiled Egg (1 pc)",
                 price=35, photo="yaico_varenoe"),
            dict(name_ru="Сендвич с курицей", name_ky="Тоокчон сендвич", name_en="Chicken Sandwich",
                 desc_ru="Хлеб 3 шт, курица жареная, соус фирменный, соус чесночный, помидоры, солёные огурцы, капуста",
                 desc_ky="Нан 3 даана, куурулган тоок эти, фирмалык соус, сарымсак соусу, помидор, туздалган бадыраң, капуста",
                 desc_en="Bread 3 slices, fried chicken, signature sauce, garlic sauce, tomatoes, pickles, cabbage",
                 price=220, photo="sendvich_kuritsa"),
        ],
    },
    # ── 3. Десерт ────────────────────────────────────────────────────────────
    {
        "name_ru": "Десерт", "name_ky": "Таттуу", "name_en": "Dessert",
        "items": [
            dict(name_ru="Сладкий ролл", name_ky="Таттуу ролл", name_en="Sweet Roll",
                 desc_ru="Сладкий сыр творожный, спринг тосто, банан, яблоко, топпинг клубничный",
                 desc_ky="Таттуу сыр, спринг тосто, банан, алма, кулпунай топпинг",
                 desc_en="Sweet cream cheese, spring toast, banana, apple, strawberry topping",
                 price=350, photo="sladkiy_roll"),
            dict(name_ru="Шоколадный ролл", name_ky="Шоколаддуу ролл", name_en="Chocolate Roll",
                 desc_ru="Сладкий сыр творожный, спринг тосто, шоколад, банан, яблоко, топпинг клубничный",
                 desc_ky="Таттуу сыр, спринг тосто, шоколад, банан, алма, кулпунай топпинг",
                 desc_en="Sweet cream cheese, spring toast, chocolate, banana, apple, strawberry topping",
                 price=350, photo="shokoladnyy_roll"),
        ],
    },
    # ── 4. Роллы ─────────────────────────────────────────────────────────────
    {
        "name_ru": "Роллы", "name_ky": "Роллдор", "name_en": "Rolls",
        "items": [
            dict(name_ru="Филадельфия", name_ky="Филадельфия", name_en="Philadelphia Roll",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, лосось, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, лосось, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, salmon, soy sauce, ginger",
                 price=450, photo="filadelfiya"),
            dict(name_ru="Калифорния", name_ky="Калифорния", name_en="California Roll",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, краб, масага красная, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, краб, кызыл масага, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, crab, red masago caviar, soy sauce, ginger",
                 price=400, photo="kaliforniya"),
            dict(name_ru="Калифорния с курицей", name_ky="Тоокчон Калифорния", name_en="California Roll with Chicken",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, курица, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, тоок эти, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, chicken, sesame, soy sauce, ginger",
                 price=400, photo="kaliforniya_kuritsa"),
            dict(name_ru="Ролл с сыром", name_ky="Быштактуу ролл", name_en="Cheese Roll",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, сыр моцарелла, сыр чеддер, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, моцарелла быштагы, чеддер быштагы, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, mozzarella, cheddar, soy sauce, ginger",
                 price=450, photo="roll_syrom"),
            dict(name_ru="Мини с огурцом", name_ky="Бадыраңдуу мини ролл", name_en="Mini Cucumber Roll",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, soy sauce, ginger",
                 price=220, photo="mini_ogurets"),
            dict(name_ru="Мини с курицей", name_ky="Тоокчон мини ролл", name_en="Mini Chicken Roll",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, курица, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, тоок эти, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, chicken, soy sauce, ginger",
                 price=250, photo="mini_kuritsa"),
            dict(name_ru="Ролл запечённый с курицей", name_ky="Мешинде бышырылган тоокчон ролл",
                 name_en="Baked Chicken Roll",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, жареная курица, соус для запекания, соус унаги, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, куурулган тоок эти, мешинде бышыруу соусу, унаги соусу, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, fried chicken, baking sauce, unagi sauce, sesame, soy sauce, ginger",
                 price=400, photo="roll_zapech_kuritsa"),
            dict(name_ru="Ролл запечённый с крабом", name_ky="Мешинде бышырылган крабдуу ролл",
                 name_en="Baked Crab Roll",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, крабовая палочка, соус для запекания, соус унаги, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, краб таякчасы, мешинде бышыруу соусу, унаги соусу, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, crab stick, baking sauce, unagi sauce, sesame, soy sauce, ginger",
                 price=400, photo="roll_zapech_krab"),
            dict(name_ru="Ролл запечённый с лососем", name_ky="Мешинде бышырылган лососьтуу ролл",
                 name_en="Baked Salmon Roll",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, лосось, соус для запекания, соус унаги, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, лосось, мешинде бышыруу соусу, унаги соусу, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, salmon, baking sauce, unagi sauce, sesame, soy sauce, ginger",
                 price=450, photo="roll_zapech_losos"),
            dict(name_ru="Ролл запечённый с сыром", name_ky="Мешинде бышырылган быштактуу ролл",
                 name_en="Baked Cheese Roll",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, сыр чеддер, сыр моцарелла, соус для запекания, соус унаги, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, чеддер быштагы, моцарелла быштагы, мешинде бышыруу соусу, унаги соусу, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, cheddar, mozzarella, baking sauce, unagi sauce, sesame, soy sauce, ginger",
                 price=420, photo="roll_zapech_syrom"),
            dict(name_ru="Ролл запечённый мини курица", name_ky="Мешинде бышырылган мини тоокчон ролл",
                 name_en="Baked Mini Chicken Roll",
                 desc_ru="Отварной рис, водоросли нори, свежий огурец, соус для запекания, соус унаги, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, таза бадыраң, мешинде бышыруу соусу, унаги соусу, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, fresh cucumber, baking sauce, unagi sauce, sesame, soy sauce, ginger",
                 price=290, photo="roll_zapech_mini_kuritsa"),
        ],
    },
    # ── 5. Жареные роллы ─────────────────────────────────────────────────────
    {
        "name_ru": "Жареные роллы", "name_ky": "Куурулган роллдор", "name_en": "Tempura Rolls",
        "items": [
            dict(name_ru="Ролл темпура с курицей", name_ky="Тоокчон темпура ролл", name_en="Tempura Roll with Chicken",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, жареная курица, кляр, сухари панировка, соус унаги, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, куурулган тоок эти, кляр, нан küкүмдөрү, унаги соусу, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, fried chicken, batter, breadcrumbs, unagi sauce, sesame, soy sauce, ginger",
                 price=400, photo="roll_tempura_kuritsa"),
            dict(name_ru="Ролл темпура с крабом", name_ky="Крабдуу темпура ролл", name_en="Tempura Roll with Crab",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, краб, кляр, сухари панировка, соус унаги, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, краб, кляр, нан күкүмдөрү, унаги соусу, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, crab, batter, breadcrumbs, unagi sauce, sesame, soy sauce, ginger",
                 price=400, photo="roll_tempura_krab"),
            dict(name_ru="Ролл темпура с лососем", name_ky="Лососьтуу темпура ролл", name_en="Tempura Roll with Salmon",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, свежий огурец, лосось, кляр, сухари панировка, соус унаги, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, таза бадыраң, лосось, кляр, нан күкүмдөрү, унаги соусу, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, fresh cucumber, salmon, batter, breadcrumbs, unagi sauce, sesame, soy sauce, ginger",
                 price=450, photo="roll_tempura_losos"),
            dict(name_ru="Ролл темпура с сыром", name_ky="Быштактуу темпура ролл", name_en="Tempura Roll with Cheese",
                 desc_ru="Отварной рис, водоросли нори, сыр творожный, сыр чеддер, сыр моцарелла, кляр, сухари панировка, соус унаги, кунжут, соевый соус, имбирь",
                 desc_ky="Кайнатылган күрүч, нори жалбырагы, сыр, чеддер быштагы, моцарелла быштагы, кляр, нан күкүмдөрү, унаги соусу, кунжут, соя соусу, имбирь",
                 desc_en="Boiled rice, nori seaweed, cream cheese, cheddar, mozzarella, batter, breadcrumbs, unagi sauce, sesame, soy sauce, ginger",
                 price=400, photo="roll_tempura_syrom"),
        ],
    },
    # ── 6. Пицца ─────────────────────────────────────────────────────────────
    {
        "name_ru": "Пицца", "name_ky": "Пицца", "name_en": "Pizza",
        "items": [
            dict(name_ru="Пицца Пепперони", name_ky="Пепперони пиццасы", name_en="Pepperoni Pizza",
                 desc_ru="Соус, сыр моцарелла, пепперони, орегано",
                 desc_ky="Соус, моцарелла быштагы, пепперони, орегано",
                 desc_en="Tomato sauce, mozzarella, pepperoni, oregano",
                 price=480, photo="pizza_pepperoni"),
            dict(name_ru="Пицца Маргарита", name_ky="Маргарита пиццасы", name_en="Margherita Pizza",
                 desc_ru="Соус, сыр моцарелла, помидоры, орегано, базилик",
                 desc_ky="Соус, моцарелла быштагы, помидор, орегано, базилик",
                 desc_en="Tomato sauce, mozzarella, tomatoes, oregano, basil",
                 price=450, photo="pizza_margarita"),
            dict(name_ru="Пицца Куриная", name_ky="Тоокчон пицца", name_en="Chicken Pizza",
                 desc_ru="Соус, сыр моцарелла, помидоры, куриное филе, орегано",
                 desc_ky="Соус, моцарелла быштагы, помидор, тоок филеси, орегано",
                 desc_en="Tomato sauce, mozzarella, tomatoes, chicken fillet, oregano",
                 price=480, photo="pizza_kurinaya"),
            dict(name_ru="Пицца 4 сезона", name_ky="4 мезгил пиццасы", name_en="Four Seasons Pizza",
                 desc_ru="Соус, сыр моцарелла, пепперони, шампиньоны, помидоры, оливки, болгарский перец",
                 desc_ky="Соус, моцарелла быштагы, пепперони, козу карын, помидор, зайтун, булгар калемпири",
                 desc_en="Tomato sauce, mozzarella, pepperoni, mushrooms, tomatoes, olives, bell pepper",
                 price=550, photo="pizza_4sezona"),
            dict(name_ru="Пицца 4 сыра", name_ky="4 быштак пиццасы", name_en="Four Cheese Pizza",
                 desc_ru="Сырный соус, сыр моцарелла, чеддер, пармезан, дорблю, орегано",
                 desc_ky="Быштак соусу, моцарелла, чеддер, пармезан, дорблю быштактары, орегано",
                 desc_en="Cheese sauce, mozzarella, cheddar, parmesan, dor blue, oregano",
                 price=500, photo="pizza_4syra"),
        ],
    },
    # ── 7. Шаурма ────────────────────────────────────────────────────────────
    {
        "name_ru": "Шаурма", "name_ky": "Шаурма", "name_en": "Shawarma",
        "items": [
            dict(name_ru="Шаурма Куриная", name_ky="Тоок этинен шаурма", name_en="Chicken Shawarma",
                 desc_ru="Соус чесночный, соус кетчуп, майонез, огурец свежий, помидор свежий, капуста китайская, картофель фри, куриная грудка",
                 desc_ky="Сарымсак соусу, кетчуп, майонез, таза бадыраң, таза помидор, кытай капустасы, картошка фри, тоок төш эти",
                 desc_en="Garlic sauce, ketchup, mayonnaise, fresh cucumber, fresh tomato, napa cabbage, french fries, chicken breast",
                 price=250, photo="shaurma_kurinaya"),
            dict(name_ru="Шаурма Классическая", name_ky="Классикалык шаурма", name_en="Classic Shawarma",
                 desc_ru="Соус чесночный, соус кетчуп, майонез, огурец свежий, помидор свежий, капуста китайская, картофель фри, говяжий котлет",
                 desc_ky="Сарымсак соусу, кетчуп, майонез, таза бадыраң, таза помидор, кытай капустасы, картошка фри, мал эт котлети",
                 desc_en="Garlic sauce, ketchup, mayonnaise, fresh cucumber, fresh tomato, napa cabbage, french fries, beef patty",
                 price=300, photo="shaurma_klassicheskaya"),
            dict(name_ru="Шаурма Ассорти", name_ky="Ассорти шаурма", name_en="Assorted Shawarma",
                 desc_ru="Соус чесночный, соус кетчуп, майонез, огурец свежий, помидор свежий, капуста китайская, картофель фри, говяжий котлет, куриная грудка",
                 desc_ky="Сарымсак соусу, кетчуп, майонез, таза бадыраң, таза помидор, кытай капустасы, картошка фри, мал эт котлети, тоок төш эти",
                 desc_en="Garlic sauce, ketchup, mayonnaise, fresh cucumber, fresh tomato, napa cabbage, french fries, beef patty, chicken breast",
                 price=350, photo="shaurma_assorti"),
            dict(name_ru="Шаурма Сырная", name_ky="Сырдуу шаурма", name_en="Cheese Shawarma",
                 desc_ru="Соус чесночный, соус кетчуп, майонез, огурец свежий, помидор свежий, капуста китайская, картофель фри, говяжий котлет, куриная грудка, сыр моцарелла",
                 desc_ky="Сарымсак соусу, кетчуп, майонез, таза бадыраң, таза помидор, кытай капустасы, картошка фри, мал эт котлети, тоок төш эти, моцарелла быштагы",
                 desc_en="Garlic sauce, ketchup, mayonnaise, fresh cucumber, fresh tomato, napa cabbage, french fries, beef patty, chicken breast, mozzarella",
                 price=300, photo="shaurma_syrnaya"),
            dict(name_ru="Шаурма Мини Классическая", name_ky="Мини классикалык шаурма", name_en="Mini Classic Shawarma",
                 desc_ru="Соус чесночный, соус кетчуп, майонез, огурец свежий, помидор свежий, капуста китайская, картофель фри, говяжий котлет",
                 desc_ky="Сарымсак соусу, кетчуп, майонез, таза бадыраң, таза помидор, кытай капустасы, картошка фри, мал эт котлети",
                 desc_en="Garlic sauce, ketchup, mayonnaise, fresh cucumber, fresh tomato, napa cabbage, french fries, beef patty",
                 price=250, photo="shaurma_mini_klassicheskaya"),
            dict(name_ru="Шаурма Мини Куриная", name_ky="Мини тоок этинен шаурма", name_en="Mini Chicken Shawarma",
                 desc_ru="Соус чесночный, соус кетчуп, майонез, огурец свежий, помидор свежий, капуста китайская, картофель фри, куриная грудка",
                 desc_ky="Сарымсак соусу, кетчуп, майонез, таза бадыраң, таза помидор, кытай капустасы, картошка фри, тоок төш эти",
                 desc_en="Garlic sauce, ketchup, mayonnaise, fresh cucumber, fresh tomato, napa cabbage, french fries, chicken breast",
                 price=230, photo="shaurma_mini_kurinaya"),
        ],
    },
    # ── 8. Бургеры ───────────────────────────────────────────────────────────
    {
        "name_ru": "Бургеры", "name_ky": "Бургерлер", "name_en": "Burgers",
        "items": [
            dict(name_ru="Чикен бургер", name_ky="Тоокчон бургер", name_en="Chicken Burger",
                 desc_ru="Салатный лист, курица, солёные огурцы, помидор, чесночный соус",
                 desc_ky="Салат жалбырагы, тоок эти, туздалган бадыраң, помидор, сарымсак соусу",
                 desc_en="Lettuce, chicken, pickles, tomato, garlic sauce",
                 price=250, photo="chiken_burger"),
            dict(name_ru="Бургер Барбекю", name_ky="Барбекю бургер", name_en="BBQ Burger",
                 desc_ru="Соус барбекю, салатный лист, говяжий котлет, сыр чеддер, помидоры свежие, солёный огурец",
                 desc_ky="Барбекю соусу, салат жалбырагы, мал эт котлети, чеддер быштагы, таза помидор, туздалган бадыраң",
                 desc_en="BBQ sauce, lettuce, beef patty, cheddar, fresh tomatoes, pickle",
                 price=280, photo="burger_barbekyu"),
            dict(name_ru="Бургер Биф", name_ky="Биф бургер", name_en="Beef Burger",
                 desc_ru="Соус фирменный, говяжий котлет, салатный лист, сыр чеддер, солёный огурец, помидор свежий",
                 desc_ky="Фирмалык соус, мал эт котлети, салат жалбырагы, чеддер быштагы, туздалган бадыраң, таза помидор",
                 desc_en="Signature sauce, beef patty, lettuce, cheddar, pickle, fresh tomato",
                 price=280, photo="burger_bif"),
            dict(name_ru="Бургер Чиз", name_ky="Чиз бургер", name_en="Cheese Burger",
                 desc_ru="Соус сырный, говяжий котлет, салатный лист, сыр чеддер, солёный огурец, помидор свежий",
                 desc_ky="Быштак соусу, мал эт котлети, салат жалбырагы, чеддер быштагы, туздалган бадыраң, таза помидор",
                 desc_en="Cheese sauce, beef patty, lettuce, cheddar, pickle, fresh tomato",
                 price=280, photo="burger_chiz"),
            dict(name_ru="Бургер Аура", name_ky="Аура бургер", name_en="Aura Burger",
                 desc_ru="Соус сырный, соус барбекю, картофель фри, яйцо жареное, говяжий котлет, салатный лист, сыр чеддер, солёный огурец, помидор свежий",
                 desc_ky="Быштак соусу, барбекю соусу, картошка фри, куурулган жумуртка, мал эт котлети, салат жалбырагы, чеддер быштагы, туздалган бадыраң, таза помидор",
                 desc_en="Cheese sauce, BBQ sauce, french fries, fried egg, beef patty, lettuce, cheddar, pickle, fresh tomato",
                 price=350, photo="burger_aura"),
            dict(name_ru="Бургер Ассорти", name_ky="Ассорти бургер", name_en="Assorted Burger",
                 desc_ru="Соус чесночный, соус сырный, говяжий котлет, курица, салатный лист, сыр чеддер, солёный огурец, помидор свежий",
                 desc_ky="Сарымсак соусу, быштак соусу, мал эт котлети, тоок эти, салат жалбырагы, чеддер быштагы, туздалган бадыраң, таза помидор",
                 desc_en="Garlic sauce, cheese sauce, beef patty, chicken, lettuce, cheddar, pickle, fresh tomato",
                 price=380, photo="burger_assorti"),
            dict(name_ru="Бургер Двойной", name_ky="Кош бургер", name_en="Double Burger",
                 desc_ru="Соус сырный, соус барбекю, 2 говяжьих котлета, салатный лист, сыр чеддер, солёный огурец, помидор свежий",
                 desc_ky="Быштак соусу, барбекю соусу, 2 мал эт котлети, салат жалбырагы, чеддер быштагы, туздалган бадыраң, таза помидор",
                 desc_en="Cheese sauce, BBQ sauce, 2 beef patties, lettuce, cheddar, pickle, fresh tomato",
                 price=280, photo="burger_dvoynoy"),
        ],
    },
    # ── 9. Хот-доги ──────────────────────────────────────────────────────────
    {
        "name_ru": "Хот-доги", "name_ky": "Хот-дог", "name_en": "Hot Dogs",
        "items": [
            dict(name_ru="Хот дог Классический", name_ky="Классикалык хот-дог", name_en="Classic Hot Dog",
                 desc_ru="Булочка для хот-дог, майонез, соус кетчуп, капуста китайская, помидор свежий, солёный огурец, сосиска",
                 desc_ky="Хот-дог нан, майонез, кетчуп, кытай капустасы, таза помидор, туздалган бадыраң, сосиска",
                 desc_en="Hot dog bun, mayonnaise, ketchup, napa cabbage, fresh tomato, pickle, sausage",
                 price=150, photo="hotdog_klassicheskiy"),
            dict(name_ru="Хот дог Сырный", name_ky="Сырдуу хот-дог", name_en="Cheese Hot Dog",
                 desc_ru="Булочка для хот-дог, майонез, соус сырный, капуста китайская, помидор свежий, солёный огурец, сосиска",
                 desc_ky="Хот-дог нан, майонез, быштак соусу, кытай капустасы, таза помидор, туздалган бадыраң, сосиска",
                 desc_en="Hot dog bun, mayonnaise, cheese sauce, napa cabbage, fresh tomato, pickle, sausage",
                 price=150, photo="hotdog_syrniy"),
            dict(name_ru="Хот дог Говяжий", name_ky="Мал этинен хот-дог", name_en="Beef Hot Dog",
                 desc_ru="Булочка для хот-дог, майонез, чесночный соус, соус кетчуп, капуста китайская, помидор свежий, солёный огурец, говяжья котлета",
                 desc_ky="Хот-дог нан, майонез, сарымсак соусу, кетчуп, кытай капустасы, таза помидор, туздалган бадыраң, мал эт котлети",
                 desc_en="Hot dog bun, mayonnaise, garlic sauce, ketchup, napa cabbage, fresh tomato, pickle, beef patty",
                 price=200, photo="hotdog_govyazhiy"),
            dict(name_ru="Хот дог Куриный", name_ky="Тоок этинен хот-дог", name_en="Chicken Hot Dog",
                 desc_ru="Булочка для хот-дог, майонез, соус кетчуп, соус чесночный, капуста китайская, помидор свежий, солёный огурец, куриная грудка",
                 desc_ky="Хот-дог нан, майонез, кетчуп, сарымсак соусу, кытай капустасы, таза помидор, туздалган бадыраң, тоок төш эти",
                 desc_en="Hot dog bun, mayonnaise, ketchup, garlic sauce, napa cabbage, fresh tomato, pickle, chicken breast",
                 price=180, photo="hotdog_kurinniy"),
        ],
    },
    # ── 10. Рамёны ───────────────────────────────────────────────────────────
    {
        "name_ru": "Рамёны", "name_ky": "Рамён", "name_en": "Ramen",
        "items": [
            dict(name_ru="Рамён с курицей", name_ky="Тоокчон рамён", name_en="Chicken Ramen",
                 desc_ru="Рамён среднеострый, курица, сыр чеддер, яйцо, кунжут, зелень",
                 desc_ky="Орточо ачуу рамён, тоок эти, чеддер быштагы, жумуртка, кунжут, көк өнүм",
                 desc_en="Medium-spicy ramen, chicken, cheddar, egg, sesame, herbs",
                 price=300, photo="ramen_kuritsa"),
            dict(name_ru="Рамён Сырный", name_ky="Сырдуу рамён", name_en="Cheese Ramen",
                 desc_ru="Рамён среднеострый, курица, сыр чеддер, яйцо, кунжут, зелень, сырный соус",
                 desc_ky="Орточо ачуу рамён, тоок эти, чеддер быштагы, жумуртка, кунжут, көк өнүм, быштак соусу",
                 desc_en="Medium-spicy ramen, chicken, cheddar, egg, sesame, herbs, cheese sauce",
                 price=300, photo="ramen_syrniy"),
            dict(name_ru="Рамён Сливочный", name_ky="Каймактуу рамён", name_en="Creamy Ramen",
                 desc_ru="Рамён среднеострый, сливки 22%, курица, сыр чеддер, яйцо, кунжут, зелень",
                 desc_ky="Орточо ачуу рамён, каймак 22%, тоок эти, чеддер быштагы, жумуртка, кунжут, көк өнүм",
                 desc_en="Medium-spicy ramen, 22% cream, chicken, cheddar, egg, sesame, herbs",
                 price=350, photo="ramen_slivochniy"),
        ],
    },
    # ── 11. Гарниры ──────────────────────────────────────────────────────────
    {
        "name_ru": "Гарниры", "name_ky": "Гарнирлер", "name_en": "Side Dishes",
        "items": [
            dict(name_ru="Картофель фри", name_ky="Картошка фри", name_en="French Fries",
                 desc_ru="150 г", desc_ky="150 г", desc_en="150 g",
                 price=150, photo="fri_150"),
            dict(name_ru="Картофель по-деревенски", name_ky="Айылча картошка", name_en="Country-Style Potato Wedges",
                 desc_ru="150 г", desc_ky="150 г", desc_en="150 g",
                 price=180, photo="kartofel_derevenski"),
            dict(name_ru="Наггетсы (6 шт)", name_ky="Наггетстер (6 даана)", name_en="Chicken Nuggets (6 pcs)",
                 price=200, photo="naggetsy"),
            dict(name_ru="Отварной рис", name_ky="Кайнатылган күрүч", name_en="Steamed Rice",
                 desc_ru="200 г", desc_ky="200 г", desc_en="200 g",
                 price=150, photo="otvarnoy_ris"),
        ],
    },
    # ── 12. Крылышки ─────────────────────────────────────────────────────────
    {
        "name_ru": "Крылышки", "name_ky": "Тоок канаты", "name_en": "Chicken Wings",
        "items": [
            dict(name_ru="Крылышки 3 шт", name_ky="Канат 3 даана", name_en="Chicken Wings 3 pcs",
                 price=180, photo="krylyshki_3"),
            dict(name_ru="Крылышки 6 шт", name_ky="Канат 6 даана", name_en="Chicken Wings 6 pcs",
                 price=350, photo="krylyshki_6"),
            dict(name_ru="Крылышки 12 шт", name_ky="Канат 12 даана", name_en="Chicken Wings 12 pcs",
                 price=650, photo="krylyshki_12"),
            dict(name_ru="Крылышки 18 шт", name_ky="Канат 18 даана", name_en="Chicken Wings 18 pcs",
                 price=990, photo="krylyshki_18"),
        ],
    },
    # ── 13. Комбо ────────────────────────────────────────────────────────────
    {
        "name_ru": "Комбо", "name_ky": "Комбо", "name_en": "Combo",
        "items": [
            dict(name_ru="Комбо 1", name_ky="Комбо 1", name_en="Combo 1",
                 desc_ru="Бургер Чикен, картофель фри, кола 0,5 л, соус кетчуп 30 г",
                 desc_ky="Тоокчон бургер, картошка фри, кола 0,5 л, кетчуп 30 г",
                 desc_en="Chicken Burger, french fries, Cola 0.5 L, ketchup 30 g",
                 price=390, photo="kombo1"),
            dict(name_ru="Комбо 2", name_ky="Комбо 2", name_en="Combo 2",
                 desc_ru="Шаурма куриная, бургер Чикен, наггетсы 6 шт, картофель фри 150 г, кола 1 л, соус чесночный 30 г",
                 desc_ky="Тоок этинен шаурма, тоокчон бургер, наггетстер 6 даана, картошка фри 150 г, кола 1 л, сарымсак соусу 30 г",
                 desc_en="Chicken Shawarma, Chicken Burger, nuggets 6 pcs, french fries 150 g, Cola 1 L, garlic sauce 30 g",
                 price=900, photo="kombo2"),
            dict(name_ru="Комбо 3", name_ky="Комбо 3", name_en="Combo 3",
                 desc_ru="Пицца Пепперони, картофель фри 150 г, ролл запечённый с курицей 10 шт, ролл темпура с курицей 10 шт, кола 1 л, соус кетчуп 30 г",
                 desc_ky="Пепперони пицца, картошка фри 150 г, мешинде бышырылган тоокчон ролл 10 даана, тоокчон темпура ролл 10 даана, кола 1 л, кетчуп 30 г",
                 desc_en="Pepperoni Pizza, french fries 150 g, baked chicken roll 10 pcs, chicken tempura roll 10 pcs, Cola 1 L, ketchup 30 g",
                 price=1350, photo="kombo3"),
            dict(name_ru="Комбо 4", name_ky="Комбо 4", name_en="Combo 4",
                 desc_ru="Бургер Аура, картофель фри 150 г, наггетсы 6 шт, кола 1 л",
                 desc_ky="Аура бургер, картошка фри 150 г, наггетстер 6 даана, кола 1 л",
                 desc_en="Aura Burger, french fries 150 g, nuggets 6 pcs, Cola 1 L",
                 price=750, photo="kombo4"),
            dict(name_ru="Комбо 5", name_ky="Комбо 5", name_en="Combo 5",
                 desc_ru="Крылышки 6 шт, наггетсы 6 шт, картофель фри 150 г, пепси 0,5 л",
                 desc_ky="Канат 6 даана, наггетстер 6 даана, картошка фри 150 г, пепси 0,5 л",
                 desc_en="Chicken wings 6 pcs, nuggets 6 pcs, french fries 150 g, Pepsi 0.5 L",
                 price=650, photo="kombo5"),
        ],
    },
    # ── 14. Сеты ─────────────────────────────────────────────────────────────
    {
        "name_ru": "Сеты", "name_ky": "Сеттер", "name_en": "Sharing Sets",
        "items": [
            dict(name_ru="Сет Любовь", name_ky="Сүйүү сети", name_en="Love Set",
                 desc_ru="Запечённый ролл с курицей 10 шт, темпура ролл с курицей 10 шт, крылышки 6 шт",
                 desc_ky="Мешинде бышырылган тоокчон ролл 10 даана, тоокчон темпура ролл 10 даана, канат 6 даана",
                 desc_en="Baked chicken roll 10 pcs, chicken tempura roll 10 pcs, chicken wings 6 pcs",
                 price=990, photo="set_lyubov"),
            dict(name_ru="Сет Семейный", name_ky="Үй-бүлөлүк сет", name_en="Family Set",
                 desc_ru="Пицца Пепперони, пицца Маргарита, запечённый ролл с курицей 10 шт, темпура ролл с курицей 10 шт, мини ролл с огурцом 10 шт, картофель фри 2 порции",
                 desc_ky="Пепперони пицца, Маргарита пицца, мешинде бышырылган тоокчон ролл 10 даана, тоокчон темпура ролл 10 даана, бадыраңдуу мини ролл 10 даана, картошка фри 2 порция",
                 desc_en="Pepperoni Pizza, Margherita Pizza, baked chicken roll 10 pcs, chicken tempura roll 10 pcs, mini cucumber roll 10 pcs, french fries x2",
                 price=2100, photo="set_semeyniy"),
            dict(name_ru="Сет Рамён", name_ky="Рамён сети", name_en="Ramen Set",
                 desc_ru="Рамён с курицей 3 порции, пепси 1 л, нан 1 шт",
                 desc_ky="Тоокчон рамён 3 порция, пепси 1 л, нан 1 даана",
                 desc_en="Chicken ramen x3, Pepsi 1 L, nan bread 1 pc",
                 price=850, photo="set_ramen"),
            dict(name_ru="Сет для студентов", name_ky="Студенттик сет", name_en="Student Set",
                 desc_ru="Чикен бургер 2 шт, шаурма куриная 2 шт, наггетсы 6 шт, картофель фри 150 г, пепси 1 л",
                 desc_ky="Тоокчон бургер 2 даана, тоок этинен шаурма 2 даана, наггетстер 6 даана, картошка фри 150 г, пепси 1 л",
                 desc_en="Chicken Burger x2, Chicken Shawarma x2, nuggets 6 pcs, french fries 150 g, Pepsi 1 L",
                 price=1350, photo="set_studenty"),
            dict(name_ru="Сет Шаурма Ролл", name_ky="Шаурма ролл сети", name_en="Shawarma & Wings Set",
                 desc_ru="Шаурма куриная х3, крылышки 3 шт, наггетсы 3 шт, картофель фри 150 г, соус чесночный 30 г, соус кетчуп 30 г, пепси 1 л в подарок",
                 desc_ky="Тоок этинен шаурма х3, канат 3 даана, наггетстер 3 даана, картошка фри 150 г, сарымсак соусу 30 г, кетчуп 30 г, белекке пепси 1 л",
                 desc_en="Chicken Shawarma x3, chicken wings 3 pcs, nuggets 3 pcs, french fries 150 g, garlic sauce 30 g, ketchup 30 g, free 1 L Pepsi",
                 price=1190, photo="set_shaurma_roll"),
            dict(name_ru="Сет 100", name_ky="Сет 100", name_en="Set 100",
                 desc_ru="Запечённый ролл с курицей, крабом и сыром по 10 шт, темпура ролл с курицей, крабом и сыром по 10 шт, мини с огурцом 10 шт, мини с курицей 20 шт, ролл сырный 10 шт",
                 desc_ky="Мешинде бышырылган тоокчон, крабдуу жана быштактуу роллдор ар бирден 10 даана, тоокчон, крабдуу жана быштактуу темпура роллдор ар бирден 10 даана, бадыраңдуу мини 10 даана, тоокчон мини 20 даана, быштактуу ролл 10 даана",
                 desc_en="Baked rolls (chicken, crab, cheese) 10 pcs each, tempura rolls (chicken, crab, cheese) 10 pcs each, mini cucumber roll 10 pcs, mini chicken roll 20 pcs, cheese roll 10 pcs",
                 price=2900, photo="set_100"),
        ],
    },
]
