# -*- coding: utf-8 -*-
"""
Полное меню кафе «БАРАКАТ кафеси» (г. Кара-Суу, ул. Юлдашева 1).
RU / KY / EN, цены и описания — по PDF-меню (МЕНЮ.pdf, 26 стр.).

Фото: папка photos_barakat/ (по одному файлу на слаг). Все фото взяты
ЦЕЛИКОМ — вытащены как отдельные вложенные изображения из PDF, без обрезки.
"""

CATEGORIES = [
    # ── 1. Салаты ─────────────────────────────────────────────────────────
    {
        "name_ru": "Салаты", "name_ky": "Салаттар", "name_en": "Salads",
        "items": [
            dict(name_ru="Греческий", name_ky="Грек салаты", name_en="Greek Salad",
                 desc_ru="Творожный сыр, помидоры, огурцы, перец болгарский, лук красный, лимонный сок, листья салата, масло оливковое, зелень",
                 desc_ky="Быштак, кызанак, бадыраң, болгар калемпири, кызыл пияз, лимон ширеси, салат жалбырагы, зайтун майы, көк өнүм",
                 desc_en="Cream cheese, tomatoes, cucumbers, bell pepper, red onion, lemon juice, lettuce, olive oil, herbs",
                 price=230, photo="salat_grecheskiy"),
            dict(name_ru="Острый с говядиной", name_ky="Мал эти м/н ачуу салат", name_en="Spicy Beef Salad",
                 desc_ru="Говядина, огурцы, помидоры, болгарский перец, кинза, соевый соус, специи",
                 desc_ky="Мал эти, бадыраң, кызанак, болгар калемпири, кинза, соя соусу, даам берүүчү заттар",
                 desc_en="Beef, cucumbers, tomatoes, bell pepper, cilantro, soy sauce, spices",
                 price=260, photo="salat_ostriy_govyadina"),
            dict(name_ru="Цезарь с курицей", name_ky="Тоок эти м/н Цезарь", name_en="Caesar Salad with Chicken",
                 desc_ru="Салат «Айсберг», жаренная куриная грудка, соус цезарь, сухарики, томаты, сыр пармезан, яйцо",
                 desc_ky="«Айсберг» салаты, куурулган тоок төшү, цезарь соусу, кытырак нан, кызанак, пармезан быштагы, жумуртка",
                 desc_en="Iceberg lettuce, grilled chicken breast, caesar dressing, croutons, tomatoes, parmesan, egg",
                 price=240, photo="salat_cezar"),
            dict(name_ru="Салат с баклажанами", name_ky="Баклажан салаты", name_en="Eggplant Salad",
                 desc_ru="Жаренные баклажаны в крахмале, томаты, соус кисло-сладкий, зелень",
                 desc_ky="Крахмалда куурулган баклажан, кызанак, ачуу-таттуу соус, көк өнүм",
                 desc_en="Crispy fried eggplant, tomatoes, sweet-and-sour sauce, herbs",
                 price=240, photo="salat_baklazhany"),
            dict(name_ru="Шакарап", name_ky="Шакарап", name_en="Shakarap",
                 desc_ru="Томаты, лук, зелень",
                 desc_ky="Кызанак, пияз, көк өнүм",
                 desc_en="Tomatoes, onion, herbs",
                 price=140, photo="salat_shakarap"),
        ],
    },
    # ── 2. Супы ───────────────────────────────────────────────────────────
    {
        "name_ru": "Супы", "name_ky": "Шорполор", "name_en": "Soups",
        "items": [
            dict(name_ru="Мясо по-казахски", name_ky="Казакча эт", name_en="Kazakh-Style Meat (Beshbarmak)",
                 desc_ru="Отварное мясо с домашней лапшой в наваристом бульоне",
                 desc_ky="Кою шорподо үй кесмеси м/н бышырылган эт",
                 desc_en="Boiled meat with homemade noodles in a rich broth",
                 price=240, photo="myaso_pokazahski"),
            dict(name_ru="Шорпо с говядиной", name_ky="Мал этинен шорпо", name_en="Beef Shorpo Soup",
                 desc_ru="Наваристый бульон, говядина, картофель, морковь, болгарский перец, зелень",
                 desc_ky="Кою шорпо, мал эти, картошка, сабиз, болгар калемпири, көк өнүм",
                 desc_en="Rich broth, beef, potato, carrot, bell pepper, herbs",
                 price=260, photo="shorpo_govyadina"),
            dict(name_ru="Чучвара", name_ky="Чүчвара", name_en="Chuchvara (Dumpling Soup)",
                 desc_ru="Мелкие пельмени ручной лепки в прозрачном бульоне с зеленью",
                 desc_ky="Көк өнүм м/н тунук шорподо колго жасалган майда чүчвара",
                 desc_en="Small hand-made dumplings in a clear broth with herbs",
                 price=250, photo="chuchvara"),
        ],
    },
    # ── 3. Уйгурские блюда ────────────────────────────────────────────────
    {
        "name_ru": "Уйгурские блюда", "name_ky": "Уйгур тамактары", "name_en": "Uyghur Dishes",
        "items": [
            dict(name_ru="Лагман 0,7 порции", name_ky="Лагман 0,7 порция", name_en="Lagman 0.7 Portion",
                 desc_ru="Тянутая лапша ручной работы с мясом и овощами",
                 desc_ky="Эт жана жашылча м/н колго тартылган кесме",
                 desc_en="Hand-pulled noodles with meat and vegetables",
                 price=280, photo="lagman"),
            dict(name_ru="Лагман 1 порция", name_ky="Лагман 1 порция", name_en="Lagman Full Portion",
                 desc_ru="Тянутая лапша ручной работы с мясом и овощами, полная порция",
                 desc_ky="Эт жана жашылча м/н колго тартылган кесме, толук порция",
                 desc_en="Hand-pulled noodles with meat and vegetables, full portion",
                 price=300, photo="lagman"),
            dict(name_ru="Жаренный лагман", name_ky="Куурулган лагман", name_en="Fried Lagman",
                 desc_ru="Обжаренная тянутая лапша с мясом и овощами",
                 desc_ky="Эт жана жашылча м/н кууруп бышырылган кесме",
                 desc_en="Stir-fried hand-pulled noodles with meat and vegetables",
                 price=290, photo="lagman"),
            dict(name_ru="Айрим Сей", name_ky="Айрим Сей", name_en="Ayrim Sey",
                 desc_ru="Уйгурское блюдо из мяса с овощами и лапшой",
                 desc_ky="Эт, жашылча жана кесмеден жасалган уйгур тамагы",
                 desc_en="Uyghur dish of meat with vegetables and noodles",
                 price=330, photo="lagman"),
            dict(name_ru="Ган Фан", name_ky="Ган Фан", name_en="Gan Fan",
                 desc_ru="Рис с мясом и овощной подливой по-уйгурски",
                 desc_ky="Уйгурча эт жана жашылча соусу м/н күрүч",
                 desc_en="Rice with meat and vegetable sauce, Uyghur style",
                 price=250, photo="lagman"),
        ],
    },
    # ── 4. Вторые блюда ───────────────────────────────────────────────────
    {
        "name_ru": "Вторые блюда", "name_ky": "Экинчи тамактар", "name_en": "Main Dishes",
        "items": [
            dict(name_ru="Манты 1 шт", name_ky="Манты 1 даана", name_en="Manty 1 pc",
                 desc_ru="Манты ручной лепки на пару, одна штука",
                 desc_ky="Колго жасалган буу мантысы, бир даана",
                 desc_en="Hand-made steamed dumpling, single piece",
                 price=50, photo="manty"),
            dict(name_ru="Манты 1 порция", name_ky="Манты 1 порция", name_en="Manty Portion",
                 desc_ru="Манты ручной лепки на пару, полная порция",
                 desc_ky="Колго жасалган буу мантысы, толук порция",
                 desc_en="Hand-made steamed dumplings, full portion",
                 price=250, photo="manty"),
            dict(name_ru="Бифштекс", name_ky="Бифштекс", name_en="Beef Steak Patty",
                 desc_ru="Сочный бифштекс с картофельным пюре, макаронами и свежими овощами",
                 desc_ky="Картошка пюреси, макарон жана таза жашылча м/н ширелүү бифштекс",
                 desc_en="Juicy beef patty with mashed potato, pasta and fresh vegetables",
                 price=230, photo="bifshteks"),
            dict(name_ru="Гуляш", name_ky="Гуляш", name_en="Goulash",
                 desc_ru="Тушёное мясо в подливе с гарниром из пюре и гречки",
                 desc_ky="Пюре жана гречка гарнири м/н соусто бышырылган эт",
                 desc_en="Braised meat in gravy with mashed potato and buckwheat",
                 price=250, photo="gulyash"),
            dict(name_ru="Казан кебаб", name_ky="Казан кебап", name_en="Kazan Kebab",
                 desc_ru="Мясо, томлёное в казане, с молодым картофелем и красным луком",
                 desc_ky="Жаш картошка жана кызыл пияз м/н казанда бышырылган эт",
                 desc_en="Meat slow-cooked in a cauldron with new potatoes and red onion",
                 price=490, photo="kazan_kebab"),
            dict(name_ru="Чиккен Спайси", name_ky="Чиккен Спайси", name_en="Chicken Spicy",
                 desc_ru="Острая курица с рисом, овощами и соусами",
                 desc_ky="Күрүч, жашылча жана соустар м/н ачуу тоок эти",
                 desc_en="Spicy chicken with rice, vegetables and sauces",
                 price=350, photo="chikken_spaysi"),
            dict(name_ru="Ташкентский плов", name_ky="Ташкент палоо", name_en="Tashkent Plov",
                 desc_ru="Рассыпчатый плов с мясом, морковью, изюмом и перепелиным яйцом",
                 desc_ky="Эт, сабиз, мейиз жана жумуртка м/н даярдалган палоо",
                 desc_en="Fluffy pilaf with meat, carrot, raisins and egg",
                 price=270, photo="tashkentskiy_plov"),
        ],
    },
    # ── 5. Шашлыки ────────────────────────────────────────────────────────
    {
        "name_ru": "Шашлыки", "name_ky": "Шашлыктар", "name_en": "Kebabs",
        "items": [
            dict(name_ru="Оромо шашлык", name_ky="Оромо шашлык", name_en="Oromo Kebab",
                 desc_ru="Шашлык на мангале, подаётся с луком и зеленью",
                 desc_ky="Пияз жана көк өнүм м/н берилген мангал шашлыгы",
                 desc_en="Charcoal-grilled kebab served with onion and herbs",
                 price=140, photo="shashlyk"),
            dict(name_ru="Шашлык из говядины", name_ky="Мал этинен шашлык", name_en="Beef Kebab",
                 desc_ru="Говядина на мангале, подаётся с луком и зеленью",
                 desc_ky="Пияз жана көк өнүм м/н берилген мал этинен мангал шашлыгы",
                 desc_en="Charcoal-grilled beef served with onion and herbs",
                 price=190, photo="shashlyk"),
            dict(name_ru="Шашлык из куриных крылышек", name_ky="Тоок канатынан шашлык", name_en="Chicken Wing Kebab",
                 desc_ru="Куриные крылышки на мангале",
                 desc_ky="Мангалда бышырылган тоок канаттары",
                 desc_en="Charcoal-grilled chicken wings",
                 price=190, photo="shashlyk"),
            dict(name_ru="Люля кебаб", name_ky="Люля кебап", name_en="Lyulya Kebab",
                 desc_ru="Рубленое мясо со специями на шампуре",
                 desc_ky="Даам берүүчү заттар м/н туураган эттен жасалган кебап",
                 desc_en="Minced spiced meat grilled on a skewer",
                 price=120, photo="shashlyk"),
            dict(name_ru="Шашлык из куриного филе", name_ky="Тоок филесинен шашлык", name_en="Chicken Fillet Kebab",
                 desc_ru="Куриное филе на мангале",
                 desc_ky="Мангалда бышырылган тоок филеси",
                 desc_en="Charcoal-grilled chicken fillet",
                 price=120, photo="shashlyk"),
            dict(name_ru="Шашлык из куриного бедра", name_ky="Тоок сан этинен шашлык", name_en="Chicken Thigh Kebab",
                 desc_ru="Куриное бедро на мангале",
                 desc_ky="Мангалда бышырылган тоок сан эти",
                 desc_en="Charcoal-grilled chicken thigh",
                 price=140, photo="shashlyk"),
        ],
    },
    # ── 6. Азиатская кухня ────────────────────────────────────────────────
    {
        "name_ru": "Азиатская кухня", "name_ky": "Азия ашканасы", "name_en": "Asian Cuisine",
        "items": [
            dict(name_ru="Рамен с курицей", name_ky="Тоок эти м/н рамен", name_en="Chicken Ramen",
                 desc_ru="Куриная грудка, куриный бульон, лапша «Рамен», куриное яйцо, сыр, маринованные шампиньоны, зелень",
                 desc_ky="Тоок төшү, тоок шорпосу, «Рамен» кесмеси, жумуртка, быштак, маринаддалган козу карын, көк өнүм",
                 desc_en="Chicken breast, chicken broth, ramen noodles, egg, cheese, marinated mushrooms, herbs",
                 price=280, photo="ramen_kuritsa"),
            dict(name_ru="Рамен с говядиной", name_ky="Мал эти м/н рамен", name_en="Beef Ramen",
                 desc_ru="Говяжья вырезка, говяжий бульон, лапша «Рамен», куриное яйцо, сыр, маринованные шампиньоны, зелень",
                 desc_ky="Мал эти, мал шорпосу, «Рамен» кесмеси, жумуртка, быштак, маринаддалган козу карын, көк өнүм",
                 desc_en="Beef tenderloin, beef broth, ramen noodles, egg, cheese, marinated mushrooms, herbs",
                 price=300, photo="ramen_govyadina"),
            dict(name_ru="Тяхан с говядиной", name_ky="Мал эти м/н тяхан", name_en="Beef Chahan (Fried Rice)",
                 desc_ru="Говядина, рис, болгарский перец, капуста, соус терияки, кунжут, лук, чеснок, морковь",
                 desc_ky="Мал эти, күрүч, болгар калемпири, капуста, терияки соусу, кунжут, пияз, сарымсак, сабиз",
                 desc_en="Beef, rice, bell pepper, cabbage, teriyaki sauce, sesame, onion, garlic, carrot",
                 price=300, photo="tyahan_govyadina"),
            dict(name_ru="Тяхан с курицей", name_ky="Тоок эти м/н тяхан", name_en="Chicken Chahan (Fried Rice)",
                 desc_ru="Курица, рис, болгарский перец, лук, чеснок, морковь, капуста, соус терияки, кунжут",
                 desc_ky="Тоок эти, күрүч, болгар калемпири, пияз, сарымсак, сабиз, капуста, терияки соусу, кунжут",
                 desc_en="Chicken, rice, bell pepper, onion, garlic, carrot, cabbage, teriyaki sauce, sesame",
                 price=280, photo="tyahan_kuritsa"),
            dict(name_ru="Вок с курицей", name_ky="Тоок эти м/н вок", name_en="Chicken Wok",
                 desc_ru="Куриная грудка, лапша удон, болгарский перец, капуста, морковь, лук, белый кунжут, соус Wok",
                 desc_ky="Тоок төшү, удон кесмеси, болгар калемпири, капуста, сабиз, пияз, ак кунжут, Wok соусу",
                 desc_en="Chicken breast, udon noodles, bell pepper, cabbage, carrot, onion, white sesame, wok sauce",
                 price=290, photo="vok_kuritsa"),
            dict(name_ru="Вок с говядиной", name_ky="Мал эти м/н вок", name_en="Beef Wok",
                 desc_ru="Говяжья вырезка, лапша удон, болгарский перец, капуста, морковь, лук, белый кунжут, соус Wok",
                 desc_ky="Мал эти, удон кесмеси, болгар калемпири, капуста, сабиз, пияз, ак кунжут, Wok соусу",
                 desc_en="Beef tenderloin, udon noodles, bell pepper, cabbage, carrot, onion, white sesame, wok sauce",
                 price=310, photo="vok_govyadina"),
            dict(name_ru="Гюдон с курицей", name_ky="Тоок эти м/н гюдон", name_en="Chicken Gyudon",
                 desc_ru="Курица, рис, яйцо, яки соус, соус терияки, масло",
                 desc_ky="Тоок эти, күрүч, жумуртка, яки соусу, терияки соусу, май",
                 desc_en="Chicken, rice, egg, yaki sauce, teriyaki sauce, butter",
                 price=265, photo="gyudon_kuritsa"),
            dict(name_ru="Гюдон с говядиной", name_ky="Мал эти м/н гюдон", name_en="Beef Gyudon",
                 desc_ru="Говядина, рис, яйцо, яки соус, соус терияки, масло",
                 desc_ky="Мал эти, күрүч, жумуртка, яки соусу, терияки соусу, май",
                 desc_en="Beef, rice, egg, yaki sauce, teriyaki sauce, butter",
                 price=285, photo="gyudon_govyadina"),
        ],
    },
    # ── 7. Бургеры ────────────────────────────────────────────────────────
    {
        "name_ru": "Бургеры", "name_ky": "Бургерлер", "name_en": "Burgers",
        "items": [
            dict(name_ru="Гамбургер", name_ky="Гамбургер", name_en="Hamburger",
                 desc_ru="Сочная котлета из говядины, лук, хрустящая зелень, сочные томаты, солёные огурчики, фирменный соус",
                 desc_ky="Ширелүү мал эт котлети, пияз, кытырак жашылча, кызанак, туздалган бадыраң, фирмалык соус",
                 desc_en="Juicy beef patty, onion, crisp lettuce, tomatoes, pickles, signature sauce",
                 price=210, photo="gamburger"),
            dict(name_ru="Чиккенбургер", name_ky="Чиккенбургер", name_en="Chicken Burger",
                 desc_ru="Сочная котлета из филе курицы, хрустящая зелень, сочные томаты, солёные огурчики, лук, фирменный соус",
                 desc_ky="Тоок филесинен котлет, кытырак жашылча, кызанак, туздалган бадыраң, пияз, фирмалык соус",
                 desc_en="Crispy chicken fillet patty, crisp lettuce, tomatoes, pickles, onion, signature sauce",
                 price=200, photo="chikkenburger"),
            dict(name_ru="Чизбургер", name_ky="Чизбургер", name_en="Cheeseburger",
                 desc_ru="Сочная котлета из говядины, сыр, хрустящая зелень, сочные томаты, солёные огурчики, лук, фирменный соус",
                 desc_ky="Ширелүү мал эт котлети, быштак, кытырак жашылча, кызанак, туздалган бадыраң, пияз, фирмалык соус",
                 desc_en="Juicy beef patty, cheese, crisp lettuce, tomatoes, pickles, onion, signature sauce",
                 price=220, photo="chizburger"),
            dict(name_ru="Бигбургер", name_ky="Бигбургер", name_en="Big Burger",
                 desc_ru="Двойная сочная котлета из говядины, грибы жареные, яйцо жареное, сыр чеддер, хрустящая зелень, сочные томаты, солёные огурчики, лук, фирменный соус, соус барбекю, халапеньо",
                 desc_ky="Кош мал эт котлети, куурулган козу карын, куурулган жумуртка, чеддер быштагы, кытырак жашылча, кызанак, туздалган бадыраң, пияз, фирмалык соус, барбекю соусу, халапеньо",
                 desc_en="Double beef patty, fried mushrooms, fried egg, cheddar, crisp lettuce, tomatoes, pickles, onion, signature sauce, BBQ sauce, jalapeño",
                 price=310, photo="bigburger"),
            dict(name_ru="Двойной чизбургер", name_ky="Кош чизбургер", name_en="Double Cheeseburger",
                 desc_ru="Двойная сочная котлета из говядины, сыр, хрустящая зелень, сочные томаты, солёные огурчики, лук, фирменный соус",
                 desc_ky="Кош мал эт котлети, быштак, кытырак жашылча, кызанак, туздалган бадыраң, пияз, фирмалык соус",
                 desc_en="Double beef patty, cheese, crisp lettuce, tomatoes, pickles, onion, signature sauce",
                 price=300, photo="dvoynoy_chizburger"),
            dict(name_ru="Шефбургер", name_ky="Шефбургер", name_en="Chef Burger",
                 desc_ru="Двойная сочная котлета из говядины, жаренное яйцо, сыр, хрустящая зелень, сочные томаты, солёные огурчики, лук, фирменный соус",
                 desc_ky="Кош мал эт котлети, куурулган жумуртка, быштак, кытырак жашылча, кызанак, туздалган бадыраң, пияз, фирмалык соус",
                 desc_en="Double beef patty, fried egg, cheese, crisp lettuce, tomatoes, pickles, onion, signature sauce",
                 price=310, photo="shefburger"),
            dict(name_ru="Наггетсбургер", name_ky="Наггетсбургер", name_en="Nugget Burger",
                 desc_ru="Наггетсы 4 шт, соус чесночный, салат айсберг, помидоры",
                 desc_ky="Наггетс 4 даана, сарымсак соусу, айсберг салаты, кызанак",
                 desc_en="4 chicken nuggets, garlic sauce, iceberg lettuce, tomatoes",
                 price=230, photo="naggetsburger"),
            dict(name_ru="Бургер детский", name_ky="Балдар бургери", name_en="Kids Burger",
                 desc_ru="Сочная котлета, фирменный соус, соус барбекю",
                 desc_ky="Ширелүү котлет, фирмалык соус, барбекю соусу",
                 desc_en="Juicy patty, signature sauce, BBQ sauce",
                 price=140, photo="burger_detskiy"),
        ],
    },
    # ── 8. Шаурма ─────────────────────────────────────────────────────────
    {
        "name_ru": "Шаурма", "name_ky": "Шаурма", "name_en": "Shawarma",
        "items": [
            dict(name_ru="Шаурма с говядиной", name_ky="Мал эти м/н шаурма", name_en="Beef Shawarma",
                 desc_ru="Говядина, свежие овощи и фирменные соусы в тонком лаваше",
                 desc_ky="Жука лавашта мал эти, таза жашылча жана фирмалык соустар",
                 desc_en="Beef, fresh vegetables and signature sauces in thin lavash",
                 price=250, photo="shaurma_govyadina"),
            dict(name_ru="Шаурма с курицей", name_ky="Тоок эти м/н шаурма", name_en="Chicken Shawarma",
                 desc_ru="Курица, свежие овощи и фирменные соусы в тонком лаваше",
                 desc_ky="Жука лавашта тоок эти, таза жашылча жана фирмалык соустар",
                 desc_en="Chicken, fresh vegetables and signature sauces in thin lavash",
                 price=240, photo="shaurma_kuritsa"),
            dict(name_ru="Шаурма ассорти", name_ky="Ассорти шаурма", name_en="Assorted Shawarma",
                 desc_ru="Говядина и курица вместе, свежие овощи и фирменные соусы",
                 desc_ky="Мал эти жана тоок эти чогуу, таза жашылча жана фирмалык соустар",
                 desc_en="Beef and chicken together, fresh vegetables and signature sauces",
                 price=260, photo="shaurma_assorti"),
            dict(name_ru="Шаурма с говядиной запеченная", name_ky="Мал эти м/н бышырылган шаурма",
                 name_en="Baked Beef Shawarma",
                 desc_ru="Говядина, овощи и соусы в запечённом лаваше с чёрным кунжутом",
                 desc_ky="Кара кунжуттуу бышырылган лавашта мал эти, жашылча жана соустар",
                 desc_en="Beef, vegetables and sauces in baked lavash with black sesame",
                 price=260, photo="shaurma_govyadina_zap"),
            dict(name_ru="Шаурма с курицей запеченная", name_ky="Тоок эти м/н бышырылган шаурма",
                 name_en="Baked Chicken Shawarma",
                 desc_ru="Курица, овощи и соусы в запечённом лаваше с чёрным кунжутом",
                 desc_ky="Кара кунжуттуу бышырылган лавашта тоок эти, жашылча жана соустар",
                 desc_en="Chicken, vegetables and sauces in baked lavash with black sesame",
                 price=250, photo="shaurma_kuritsa_zap"),
            dict(name_ru="Шаурма ассорти запеченная", name_ky="Ассорти бышырылган шаурма",
                 name_en="Baked Assorted Shawarma",
                 desc_ru="Говядина и курица, овощи и соусы в запечённом лаваше",
                 desc_ky="Бышырылган лавашта мал эти, тоок эти, жашылча жана соустар",
                 desc_en="Beef and chicken, vegetables and sauces in baked lavash",
                 price=270, photo="shaurma_assorti_zap"),
            dict(name_ru="Бигмастер", name_ky="Бигмастер", name_en="Big Master",
                 desc_ru="Куриные стрипсы, свежая зелень, огурцы и фирменный соус в лаваше",
                 desc_ky="Лавашта тоок стрипси, таза көк өнүм, бадыраң жана фирмалык соус",
                 desc_en="Chicken strips, fresh greens, cucumber and signature sauce in lavash",
                 price=280, photo="bigmaster"),
        ],
    },
    # ── 9. Фастфуд ────────────────────────────────────────────────────────
    {
        "name_ru": "Фастфуд", "name_ky": "Фастфуд", "name_en": "Fast Food",
        "items": [
            dict(name_ru="Стрипсы 4 шт", name_ky="Стрипс 4 даана", name_en="Chicken Strips 4 pcs",
                 desc_ru="Куриные стрипсы в хрустящей панировке",
                 desc_ky="Кытырак панировкадагы тоок стрипси",
                 desc_en="Crispy breaded chicken strips", price=180, photo="stripsy"),
            dict(name_ru="Стрипсы 8 шт", name_ky="Стрипс 8 даана", name_en="Chicken Strips 8 pcs",
                 desc_ru="Куриные стрипсы в хрустящей панировке",
                 desc_ky="Кытырак панировкадагы тоок стрипси",
                 desc_en="Crispy breaded chicken strips", price=340, photo="stripsy"),
            dict(name_ru="Стрипсы 12 шт", name_ky="Стрипс 12 даана", name_en="Chicken Strips 12 pcs",
                 desc_ru="Куриные стрипсы в хрустящей панировке",
                 desc_ky="Кытырак панировкадагы тоок стрипси",
                 desc_en="Crispy breaded chicken strips", price=500, photo="stripsy"),
            dict(name_ru="Стрипсы 24 шт", name_ky="Стрипс 24 даана", name_en="Chicken Strips 24 pcs",
                 desc_ru="Куриные стрипсы в хрустящей панировке, на компанию",
                 desc_ky="Кытырак панировкадагы тоок стрипси, чоң топко",
                 desc_en="Crispy breaded chicken strips, for sharing", price=990, photo="stripsy"),
            dict(name_ru="Стрипсы 30 шт", name_ky="Стрипс 30 даана", name_en="Chicken Strips 30 pcs",
                 desc_ru="Куриные стрипсы в хрустящей панировке, большая порция",
                 desc_ky="Кытырак панировкадагы тоок стрипси, чоң порция",
                 desc_en="Crispy breaded chicken strips, large portion", price=1260, photo="stripsy"),
            dict(name_ru="Крылышки 4 шт", name_ky="Канат 4 даана", name_en="Chicken Wings 4 pcs",
                 desc_ru="Куриные крылышки в хрустящей панировке",
                 desc_ky="Кытырак панировкадагы тоок канаты",
                 desc_en="Crispy breaded chicken wings", price=180, photo="krylyshki"),
            dict(name_ru="Крылышки 8 шт", name_ky="Канат 8 даана", name_en="Chicken Wings 8 pcs",
                 desc_ru="Куриные крылышки в хрустящей панировке",
                 desc_ky="Кытырак панировкадагы тоок канаты",
                 desc_en="Crispy breaded chicken wings", price=340, photo="krylyshki"),
            dict(name_ru="Крылышки 12 шт", name_ky="Канат 12 даана", name_en="Chicken Wings 12 pcs",
                 desc_ru="Куриные крылышки в хрустящей панировке",
                 desc_ky="Кытырак панировкадагы тоок канаты",
                 desc_en="Crispy breaded chicken wings", price=500, photo="krylyshki"),
            dict(name_ru="Крылышки 24 шт", name_ky="Канат 24 даана", name_en="Chicken Wings 24 pcs",
                 desc_ru="Куриные крылышки в хрустящей панировке, на компанию",
                 desc_ky="Кытырак панировкадагы тоок канаты, чоң топко",
                 desc_en="Crispy breaded chicken wings, for sharing", price=990, photo="krylyshki"),
            dict(name_ru="Крылышки 30 шт", name_ky="Канат 30 даана", name_en="Chicken Wings 30 pcs",
                 desc_ru="Куриные крылышки в хрустящей панировке, большая порция",
                 desc_ky="Кытырак панировкадагы тоок канаты, чоң порция",
                 desc_en="Crispy breaded chicken wings, large portion", price=1260, photo="krylyshki"),
            dict(name_ru="Крокеты", name_ky="Крокеттер", name_en="Potato Croquettes",
                 desc_ru="150 гр, подаются с кетчупом",
                 desc_ky="150 гр, кетчуп м/н берилет",
                 desc_en="150 g, served with ketchup", price=150, photo="krokety"),
            dict(name_ru="Наггетсы", name_ky="Наггетстер", name_en="Chicken Nuggets",
                 desc_ru="6 шт, подаются с кетчупом",
                 desc_ky="6 даана, кетчуп м/н берилет",
                 desc_en="6 pcs, served with ketchup", price=180, photo="naggetsy"),
            dict(name_ru="Картошка фри", name_ky="Картошка фри", name_en="French Fries",
                 desc_ru="150 гр, подаётся с кетчупом",
                 desc_ky="150 гр, кетчуп м/н берилет",
                 desc_en="150 g, served with ketchup", price=150, photo="kartoshka_fri"),
            dict(name_ru="Картошка по-деревенски", name_ky="Айылча картошка", name_en="Country-Style Potatoes",
                 desc_ru="150 гр, подаётся с кетчупом",
                 desc_ky="150 гр, кетчуп м/н берилет",
                 desc_en="150 g, served with ketchup", price=160, photo="kartoshka_derevenski"),
        ],
    },
    # ── 10. Пиццы ─────────────────────────────────────────────────────────
    {
        "name_ru": "Пиццы", "name_ky": "Пиццалар", "name_en": "Pizza",
        "items": [
            dict(name_ru="Пицца Маргарита 35 см", name_ky="Маргарита пицца 35 см", name_en="Margherita Pizza 35 cm",
                 desc_ru="Сыр моцарелла, фирменный томатный соус",
                 desc_ky="Моцарелла быштагы, фирмалык кызанак соусу",
                 desc_en="Mozzarella, signature tomato sauce", price=420, photo="pizza_margarita"),
            dict(name_ru="Пицца Маргарита 40 см", name_ky="Маргарита пицца 40 см", name_en="Margherita Pizza 40 cm",
                 desc_ru="Сыр моцарелла, фирменный томатный соус",
                 desc_ky="Моцарелла быштагы, фирмалык кызанак соусу",
                 desc_en="Mozzarella, signature tomato sauce", price=450, photo="pizza_margarita"),
            dict(name_ru="Пицца Пепперони 35 см", name_ky="Пепперони пицца 35 см", name_en="Pepperoni Pizza 35 cm",
                 desc_ru="Колбаса пепперони, фирменный томатный соус, сыр моцарелла",
                 desc_ky="Пепперони колбасасы, фирмалык кызанак соусу, моцарелла быштагы",
                 desc_en="Pepperoni, signature tomato sauce, mozzarella", price=520, photo="pizza_pepperoni"),
            dict(name_ru="Пицца Пепперони 40 см", name_ky="Пепперони пицца 40 см", name_en="Pepperoni Pizza 40 cm",
                 desc_ru="Колбаса пепперони, фирменный томатный соус, сыр моцарелла",
                 desc_ky="Пепперони колбасасы, фирмалык кызанак соусу, моцарелла быштагы",
                 desc_en="Pepperoni, signature tomato sauce, mozzarella", price=570, photo="pizza_pepperoni"),
            dict(name_ru="Пицца Курица с грибами 35 см", name_ky="Тоок жана козу карын пицца 35 см",
                 name_en="Chicken & Mushroom Pizza 35 cm",
                 desc_ru="Сочное филе курицы, маринованные грибы шампиньоны, фирменный томатный соус, сыр моцарелла",
                 desc_ky="Тоок филеси, маринаддалган козу карын, фирмалык кызанак соусу, моцарелла быштагы",
                 desc_en="Chicken fillet, marinated mushrooms, signature tomato sauce, mozzarella",
                 price=520, photo="pizza_kuritsa_gribami"),
            dict(name_ru="Пицца Курица с грибами 40 см", name_ky="Тоок жана козу карын пицца 40 см",
                 name_en="Chicken & Mushroom Pizza 40 cm",
                 desc_ru="Сочное филе курицы, маринованные грибы шампиньоны, фирменный томатный соус, сыр моцарелла",
                 desc_ky="Тоок филеси, маринаддалган козу карын, фирмалык кызанак соусу, моцарелла быштагы",
                 desc_en="Chicken fillet, marinated mushrooms, signature tomato sauce, mozzarella",
                 price=570, photo="pizza_kuritsa_gribami"),
            dict(name_ru="Пицца Цезарь 35 см", name_ky="Цезарь пицца 35 см", name_en="Caesar Pizza 35 cm",
                 desc_ru="Салат айсберг, жаренная куриная грудка, соус цезарь, сухарики, томаты, сыр пармезан, сыр моцарелла",
                 desc_ky="Айсберг салаты, куурулган тоок төшү, цезарь соусу, кытырак нан, кызанак, пармезан, моцарелла",
                 desc_en="Iceberg lettuce, grilled chicken, caesar dressing, croutons, tomatoes, parmesan, mozzarella",
                 price=520, photo="pizza_cezar"),
            dict(name_ru="Пицца Цезарь 40 см", name_ky="Цезарь пицца 40 см", name_en="Caesar Pizza 40 cm",
                 desc_ru="Салат айсберг, жаренная куриная грудка, соус цезарь, сухарики, томаты, сыр пармезан, сыр моцарелла",
                 desc_ky="Айсберг салаты, куурулган тоок төшү, цезарь соусу, кытырак нан, кызанак, пармезан, моцарелла",
                 desc_en="Iceberg lettuce, grilled chicken, caesar dressing, croutons, tomatoes, parmesan, mozzarella",
                 price=570, photo="pizza_cezar"),
            dict(name_ru="Пицца 4 сыра 35 см", name_ky="4 быштак пицца 35 см", name_en="Four Cheese Pizza 35 cm",
                 desc_ru="Сыр моцарелла, сыр чеддер, сыр пармезан, сыр голландский",
                 desc_ky="Моцарелла, чеддер, пармезан жана голланд быштактары",
                 desc_en="Mozzarella, cheddar, parmesan and Dutch cheese", price=520, photo="pizza_4syra"),
            dict(name_ru="Пицца 4 сыра 40 см", name_ky="4 быштак пицца 40 см", name_en="Four Cheese Pizza 40 cm",
                 desc_ru="Сыр моцарелла, сыр чеддер, сыр пармезан, сыр голландский",
                 desc_ky="Моцарелла, чеддер, пармезан жана голланд быштактары",
                 desc_en="Mozzarella, cheddar, parmesan and Dutch cheese", price=570, photo="pizza_4syra"),
            dict(name_ru="Пицца Баварская 35 см", name_ky="Бавар пицца 35 см", name_en="Bavarian Pizza 35 cm",
                 desc_ru="Пикантные сосиски, колбаса пепперони, охотничьи колбаски, красный болгарский перец, фирменный томатный соус, сыр моцарелла",
                 desc_ky="Ачуу сосиска, пепперони, аңчы колбаскалары, кызыл болгар калемпири, фирмалык кызанак соусу, моцарелла",
                 desc_en="Spicy sausages, pepperoni, hunter sausages, red bell pepper, signature tomato sauce, mozzarella",
                 price=620, photo="pizza_bavarskaya"),
            dict(name_ru="Пицца Баварская 40 см", name_ky="Бавар пицца 40 см", name_en="Bavarian Pizza 40 cm",
                 desc_ru="Пикантные сосиски, колбаса пепперони, охотничьи колбаски, красный болгарский перец, фирменный томатный соус, сыр моцарелла",
                 desc_ky="Ачуу сосиска, пепперони, аңчы колбаскалары, кызыл болгар калемпири, фирмалык кызанак соусу, моцарелла",
                 desc_en="Spicy sausages, pepperoni, hunter sausages, red bell pepper, signature tomato sauce, mozzarella",
                 price=670, photo="pizza_bavarskaya"),
            dict(name_ru="Пицца Мексиканская 35 см", name_ky="Мексика пицца 35 см", name_en="Mexican Pizza 35 cm",
                 desc_ru="Говядина, филе сочной курицы, фирменный томатный соус, красный болгарский перец, сыр моцарелла, острый соус",
                 desc_ky="Мал эти, тоок филеси, фирмалык кызанак соусу, кызыл болгар калемпири, моцарелла, ачуу соус",
                 desc_en="Beef, chicken fillet, signature tomato sauce, red bell pepper, mozzarella, hot sauce",
                 price=550, photo="pizza_meksikanskaya"),
            dict(name_ru="Пицца Мексиканская 40 см", name_ky="Мексика пицца 40 см", name_en="Mexican Pizza 40 cm",
                 desc_ru="Говядина, филе сочной курицы, фирменный томатный соус, красный болгарский перец, сыр моцарелла, острый соус",
                 desc_ky="Мал эти, тоок филеси, фирмалык кызанак соусу, кызыл болгар калемпири, моцарелла, ачуу соус",
                 desc_en="Beef, chicken fillet, signature tomato sauce, red bell pepper, mozzarella, hot sauce",
                 price=600, photo="pizza_meksikanskaya"),
            dict(name_ru="Пицца 4 сезона 35 см", name_ky="4 мезгил пицца 35 см", name_en="Four Seasons Pizza 35 cm",
                 desc_ru="Куриная грудка, говядина, колбаса пепперони, сочные сосиски, фирменный томатный соус, сыр моцарелла",
                 desc_ky="Тоок төшү, мал эти, пепперони, сосиска, фирмалык кызанак соусу, моцарелла",
                 desc_en="Chicken breast, beef, pepperoni, sausages, signature tomato sauce, mozzarella",
                 price=620, photo="pizza_4sezona"),
            dict(name_ru="Пицца 4 сезона 40 см", name_ky="4 мезгил пицца 40 см", name_en="Four Seasons Pizza 40 cm",
                 desc_ru="Куриная грудка, говядина, колбаса пепперони, сочные сосиски, фирменный томатный соус, сыр моцарелла",
                 desc_ky="Тоок төшү, мал эти, пепперони, сосиска, фирмалык кызанак соусу, моцарелла",
                 desc_en="Chicken breast, beef, pepperoni, sausages, signature tomato sauce, mozzarella",
                 price=670, photo="pizza_4sezona"),
            dict(name_ru="Пицца Мясное ассорти 35 см", name_ky="Эт ассорти пицца 35 см", name_en="Meat Platter Pizza 35 cm",
                 desc_ru="Говядина, сочная курица, красный болгарский перец, оливки, лук красный, помидоры, зелень",
                 desc_ky="Мал эти, тоок эти, кызыл болгар калемпири, зайтун, кызыл пияз, кызанак, көк өнүм",
                 desc_en="Beef, chicken, red bell pepper, olives, red onion, tomatoes, herbs",
                 price=620, photo="pizza_myasnoe_assorti"),
            dict(name_ru="Пицца Мясное ассорти 40 см", name_ky="Эт ассорти пицца 40 см", name_en="Meat Platter Pizza 40 cm",
                 desc_ru="Говядина, сочная курица, красный болгарский перец, оливки, лук красный, помидоры, зелень",
                 desc_ky="Мал эти, тоок эти, кызыл болгар калемпири, зайтун, кызыл пияз, кызанак, көк өнүм",
                 desc_en="Beef, chicken, red bell pepper, olives, red onion, tomatoes, herbs",
                 price=670, photo="pizza_myasnoe_assorti"),
            dict(name_ru="Пицца Тайская 35 см", name_ky="Тай пицца 35 см", name_en="Thai Pizza 35 cm",
                 desc_ru="Сыр моцарелла, голландский сыр, говядина, помидоры, халапеньо, барбекю соус",
                 desc_ky="Моцарелла, голланд быштагы, мал эти, кызанак, халапеньо, барбекю соусу",
                 desc_en="Mozzarella, Dutch cheese, beef, tomatoes, jalapeño, BBQ sauce",
                 price=620, photo="pizza_tayskaya"),
            dict(name_ru="Пицца Тайская 40 см", name_ky="Тай пицца 40 см", name_en="Thai Pizza 40 cm",
                 desc_ru="Сыр моцарелла, голландский сыр, говядина, помидоры, халапеньо, барбекю соус",
                 desc_ky="Моцарелла, голланд быштагы, мал эти, кызанак, халапеньо, барбекю соусу",
                 desc_en="Mozzarella, Dutch cheese, beef, tomatoes, jalapeño, BBQ sauce",
                 price=670, photo="pizza_tayskaya"),
        ],
    },
    # ── 11. Комбо ─────────────────────────────────────────────────────────
    {
        "name_ru": "Комбо", "name_ky": "Комбо", "name_en": "Combo Deals",
        "items": [
            dict(name_ru="Комбо на одного", name_ky="Бирөөгө комбо", name_en="Combo for One",
                 desc_ru="Чизбургер, фри, кетчуп, Salam Premium Cola 0,5",
                 desc_ky="Чизбургер, фри, кетчуп, Salam Premium Cola 0,5",
                 desc_en="Cheeseburger, fries, ketchup, Salam Premium Cola 0.5",
                 price=400, photo="kombo_odnogo"),
            dict(name_ru="Комбо на двоих", name_ky="Экөөгө комбо", name_en="Combo for Two",
                 desc_ru="Чизбургер, чиккенбургер, 2 фри, 2 кетчупа, Salam Premium Cola 1 л",
                 desc_ky="Чизбургер, чиккенбургер, 2 фри, 2 кетчуп, Salam Premium Cola 1 л",
                 desc_en="Cheeseburger, chicken burger, 2 fries, 2 ketchups, Salam Premium Cola 1 L",
                 price=750, photo="kombo_dvoih"),
            dict(name_ru="Комбо с шаурмой", name_ky="Шаурма м/н комбо", name_en="Shawarma Combo",
                 desc_ru="Шаурма на ваш выбор (курица/говядина), фри, кетчуп, Salam Premium Cola 0,5",
                 desc_ky="Тандооңуз боюнча шаурма (тоок/мал эти), фри, кетчуп, Salam Premium Cola 0,5",
                 desc_en="Shawarma of your choice (chicken/beef), fries, ketchup, Salam Premium Cola 0.5",
                 price=450, photo="kombo_shaurma"),
            dict(name_ru="Комбо для меня", name_ky="Мен үчүн комбо", name_en="Combo for Me",
                 desc_ru="Мини запеченный ролл с крабом, картошка по-деревенски, Salam Premium Cola 0,5, кетчуп",
                 desc_ky="Краб м/н мини бышырылган ролл, айылча картошка, Salam Premium Cola 0,5, кетчуп",
                 desc_en="Mini baked crab roll, country-style potatoes, Salam Premium Cola 0.5, ketchup",
                 price=420, photo="kombo_dlya_menya"),
            dict(name_ru="Комбо детский", name_ky="Балдар комбосу", name_en="Kids Combo",
                 desc_ru="Детский бургер, картошка фри, сок «Нектар», кетчуп",
                 desc_ky="Балдар бургери, картошка фри, «Нектар» ширеси, кетчуп",
                 desc_en="Kids burger, french fries, Nektar juice, ketchup",
                 price=300, photo="kombo_detskiy"),
            dict(name_ru="Комбо «Семейный»", name_ky="«Үй-бүлөлүк» комбо", name_en="Family Combo",
                 desc_ru="Пепперони 35 см, чизбургер, куриный бургер, 2 фри, картошка по-деревенски, 3 соуса, 8 крылышек, Salam Premium Cola 1,5 л",
                 desc_ky="Пепперони 35 см, чизбургер, тоок бургери, 2 фри, айылча картошка, 3 соус, 8 канат, Salam Premium Cola 1,5 л",
                 desc_en="Pepperoni 35 cm, cheeseburger, chicken burger, 2 fries, country potatoes, 3 sauces, 8 wings, Salam Premium Cola 1.5 L",
                 price=1850, photo="kombo_semeyniy"),
            dict(name_ru="Комбо «Любимый»", name_ky="«Сүйүктүү» комбо", name_en="Favourite Combo",
                 desc_ru="Крылышки 12 шт, пепперони 40 см, картошка по-деревенски, кетчуп, соус чесночный, Salam Premium Cola 1 л",
                 desc_ky="12 канат, пепперони 40 см, айылча картошка, кетчуп, сарымсак соусу, Salam Premium Cola 1 л",
                 desc_en="12 wings, pepperoni 40 cm, country potatoes, ketchup, garlic sauce, Salam Premium Cola 1 L",
                 price=1290, photo="kombo_lyubimiy"),
            dict(name_ru="Комбо «Люкс»", name_ky="«Люкс» комбо", name_en="Lux Combo",
                 desc_ru="Пепперони 40 см, Salam Premium Cola 1 л, сет запеченный 24 шт",
                 desc_ky="Пепперони 40 см, Salam Premium Cola 1 л, бышырылган сет 24 даана",
                 desc_en="Pepperoni 40 cm, Salam Premium Cola 1 L, baked roll set 24 pcs",
                 price=1450, photo="kombo_lyuks"),
            dict(name_ru="Комбо «Три пиццы»", name_ky="«Үч пицца» комбо", name_en="Three Pizzas Combo",
                 desc_ru="Пепперони 35 см, Маргарита 35 см, пицца с курицей 35 см",
                 desc_ky="Пепперони 35 см, Маргарита 35 см, тоок эти м/н пицца 35 см",
                 desc_en="Pepperoni 35 cm, Margherita 35 cm, chicken pizza 35 cm",
                 price=1250, photo="kombo_tri_piccy"),
            dict(name_ru="Комбо «Чиккен баскет»", name_ky="«Чиккен баскет» комбо", name_en="Chicken Basket Combo",
                 desc_ru="Крылышки 30 шт, 2 соуса, 2 фри, Salam Premium Cola 1 л",
                 desc_ky="30 канат, 2 соус, 2 фри, Salam Premium Cola 1 л",
                 desc_en="30 wings, 2 sauces, 2 fries, Salam Premium Cola 1 L",
                 price=1599, photo="kombo_chikken_basket"),
            dict(name_ru="Комбо «Баракат»", name_ky="«Баракат» комбо", name_en="Barakat Combo",
                 desc_ru="Пепперони 35 см, крылышки 12 шт, сет запечённый, фри 2 порции, Salam Premium Cola 1 л",
                 desc_ky="Пепперони 35 см, 12 канат, бышырылган сет, 2 порция фри, Salam Premium Cola 1 л",
                 desc_en="Pepperoni 35 cm, 12 wings, baked roll set, 2 portions of fries, Salam Premium Cola 1 L",
                 price=1999, photo="kombo_barakat"),
            dict(name_ru="Комбо «Дастархан»", name_ky="«Дасторкон» комбо", name_en="Dastarkhan Combo",
                 desc_ru="Пицца «Курица с грибами» 35 см, пицца «Пепперони» 35 см, сет «Мега Хит», крылышки 20 шт, 2 фри, Salam Premium Cola 2 л, 3 соуса (кетчуп, чесночный, сырный)",
                 desc_ky="«Тоок жана козу карын» пицца 35 см, «Пепперони» пицца 35 см, «Мега Хит» сети, 20 канат, 2 фри, Salam Premium Cola 2 л, 3 соус",
                 desc_en="Chicken & mushroom pizza 35 cm, pepperoni pizza 35 cm, Mega Hit roll set, 20 wings, 2 fries, Salam Premium Cola 2 L, 3 sauces",
                 price=3799, photo="kombo_dastarhan"),
        ],
    },
    # ── 12. Классические роллы ────────────────────────────────────────────
    {
        "name_ru": "Классические роллы", "name_ky": "Классикалык роллдор", "name_en": "Classic Rolls",
        "items": [
            dict(name_ru="Филадельфия", name_ky="Филадельфия", name_en="Philadelphia",
                 desc_ru="Лосось, сливочный сыр, огурец",
                 desc_ky="Лосось, каймак быштагы, бадыраң",
                 desc_en="Salmon, cream cheese, cucumber", price=350, photo="roll_filadelfiya"),
            dict(name_ru="Филадельфия дуэт", name_ky="Филадельфия дуэт", name_en="Philadelphia Duet",
                 desc_ru="Лосось, угорь, творожный сыр, огурец, соус унаги, белый кунжут",
                 desc_ky="Лосось, жылан балык, быштак, бадыраң, унаги соусу, ак кунжут",
                 desc_en="Salmon, eel, cream cheese, cucumber, unagi sauce, white sesame",
                 price=370, photo="roll_filadelfiya_duet"),
            dict(name_ru="Канада", name_ky="Канада", name_en="Canada",
                 desc_ru="Угорь, лосось, творожный сыр, соус унаги, огурец, белый кунжут",
                 desc_ky="Жылан балык, лосось, быштак, унаги соусу, бадыраң, ак кунжут",
                 desc_en="Eel, salmon, cream cheese, unagi sauce, cucumber, white sesame",
                 price=380, photo="roll_kanada"),
            dict(name_ru="Калифорния с крабом", name_ky="Краб м/н Калифорния", name_en="California with Crab",
                 desc_ru="Крабовые палочки, огурец, икра тобико",
                 desc_ky="Краб таякчалары, бадыраң, тобико уурулдугу",
                 desc_en="Crab sticks, cucumber, tobiko caviar", price=340, photo="roll_kaliforniya_krab"),
            dict(name_ru="Калифорния с лососем", name_ky="Лосось м/н Калифорния", name_en="California with Salmon",
                 desc_ru="Лосось, творожный сыр, огурец, икра тобико",
                 desc_ky="Лосось, быштак, бадыраң, тобико уурулдугу",
                 desc_en="Salmon, cream cheese, cucumber, tobiko caviar", price=360, photo="roll_kaliforniya_losos"),
            dict(name_ru="Окинава с лососем", name_ky="Лосось м/н Окинава", name_en="Okinawa with Salmon",
                 desc_ru="Лосось, сыр творожный, огурец",
                 desc_ky="Лосось, быштак, бадыраң",
                 desc_en="Salmon, cream cheese, cucumber", price=330, photo="roll_okinava_losos"),
            dict(name_ru="Киото с лососем", name_ky="Лосось м/н Киото", name_en="Kyoto with Salmon",
                 desc_ru="Творожный сыр, лосось, огурец, соус терияки, икра тобико, соус унаги, фирменный соус",
                 desc_ky="Быштак, лосось, бадыраң, терияки соусу, тобико, унаги соусу, фирмалык соус",
                 desc_en="Cream cheese, salmon, cucumber, teriyaki, tobiko caviar, unagi sauce, signature sauce",
                 price=360, photo="roll_kioto_losos"),
            dict(name_ru="Киото с угрем", name_ky="Жылан балык м/н Киото", name_en="Kyoto with Eel",
                 desc_ru="Угорь, творожный сыр, фирменный соус, соус унаги, икра тобико, белый кунжут",
                 desc_ky="Жылан балык, быштак, фирмалык соус, унаги соусу, тобико, ак кунжут",
                 desc_en="Eel, cream cheese, signature sauce, unagi sauce, tobiko caviar, white sesame",
                 price=370, photo="roll_kioto_ugor"),
            dict(name_ru="Пирамида с лососем", name_ky="Лосось м/н Пирамида", name_en="Pyramid with Salmon",
                 desc_ru="Лосось, творожный сыр, огурец, икра тобико",
                 desc_ky="Лосось, быштак, бадыраң, тобико уурулдугу",
                 desc_en="Salmon, cream cheese, cucumber, tobiko caviar", price=350, photo="roll_piramida_losos"),
        ],
    },
    # ── 13. Запеченные роллы ──────────────────────────────────────────────
    {
        "name_ru": "Запеченные роллы", "name_ky": "Бышырылган роллдор", "name_en": "Baked Rolls",
        "items": [
            dict(name_ru="Запеченный сырный", name_ky="Бышырылган быштактуу", name_en="Baked Cheese Roll",
                 desc_ru="Творожный сыр, огурец, крабовые палочки, сырная шапочка",
                 desc_ky="Быштак, бадыраң, краб таякчалары, быштак калпакчасы",
                 desc_en="Cream cheese, cucumber, crab sticks, baked cheese cap",
                 price=340, photo="roll_zap_syrniy"),
            dict(name_ru="Запеченный с угрем", name_ky="Жылан балык м/н бышырылган", name_en="Baked Roll with Eel",
                 desc_ru="Угорь, творожный сыр, огурец, соус унаги, куриная грудка",
                 desc_ky="Жылан балык, быштак, бадыраң, унаги соусу, тоок төшү",
                 desc_en="Eel, cream cheese, cucumber, unagi sauce, chicken breast",
                 price=370, photo="roll_zap_ugor"),
            dict(name_ru="Запеченная Калифорния", name_ky="Бышырылган Калифорния", name_en="Baked California",
                 desc_ru="Крабовые палочки, сыр творожный, икра тобико, огурец, соус унаги",
                 desc_ky="Краб таякчалары, быштак, тобико, бадыраң, унаги соусу",
                 desc_en="Crab sticks, cream cheese, tobiko caviar, cucumber, unagi sauce",
                 price=350, photo="roll_zap_kaliforniya"),
            dict(name_ru="Опаленный лосось", name_ky="Күйгүзүлгөн лосось", name_en="Seared Salmon Roll",
                 desc_ru="Крабовые палочки, сыр творожный, икра тобико, огурец, соус унаги, лосось, кунжут",
                 desc_ky="Краб таякчалары, быштак, тобико, бадыраң, унаги соусу, лосось, кунжут",
                 desc_en="Crab sticks, cream cheese, tobiko caviar, cucumber, unagi sauce, salmon, sesame",
                 price=370, photo="roll_opalenniy_losos"),
            dict(name_ru="Чиккен чиз", name_ky="Чиккен чиз", name_en="Chicken Cheese Roll",
                 desc_ru="Куриная грудка, сыр творожный, огурец, сырная шапочка, соус унаги",
                 desc_ky="Тоок төшү, быштак, бадыраң, быштак калпакчасы, унаги соусу",
                 desc_en="Chicken breast, cream cheese, cucumber, baked cheese cap, unagi sauce",
                 price=340, photo="roll_chikken_chiz"),
            dict(name_ru="Запеченная Флорида", name_ky="Бышырылган Флорида", name_en="Baked Florida",
                 desc_ru="Крабовые палочки, сыр творожный, икра тобико, огурец, соус унаги",
                 desc_ky="Краб таякчалары, быштак, тобико, бадыраң, унаги соусу",
                 desc_en="Crab sticks, cream cheese, tobiko caviar, cucumber, unagi sauce",
                 price=340, photo="roll_zap_florida"),
            dict(name_ru="Запеченный лосось", name_ky="Бышырылган лосось", name_en="Baked Salmon Roll",
                 desc_ru="Лосось терияки, творожный сыр, огурец, масаго, соус спайси, кунжут",
                 desc_ky="Терияки лосось, быштак, бадыраң, масаго, спайси соусу, кунжут",
                 desc_en="Teriyaki salmon, cream cheese, cucumber, masago, spicy sauce, sesame",
                 price=350, photo="roll_zap_losos"),
            dict(name_ru="Итальянский ролл", name_ky="Италия роллу", name_en="Italian Roll",
                 desc_ru="Крабовые палочки, сыр Чеддер, сыр творожный, огурец, соус унаги",
                 desc_ky="Краб таякчалары, Чеддер быштагы, быштак, бадыраң, унаги соусу",
                 desc_en="Crab sticks, cheddar, cream cheese, cucumber, unagi sauce",
                 price=350, photo="roll_italyanskiy"),
            dict(name_ru="Шеф ролл", name_ky="Шеф ролл", name_en="Chef Roll",
                 desc_ru="Творожный сыр, огурец маринованный, крабовые палочки, сыр чеддер, халапеньо",
                 desc_ky="Быштак, маринаддалган бадыраң, краб таякчалары, чеддер быштагы, халапеньо",
                 desc_en="Cream cheese, pickled cucumber, crab sticks, cheddar, jalapeño",
                 price=370, photo="roll_shef"),
            dict(name_ru="Ролл нежный", name_ky="Назик ролл", name_en="Tender Roll",
                 desc_ru="Творожный сыр, огурец, сыр чеддер, фирменный соус",
                 desc_ky="Быштак, бадыраң, чеддер быштагы, фирмалык соус",
                 desc_en="Cream cheese, cucumber, cheddar, signature sauce",
                 price=320, photo="roll_nezhniy"),
        ],
    },
    # ── 14. Жаренные роллы ────────────────────────────────────────────────
    {
        "name_ru": "Жаренные роллы", "name_ky": "Куурулган роллдор", "name_en": "Tempura Rolls",
        "items": [
            dict(name_ru="Темпура Филадельфия", name_ky="Темпура Филадельфия", name_en="Tempura Philadelphia",
                 desc_ru="Лосось, сливочный сыр, огурец, икра тобико",
                 desc_ky="Лосось, каймак быштагы, бадыраң, тобико",
                 desc_en="Salmon, cream cheese, cucumber, tobiko caviar",
                 price=390, photo="roll_tempura_filadelfiya"),
            dict(name_ru="Темпура Калифорния", name_ky="Темпура Калифорния", name_en="Tempura California",
                 desc_ru="Крабовые палочки, огурец, икра тобико",
                 desc_ky="Краб таякчалары, бадыраң, тобико",
                 desc_en="Crab sticks, cucumber, tobiko caviar",
                 price=370, photo="roll_tempura_kaliforniya"),
            dict(name_ru="Темпура Канада", name_ky="Темпура Канада", name_en="Tempura Canada",
                 desc_ru="Угорь, лосось, сливочный сыр, огурец",
                 desc_ky="Жылан балык, лосось, каймак быштагы, бадыраң",
                 desc_en="Eel, salmon, cream cheese, cucumber",
                 price=390, photo="roll_tempura_kanada"),
            dict(name_ru="Темпура с курицей", name_ky="Тоок эти м/н темпура", name_en="Tempura with Chicken",
                 desc_ru="Куриная грудка, творожный сыр, огурец",
                 desc_ky="Тоок төшү, быштак, бадыраң",
                 desc_en="Chicken breast, cream cheese, cucumber",
                 price=370, photo="roll_tempura_kuritsa"),
        ],
    },
    # ── 15. Мини роллы ────────────────────────────────────────────────────
    {
        "name_ru": "Мини роллы", "name_ky": "Мини роллдор", "name_en": "Mini Rolls",
        "items": [
            dict(name_ru="Роллы с лососем", name_ky="Лосось м/н роллдор", name_en="Salmon Mini Rolls",
                 desc_ru="Лосось", desc_ky="Лосось", desc_en="Salmon",
                 price=160, photo="mini_losos"),
            dict(name_ru="Роллы с огурцом", name_ky="Бадыраң м/н роллдор", name_en="Cucumber Mini Rolls",
                 desc_ru="Огурец", desc_ky="Бадыраң", desc_en="Cucumber",
                 price=90, photo="mini_ogurets"),
            dict(name_ru="Роллы с угрем", name_ky="Жылан балык м/н роллдор", name_en="Eel Mini Rolls",
                 desc_ru="Угорь, соус унаги, белый кунжут",
                 desc_ky="Жылан балык, унаги соусу, ак кунжут",
                 desc_en="Eel, unagi sauce, white sesame",
                 price=180, photo="mini_ugor"),
        ],
    },
    # ── 16. Сеты ──────────────────────────────────────────────────────────
    {
        "name_ru": "Сеты", "name_ky": "Сеттер", "name_en": "Roll Sets",
        "items": [
            dict(name_ru="Сет Харакири", name_ky="Харакири сети", name_en="Harakiri Set",
                 desc_ru="Ролл Филадельфия, ролл Калифорния с крабом, ролл Калифорния с кунжутом, ролл с огурцом",
                 desc_ky="Филадельфия ролл, краб м/н Калифорния, кунжут м/н Калифорния, бадыраң м/н ролл",
                 desc_en="Philadelphia roll, California with crab, California with sesame, cucumber roll",
                 price=1090, photo="set_harakiri"),
            dict(name_ru="Сет Темпура", name_ky="Темпура сети", name_en="Tempura Set",
                 desc_ru="Темпура с курицей, ролл Калифорния темпура, ролл Филадельфия темпура",
                 desc_ky="Тоок м/н темпура, Калифорния темпура, Филадельфия темпура",
                 desc_en="Tempura with chicken, California tempura, Philadelphia tempura",
                 price=1090, photo="set_tempura"),
            dict(name_ru="Сет Мега Хит", name_ky="Мега Хит сети", name_en="Mega Hit Set",
                 desc_ru="Сырный запеченный, Калифорния запеченная, Калифорния с крабом, Калифорния с кунжутом, Филадельфия, ролл с лососем, ролл с огурцом",
                 desc_ky="Бышырылган быштактуу, бышырылган Калифорния, краб м/н Калифорния, кунжут м/н Калифорния, Филадельфия, лосось ролл, бадыраң ролл",
                 desc_en="Baked cheese, baked California, California with crab, California with sesame, Philadelphia, salmon roll, cucumber roll",
                 price=1799, photo="set_mega_hit"),
            dict(name_ru="Сет Микс", name_ky="Микс сети", name_en="Mix Set",
                 desc_ru="Сырный запеченный, Филадельфия, Калифорния темпура",
                 desc_ky="Бышырылган быштактуу, Филадельфия, Калифорния темпура",
                 desc_en="Baked cheese roll, Philadelphia, California tempura",
                 price=999, photo="set_miks"),
            dict(name_ru="Сет Запеченный", name_ky="Бышырылган сет", name_en="Baked Set",
                 desc_ru="Калифорния запеченная, запеченная Чиккен Чиз, запеченный Крабик Хот",
                 desc_ky="Бышырылган Калифорния, бышырылган Чиккен Чиз, бышырылган Крабик Хот",
                 desc_en="Baked California, baked Chicken Cheese, baked Crab Hot",
                 price=799, photo="set_zapechenniy"),
            dict(name_ru="Сет Токио", name_ky="Токио сети", name_en="Tokyo Set",
                 desc_ru="Ролл Филадельфия, ролл Калифорния с крабом, ролл сырный запеченный, ролл с огурцом",
                 desc_ky="Филадельфия ролл, краб м/н Калифорния, бышырылган быштактуу ролл, бадыраң ролл",
                 desc_en="Philadelphia roll, California with crab, baked cheese roll, cucumber roll",
                 price=999, photo="set_tokio"),
            dict(name_ru="Сет Канадиан", name_ky="Канадиан сети", name_en="Canadian Set",
                 desc_ru="Филадельфия, Калифорния с лососем, Аляска, Канада",
                 desc_ky="Филадельфия, лосось м/н Калифорния, Аляска, Канада",
                 desc_en="Philadelphia, California with salmon, Alaska, Canada",
                 price=1350, photo="set_kanadian"),
        ],
    },
    # ── 17. Гарниры ───────────────────────────────────────────────────────
    {
        "name_ru": "Гарниры", "name_ky": "Гарнирлер", "name_en": "Side Dishes",
        "items": [
            dict(name_ru="Рис", name_ky="Күрүч", name_en="Rice",
                 desc_ru="Отварной рассыпчатый рис", desc_ky="Кайнатылган күрүч",
                 desc_en="Steamed fluffy rice", price=80, photo="garnir_ris"),
            dict(name_ru="Картофельное пюре", name_ky="Картошка пюреси", name_en="Mashed Potato",
                 desc_ru="Нежное картофельное пюре", desc_ky="Назик картошка пюреси",
                 desc_en="Creamy mashed potato", price=80, photo="garnir_pyure"),
            dict(name_ru="Гречка", name_ky="Гречка", name_en="Buckwheat",
                 desc_ru="Рассыпчатая гречневая каша", desc_ky="Бышырылган гречка",
                 desc_en="Cooked buckwheat", price=80, photo="garnir_grechka"),
            dict(name_ru="Котлета", name_ky="Котлет", name_en="Meat Patty",
                 desc_ru="Домашняя мясная котлета", desc_ky="Үй шартында жасалган эт котлети",
                 desc_en="Homemade meat patty", price=100, photo="garnir_kotleta"),
            dict(name_ru="Яйцо 1 шт", name_ky="Жумуртка 1 даана", name_en="Fried Egg 1 pc",
                 desc_ru="Жареное яйцо", desc_ky="Куурулган жумуртка",
                 desc_en="Fried egg", price=25, photo="garnir_yaytso"),
        ],
    },
    # ── 18. Дополнительные соусы ──────────────────────────────────────────
    {
        "name_ru": "Дополнительные соусы", "name_ky": "Кошумча соустар", "name_en": "Extra Sauces",
        "items": [
            dict(name_ru="Соус кетчуп", name_ky="Кетчуп соусу", name_en="Ketchup",
                 desc_ru="30 мл", desc_ky="30 мл", desc_en="30 ml", price=20, photo="sous_ketchup"),
            dict(name_ru="Соус сырный", name_ky="Быштак соусу", name_en="Cheese Sauce",
                 desc_ru="30 мл", desc_ky="30 мл", desc_en="30 ml", price=30, photo="sous_syrnyy"),
            dict(name_ru="Соус барбекю", name_ky="Барбекю соусу", name_en="BBQ Sauce",
                 desc_ru="30 мл", desc_ky="30 мл", desc_en="30 ml", price=30, photo="sous_barbekyu"),
            dict(name_ru="Соус чесночный", name_ky="Сарымсак соусу", name_en="Garlic Sauce",
                 desc_ru="30 мл", desc_ky="30 мл", desc_en="30 ml", price=30, photo="sous_chesnochnyy"),
            dict(name_ru="Соевый соус", name_ky="Соя соусу", name_en="Soy Sauce",
                 desc_ru="30 мл", desc_ky="30 мл", desc_en="30 ml", price=20, photo="sous_soevyy"),
            dict(name_ru="Соус Шрирачи (острый)", name_ky="Шрирача соусу (ачуу)", name_en="Sriracha Sauce (hot)",
                 desc_ru="30 мл", desc_ky="30 мл", desc_en="30 ml", price=50, photo="sous_shrirachi"),
            dict(name_ru="Васаби", name_ky="Васаби", name_en="Wasabi",
                 desc_ru="10 гр", desc_ky="10 гр", desc_en="10 g", price=20, photo="sous_vasabi"),
            dict(name_ru="Имбирь", name_ky="Имбирь", name_en="Pickled Ginger",
                 desc_ru="20 гр", desc_ky="20 гр", desc_en="20 g", price=30, photo="imbir"),
            dict(name_ru="Халапеньо", name_ky="Халапеньо", name_en="Jalapeño",
                 desc_ru="25 гр", desc_ky="25 гр", desc_en="25 g", price=40, photo="halapeno"),
            dict(name_ru="Сыр Чеддер", name_ky="Чеддер быштагы", name_en="Cheddar Cheese",
                 desc_ru="1 ломтик", desc_ky="1 кесим", desc_en="1 slice", price=50, photo="syr_cheddar"),
        ],
    },
    # ── 19. Десерты ───────────────────────────────────────────────────────
    {
        "name_ru": "Десерты", "name_ky": "Таттуулар", "name_en": "Desserts",
        "items": [
            dict(name_ru="Творожный", name_ky="Быштактуу торт", name_en="Cheesecake Slice",
                 desc_ru="Нежный творожный торт", desc_ky="Назик быштактуу торт",
                 desc_en="Delicate curd cake", price=130, photo="desert_tvorozhniy"),
            dict(name_ru="Красный бархат", name_ky="Кызыл баркыт", name_en="Red Velvet",
                 desc_ru="Классический торт «Красный бархат» со сливочным кремом",
                 desc_ky="Каймак крем м/н классикалык «Кызыл баркыт» торту",
                 desc_en="Classic red velvet cake with cream cheese frosting",
                 price=150, photo="desert_krasniy_barhat"),
            dict(name_ru="Медовик", name_ky="Балдуу торт", name_en="Honey Cake (Medovik)",
                 desc_ru="Медовые коржи со сметанным кремом",
                 desc_ky="Каймак крем м/н бал катмарлары",
                 desc_en="Honey layers with sour cream filling", price=130, photo="desert_medovik"),
            dict(name_ru="Сникерс", name_ky="Сникерс", name_en="Snickers Cake",
                 desc_ru="Шоколадный торт с арахисом и карамелью",
                 desc_ky="Жержаңгак жана карамель м/н шоколад торту",
                 desc_en="Chocolate cake with peanuts and caramel", price=170, photo="desert_snikers"),
            dict(name_ru="Черный лес", name_ky="Кара токой", name_en="Black Forest",
                 desc_ru="Шоколадный торт с вишней и сливками",
                 desc_ky="Чие жана каймак м/н шоколад торту",
                 desc_en="Chocolate cake with cherry and cream", price=160, photo="desert_cherniy_les"),
        ],
    },
    # ── 20. Блюда на заказ ────────────────────────────────────────────────
    {
        "name_ru": "Блюда на заказ", "name_ky": "Буйрутма боюнча тамактар", "name_en": "Order in Advance",
        "items": [
            dict(name_ru="Хлеб", name_ky="Нан", name_en="Bread",
                 desc_ru="Свежая лепёшка", desc_ky="Жаңы бышкан нан",
                 desc_en="Fresh flatbread", price=35, photo="hleb"),
            dict(name_ru="Боорсок 250 гр", name_ky="Боорсок 250 гр", name_en="Boorsok 250 g",
                 desc_ru="Традиционные жареные боорсоки, 250 гр",
                 desc_ky="Салттуу куурулган боорсок, 250 гр",
                 desc_en="Traditional fried dough boorsok, 250 g", price=120, photo="boorsok"),
            dict(name_ru="Ташкентский плов 1 кг", name_ky="Ташкент палоосу 1 кг", name_en="Tashkent Plov 1 kg",
                 desc_ru="Плов на компанию, 1 кг. Готовится под заказ",
                 desc_ky="Чоң топко палоо, 1 кг. Буйрутма боюнча даярдалат",
                 desc_en="Plov for sharing, 1 kg. Made to order", price=2200, photo="plov_na_zakaz"),
            dict(name_ru="Узгенский плов 1 кг", name_ky="Өзгөн палоосу 1 кг", name_en="Uzgen Plov 1 kg",
                 desc_ru="Плов из узгенского риса, 1 кг. В подарок Salam Premium Cola 1,5 л",
                 desc_ky="Өзгөн күрүчүнөн палоо, 1 кг. Белекке Salam Premium Cola 1,5 л",
                 desc_en="Plov made with Uzgen rice, 1 kg. Free Salam Premium Cola 1.5 L",
                 price=2500, photo="plov_na_zakaz"),
        ],
    },
    # ── 21. Горячие напитки ───────────────────────────────────────────────
    {
        "name_ru": "Горячие напитки", "name_ky": "Ысык суусундуктар", "name_en": "Hot Drinks",
        "items": [
            dict(name_ru="Кофе черный растворимый", name_ky="Эрүүчү кара кофе", name_en="Black Instant Coffee",
                 price=30, photo="kofe"),
            dict(name_ru="Кофе 3в1", name_ky="Кофе 3в1", name_en="Coffee 3-in-1",
                 price=30, photo="kofe"),
            dict(name_ru="Чай черный", name_ky="Кара чай", name_en="Black Tea",
                 price=20, photo="chay_cherniy"),
            dict(name_ru="Чай зелёный", name_ky="Жашыл чай", name_en="Green Tea",
                 price=20, photo="chay_zelenyy"),
            dict(name_ru="Чай Микс", name_ky="Микс чай", name_en="Mixed Fruit Tea",
                 desc_ru="Фруктовый чай в чайнике", desc_ky="Чайнекте жемиш чайы",
                 desc_en="Fruit tea served in a teapot", price=30, photo="chay_miks"),
            dict(name_ru="Нават 100 гр", name_ky="Набат 100 гр", name_en="Nabat Sugar 100 g",
                 desc_ru="Кристаллический сахар к чаю, 100 гр",
                 desc_ky="Чайга кристалл шекер, 100 гр",
                 desc_en="Crystal sugar for tea, 100 g", price=50, photo="chay_cherniy"),
            dict(name_ru="Лимон", name_ky="Лимон", name_en="Lemon",
                 desc_ru="Свежий лимон к чаю", desc_ky="Чайга жаңы лимон",
                 desc_en="Fresh lemon for tea", price=50, photo="limon"),
        ],
    },
    # ── 22. Напитки ───────────────────────────────────────────────────────
    {
        "name_ru": "Напитки", "name_ky": "Суусундуктар", "name_en": "Cold Drinks",
        "items": [
            dict(name_ru="Salam Premium Cola 0,5 л", name_ky="Salam Premium Cola 0,5 л", name_en="Salam Premium Cola 0.5 L",
                 price=70, photo="salam_cola"),
            dict(name_ru="Salam Premium Cola 1 л", name_ky="Salam Premium Cola 1 л", name_en="Salam Premium Cola 1 L",
                 price=110, photo="salam_cola"),
            dict(name_ru="Salam Premium Cola 1,5 л", name_ky="Salam Premium Cola 1,5 л", name_en="Salam Premium Cola 1.5 L",
                 price=160, photo="salam_cola"),
            dict(name_ru="Salam Premium Cola 2 л", name_ky="Salam Premium Cola 2 л", name_en="Salam Premium Cola 2 L",
                 price=190, photo="salam_cola"),
            dict(name_ru="ASU 0,5 л", name_ky="ASU 0,5 л", name_en="ASU Water 0.5 L",
                 desc_ru="Питьевая вода", desc_ky="Ичүүчү суу", desc_en="Drinking water",
                 price=40, photo="voda"),
            dict(name_ru="ASU 1 л", name_ky="ASU 1 л", name_en="ASU Water 1 L",
                 desc_ru="Питьевая вода", desc_ky="Ичүүчү суу", desc_en="Drinking water",
                 price=60, photo="voda"),
            dict(name_ru="ASU со вкусом 0,5 л", name_ky="ASU даамдуу 0,5 л", name_en="ASU Flavoured 0.5 L",
                 desc_ru="Вода со вкусом", desc_ky="Даамдуу суу", desc_en="Flavoured water",
                 price=60, photo="voda"),
            dict(name_ru="ASU со вкусом 1 л", name_ky="ASU даамдуу 1 л", name_en="ASU Flavoured 1 L",
                 desc_ru="Вода со вкусом", desc_ky="Даамдуу суу", desc_en="Flavoured water",
                 price=80, photo="voda"),
            dict(name_ru="Сок Gracio 1 л", name_ky="Gracio ширеси 1 л", name_en="Gracio Juice 1 L",
                 price=160, photo="sok"),
            dict(name_ru="Сок DaDa 0,5 л", name_ky="DaDa ширеси 0,5 л", name_en="DaDa Juice 0.5 L",
                 price=80, photo="sok"),
            dict(name_ru="Сок DaDa 1 л", name_ky="DaDa ширеси 1 л", name_en="DaDa Juice 1 L",
                 price=130, photo="sok"),
            dict(name_ru="Чай Piala 0,5 л", name_ky="Piala чайы 0,5 л", name_en="Piala Iced Tea 0.5 L",
                 price=60, photo="chay_butylka"),
            dict(name_ru="Чай Piala 1 л", name_ky="Piala чайы 1 л", name_en="Piala Iced Tea 1 L",
                 price=100, photo="chay_butylka"),
            dict(name_ru="AVA ассорти 1 л", name_ky="AVA ассорти 1 л", name_en="AVA Lemonade Assorted 1 L",
                 desc_ru="Лимонад в ассортименте", desc_ky="Ар түрдүү лимонад",
                 desc_en="Assorted lemonade", price=110, photo="ava_lemonade"),
            dict(name_ru="Lavina энергетик 0,45 л", name_ky="Lavina энергетик 0,45 л", name_en="Lavina Energy Drink 0.45 L",
                 desc_ru="Энергетический напиток, банка",
                 desc_ky="Энергетикалык суусундук, банка",
                 desc_en="Energy drink, can", price=100, photo="napitok_energetik"),
            dict(name_ru="Сок Dada детский 0,2 л", name_ky="Dada балдар ширеси 0,2 л", name_en="Dada Kids Juice 0.2 L",
                 price=40, photo="sok"),
            dict(name_ru="Сок Нектар детский 0,2 л", name_ky="Нектар балдар ширеси 0,2 л", name_en="Nektar Kids Juice 0.2 L",
                 price=40, photo="sok"),
        ],
    },
]
