# -*- coding: utf-8 -*-
"""
Полные данные меню ресторана DUA — 3 языка (RU/KY/EN), цены, фото-слаги.
Составлено по меню-PDF (01.pdf), сентябрь 2026.

Формат:
CATEGORIES = [
    {
        "name_ru": ..., "name_ky": ..., "name_en": ...,
        "items": [
            {
                "name_ru": ..., "name_ky": ..., "name_en": ...,
                "desc_ru": ..., "desc_ky": ..., "desc_en": ...,
                "price": Decimal-совместимое число,
                "photo": "slug"  # имя файла в crops/<slug>.jpg, либо None
            },
            ...
        ],
    },
    ...
]
"""

CATEGORIES = [
    # ── 1. Завтраки (до 12:00) ──────────────────────────────────────────────
    {
        "name_ru": "Завтраки", "name_ky": "Таңкы тамактар", "name_en": "Breakfast",
        "items": [
            dict(name_ru="Яичница с колбасой", name_ky="Куурулган жумуртка колбаса м/н",
                 name_en="Fried Eggs with Sausage",
                 desc_ru="Яйца, лепёшка, колбаса", desc_ky="Жумуртка, нан, колбаса",
                 desc_en="Eggs, flatbread, sausage",
                 price=250, photo="yaichnitsa_kolbasa"),
            dict(name_ru="Яичница", name_ky="Куурулган жумуртка", name_en="Fried Eggs",
                 desc_ru="Яйца, лепёшка", desc_ky="Жумуртка, нан", desc_en="Eggs, flatbread",
                 price=200, photo="yaichnitsa"),
            dict(name_ru="Турецкий завтрак", name_ky="Түрк таңкы тамак", name_en="Turkish Breakfast",
                 desc_ru="Яйца, лепёшка, оливки, грецкий орех, мёд, масло, джем, борек, брынза, моцарелла, помидор, огурец",
                 desc_ky="Жумуртка, нан, зайтун, жаңгак, бал, май, кыям, борек, брынза, моцарелла, кызанак, бадыраң",
                 desc_en="Eggs, flatbread, olives, walnuts, honey, butter, jam, borek, feta, mozzarella, tomato, cucumber",
                 price=400, photo="turk_zavtrak"),
            dict(name_ru="Омлет с сыром", name_ky="Быштак м/н омлет", name_en="Cheese Omelette",
                 desc_ru="Яйца, молоко, сыр, помидор, огурец", desc_ky="Жумуртка, сүт, быштак, помидор, бадыраң",
                 desc_en="Eggs, milk, cheese, tomato, cucumber",
                 price=230, photo="omlet_syrom"),
            dict(name_ru="Менемен с сыром", name_ky="Быштак м/н менемен", name_en="Menemen with Cheese",
                 desc_ru="Яйца, помидор, болгарский перец, лук, сыр",
                 desc_ky="Жумуртка, кызанак, болгар калемпири, пияз, быштак",
                 desc_en="Eggs, tomato, bell pepper, onion, cheese",
                 price=250, photo="menemen_syrom"),
            dict(name_ru="Сигара борек", name_ky="Сигара борек", name_en="Cigar Böreği (Cheese Rolls)",
                 desc_ru="Лаваш, сыр", desc_ky="Лаваш, быштак",
                 desc_en="Crispy pastry rolls filled with cheese",
                 price=230, photo="sigara_borek"),
        ],
    },
    # ── 2. Салаты ────────────────────────────────────────────────────────────
    {
        "name_ru": "Салаты", "name_ky": "Салаттар", "name_en": "Salads",
        "items": [
            dict(name_ru="Фирменный салат ДУА", name_ky="Өзгөчө салат ДУА", name_en="Signature DUA Salad",
                 desc_ru="Курица, пекинская капуста, листья салата, хрустящий картофель, майонез, бальзамический соус",
                 desc_ky="Тоок эти, кытай салаты, жалбырак, картошка, майонез, бальзам соусу",
                 desc_en="Chicken, napa cabbage, lettuce, crispy potato, mayonnaise, balsamic glaze",
                 price=390, photo="salat_dua"),
            dict(name_ru="Баклажаны от шефа", name_ky="Шефтен баклажан", name_en="Chef's Eggplant",
                 desc_ru="Баклажан, кисло-сладкий соус, сыр, помидор, кунжут",
                 desc_ky="Баклажан, ачуу-ширин соус, быштак, кызанак, кунжут",
                 desc_en="Eggplant, sweet-and-sour sauce, cheese, tomato, sesame",
                 price=380, photo="baklajan_shefa"),
            dict(name_ru="Греческий салат", name_ky="Грек салаты", name_en="Greek Salad",
                 desc_ru="Огурец, помидор, болгарский перец, сыр фета",
                 desc_ky="Бадыраң, кызанак, болгар калемпири, фетакса быштагы",
                 desc_en="Cucumber, tomato, bell pepper, feta cheese",
                 price=370, photo="grecheskiy_salat"),
            dict(name_ru="Салат Цезарь с курицей", name_ky="Тоок этинен цезарь салаты", name_en="Chicken Caesar Salad",
                 desc_ru="Курица, пекинская капуста, листья салата, соус цезарь, пармезан, гренки, помидор",
                 desc_ky="Тоок эти, кытай капуста, салат жалбырагы, цезар соусу, пармизан быштагы, кытырак нан, кызанак",
                 desc_en="Chicken, napa cabbage, lettuce, caesar dressing, parmesan, croutons, tomato",
                 price=380, photo="salat_tsezar"),
            dict(name_ru="Тёплый салат с грибами", name_ky="Козу карын м/н ыссык салат", name_en="Warm Mushroom Salad",
                 desc_ru="Говядина, древесные грибы, болгарский перец, брокколи, соевый соус, перец",
                 desc_ky="Мал эти, козу карын, болгар калемпири, брокколи, соя соусу, бибер",
                 desc_en="Beef, wood-ear mushrooms, bell pepper, broccoli, soy sauce, pepper",
                 price=370, photo="salat_gribami"),
        ],
    },
    # ── 3. Супы ──────────────────────────────────────────────────────────────
    {
        "name_ru": "Супы", "name_ky": "Суюк тамактар", "name_en": "Soups",
        "items": [
            dict(name_ru="Чечевичный суп", name_ky="Кызыл жасмык", name_en="Lentil Soup",
                 desc_ru="Красная чечевица, специи, гренки", desc_ky="Кызыл жасмык, даам берүүчү заттар",
                 desc_en="Red lentils, spices, croutons",
                 price=250, photo="sup_chechevichniy"),
            dict(name_ru="Суп с фрикадельками", name_ky="Фрикаделькилер", name_en="Meatball Soup",
                 desc_ru="Говяжьи фрикадельки, овощной бульон", desc_ky="Мал этинен фрикаделька, кою шорпо",
                 desc_en="Beef meatballs in vegetable broth",
                 price=300, photo="sup_frikadelki"),
            dict(name_ru="Куриный суп", name_ky="Тоок эти", name_en="Chicken Soup",
                 desc_ru="Куриный бульон, овощи, зелень", desc_ky="Тоок шорпо, көк өнүм",
                 desc_en="Chicken broth with vegetables and herbs",
                 price=250, photo="sup_kurinyi"),
            dict(name_ru="Домашние пельмени", name_ky="Колго туюлгөн чучвара", name_en="Homemade Dumpling Soup",
                 desc_ru="Пельмени ручной лепки в бульоне, сметана", desc_ky="Колго туюлгөн чучвара, каймак",
                 desc_en="Hand-made dumplings in broth, served with sour cream",
                 price=300, photo="sup_pelmeni"),
        ],
    },
    # ── 4. Горячие блюда ─────────────────────────────────────────────────────
    {
        "name_ru": "Горячие блюда", "name_ky": "Кою тамактар", "name_en": "Main Dishes",
        "items": [
            dict(name_ru="Мясное сотэ", name_ky="Эт соте", name_en="Beef Sauté",
                 desc_ru="Говядина, древесные грибы, лук, болгарский перец, помидор",
                 desc_ky="Мал эти, козу карын, пияз, болгар калемпири, кызанак",
                 desc_en="Beef, wood-ear mushrooms, onion, bell pepper, tomato",
                 price=550, photo="et_sote"),
            dict(name_ru="Куриное сотэ", name_ky="Тоок соте", name_en="Chicken Sauté",
                 desc_ru="Курица, древесные грибы, лук, болгарский перец, помидор",
                 desc_ky="Тоок эти, козу карын, пияз, болгар калемпири, кызанак",
                 desc_en="Chicken, wood-ear mushrooms, onion, bell pepper, tomato",
                 price=520, photo="took_sote"),
            dict(name_ru="Фрикасе из курицы в сливочном соусе", name_ky="Тоок этинен фрикасе",
                 name_en="Chicken Fricassee in Cream Sauce",
                 desc_ru="Курица, древесные грибы, сливочный соус, лук, подаётся с рисом",
                 desc_ky="Тоок эти, козу карын, каймактуу соусу, пияз",
                 desc_en="Chicken, wood-ear mushrooms, cream sauce, onion, served with rice",
                 price=520, photo="frikase_kuritsa"),
            dict(name_ru="Фрикасе из говядины в сливочном соусе", name_ky="Мал этинен фрикассе",
                 name_en="Beef Fricassee in Cream Sauce",
                 desc_ru="Говядина, древесные грибы, сливочный соус, лук, подаётся с рисом",
                 desc_ky="Мал эти, козу карын, каймактуу соусу, пияз",
                 desc_en="Beef, wood-ear mushrooms, cream sauce, onion, served with rice",
                 price=550, photo="frikase_govyadina"),
        ],
    },
    # ── 5. Блюда из донера ───────────────────────────────────────────────────
    {
        "name_ru": "Блюда из донера", "name_ky": "Донер этинен чыккан тамактар", "name_en": "Döner Dishes",
        "items": [
            dict(name_ru="Искендер", name_ky="Искендер", name_en="Iskender Kebab",
                 desc_ru="Мясо донер, хрустящая лепёшка, топлёное масло, сузьма, соус искендер",
                 desc_ky="Донер эти, кытырак нан, сары май, сүзмө, искендер соусу",
                 desc_en="Döner meat, crispy flatbread, melted butter, strained yogurt, iskender sauce",
                 price=720, photo="iskender"),
            dict(name_ru="Дуа Донер", name_ky="Дуа донер", name_en="DUA Döner",
                 desc_ru="Мясо донер, рис, лаваш, соус адана", desc_ky="Донер эти, күрүч, лаваш, адана соусу",
                 desc_en="Döner meat, rice, lavash, adana sauce",
                 price=680, photo="dua_doner"),
            dict(name_ru="Нан бургер", name_ky="Нан бургер", name_en="Nan Döner Burger",
                 desc_ru="Мясо донер, помидор, соус адана, красный лук, в лепёшке нан",
                 desc_ky="Донер эти, кызанак, адана соус, кызыл пияз",
                 desc_en="Döner meat, tomato, adana sauce, red onion, in nan flatbread",
                 price=300, photo="nan_burger"),
            dict(name_ru="Донер лаваш", name_ky="Донер лаваш", name_en="Döner Lavash Wrap",
                 desc_ru="Мясо донер, красный лук, помидор, огурец, в лаваше",
                 desc_ky="Донер эти, кызыл пияз, кызанак, бадыраң",
                 desc_en="Döner meat, red onion, tomato, cucumber, wrapped in lavash",
                 price=350, photo="doner_lavash"),
        ],
    },
    # ── 6. Блюда на мангале ──────────────────────────────────────────────────
    {
        "name_ru": "Блюда на мангале", "name_ky": "Мангалда какталып бышкан тамактар", "name_en": "Grilled Dishes",
        "items": [
            dict(name_ru="Али Назик кофте", name_ky="Кофте Али Назик соусу м/н", name_en="Ali Nazik Köfte",
                 desc_ru="Кофте, баклажановый соус, лепёшка, перец, салат, рис, соус искендер",
                 desc_ky="Кофте, баклажан соус, нан, бибер, салат, күрүч, искендер соусу",
                 desc_en="Köfte, eggplant sauce, flatbread, pepper, salad, rice, iskender sauce",
                 price=550, photo="kofte_ali_nazik"),
            dict(name_ru="Урфа кебаб", name_ky="Урфа", name_en="Urfa Kebab",
                 desc_ru="Говядина, курдючное сало, рис, салат, лепёшка, соус адана, перец",
                 desc_ky="Мал эти, куйрук, күрүч, салат, нан, адана соус, бибер",
                 desc_en="Beef, tail fat, rice, salad, flatbread, adana sauce, pepper",
                 price=520, photo="urfa"),
            dict(name_ru="Острая Адана", name_ky="Ачуу адана", name_en="Spicy Adana Kebab",
                 desc_ru="Говядина, курдючное сало, рис, салат, лепёшка, острый соус адана, перец",
                 desc_ky="Мал эти, куйрук, күрүч, салат, нан, ачуу адана соус, бибер",
                 desc_en="Beef, tail fat, rice, salad, flatbread, spicy adana sauce, pepper",
                 price=520, photo="achuu_adana"),
            dict(name_ru="Ассорти кебаб", name_ky="Ассорти кебап", name_en="Assorted Kebab Platter",
                 desc_ru="Говядина, куриные крылышки, лепёшка, салат, рис, перец, соус адана",
                 desc_ky="Мал эти, тоок канаты, нан, салат, күрүч, бибер, адана соус",
                 desc_en="Beef, chicken wings, flatbread, salad, rice, pepper, adana sauce",
                 price=700, photo="assorti_kebap"),
            dict(name_ru="Шеф ассорти", name_ky="Шеф ассорти", name_en="Chef's Assorted Grill",
                 desc_ru="Куриный стейк, кофте на углях, лаваш, салат, рис, перец, соус адана",
                 desc_ky="Тоок стейк, ызгара кофте, лаваш, салат, күрүч, бибер, адана соус",
                 desc_en="Chicken steak, grilled köfte, lavash, salad, rice, pepper, adana sauce",
                 price=680, photo="shef_assorti"),
            dict(name_ru="Дуа ассорти", name_ky="Дуа ассорти", name_en="DUA Assorted Grill",
                 desc_ru="Куриный стейк, говяжий стейк, зелёный баклажан, помидор, соус адана, лаваш, лепёшка, рис",
                 desc_ky="Тоок стейк, мал этинен стейк, жашыл баклажан, кызанак, адана соус, лаваш, нан, күрүч",
                 desc_en="Chicken steak, beef steak, grilled green eggplant, tomato, adana sauce, lavash, flatbread, rice",
                 price=700, photo="dua_assorti"),
            dict(name_ru="Кофте на углях", name_ky="Ызгара кофте", name_en="Grilled Köfte",
                 desc_ru="Кофте на углях, лепёшка, перец, салат, рис, соус адана",
                 desc_ky="Ызгара кофте, нан, бибер, салат, күрүч, адана соус",
                 desc_en="Charcoal-grilled köfte, flatbread, pepper, salad, rice, adana sauce",
                 price=520, photo="yzgara_kofte"),
            dict(name_ru="Куриный стейк", name_ky="Тоок этинен стейк", name_en="Chicken Steak",
                 desc_ru="Курица, белый баклажан, перец, лук, помидор, рис, лепёшка",
                 desc_ky="Тоок эти, ак баклажан, бибер, пияз, кызанак, күрүч, нан",
                 desc_en="Chicken, white eggplant, pepper, onion, tomato, rice, flatbread",
                 price=650, photo="took_steyk"),
            dict(name_ru="Крылышки на мангале", name_ky="Чытыр канат", name_en="Grilled Chicken Wings",
                 desc_ru="Куриные крылышки, лепёшка, салат, рис, соус адана",
                 desc_ky="Тоок канат, нан, салат, күрүч, адана соус",
                 desc_en="Chicken wings, flatbread, salad, rice, adana sauce",
                 price=550, photo="chytyr_kanat"),
            dict(name_ru="Острые крылышки", name_ky="Ачуу канат", name_en="Spicy Chicken Wings",
                 desc_ru="Куриные крылышки, лаваш, салат, рис, соус, картофель фри",
                 desc_ky="Тоок канат, лаваш, салат, күрүч, соус, картошка фри",
                 desc_en="Chicken wings, lavash, salad, rice, sauce, french fries",
                 price=550, photo="achuu_kanat"),
            dict(name_ru="Чоп шиш", name_ky="Чоп шиш", name_en="Chop Shish Skewer",
                 desc_ru="Говядина, курдючное сало, рис, салат, лепёшка, соус адана, перец",
                 desc_ky="Мал эти, куйрук, күрүч, салат, нан, адана соус, бибер",
                 desc_en="Beef skewer with tail fat, rice, salad, flatbread, adana sauce, pepper",
                 price=580, photo="chop_shish"),
            dict(name_ru="Кофте с сыром", name_ky="Ызгара м/н быштак", name_en="Grilled Köfte with Cheese",
                 desc_ru="Кофте на углях, сыр, рис, салат, лепёшка, соус адана, перец",
                 desc_ky="Ызгара кофте, быштак, күрүч, салат, нан, адана соус, бибер",
                 desc_en="Charcoal-grilled köfte with cheese, rice, salad, flatbread, adana sauce, pepper",
                 price=580, photo="kofte_byshtak"),
            dict(name_ru="Бейти сарма", name_ky="Бейти сарма", name_en="Beyti Sarma",
                 desc_ru="Кебаб, завёрнутый в лаваш, говядина, рис, салат, 2 вида соуса",
                 desc_ky="Камырга оролгон кебап, мал эти, күрүч, салат, 2 түр соус",
                 desc_en="Kebab wrapped in flatbread, beef, rice, salad, two sauces",
                 price=590, photo="beyti_sarma"),
            dict(name_ru="Тавук сарма", name_ky="Тавук сарма", name_en="Tavuk Sarma",
                 desc_ru="Куриное мясо, завёрнутое в лаваш и запечённое, рис, салат, 2 вида соуса",
                 desc_ky="Камырга оролуп какталып бышырылган тоок эти, күрүч, салат, 2 түр соус",
                 desc_en="Chicken wrapped in flatbread and oven-baked, rice, salad, two sauces",
                 price=560, photo="tavuk_sarma"),
            dict(name_ru="Дуа сет", name_ky="Дуа сет", name_en="DUA Sharing Set",
                 desc_ru="Большое сет-блюдо на компанию: кебаб в лаваше, куриные крылышки, куриный стейк, острый кебаб из говядины, салат, зелёный баклажан, помидор, ассорти соус, рис",
                 desc_ky="Лавашка оролгон кебаб, тоок канат, тоок стейк, ачуу мал этинен кебаб, салат, жашыл баклажан, кызанак, ассорти соус, күрүч",
                 desc_en="Large sharing platter: kebab in flatbread, chicken wings, chicken steak, spicy beef kebab, salad, grilled green eggplant, tomato, assorted sauces, rice",
                 price=2000, photo="dua_set"),
        ],
    },
    # ── 7. Пицца ─────────────────────────────────────────────────────────────
    {
        "name_ru": "Пицца", "name_ky": "Ачыткыдан жасалган пиццалар", "name_en": "Pizza",
        "items": [
            dict(name_ru="4 сыра", name_ky="4 быштак", name_en="Four Cheese Pizza",
                 desc_ru="Моцарелла, фета, сулугуни, плавленый сыр",
                 desc_ky="Моцарелла быштагы, фета быштагы, сулугуни быштагы, ээритилген быштак",
                 desc_en="Mozzarella, feta, suluguni, melted cheese",
                 price=650, photo="pizza_4syra"),
            dict(name_ru="Овощная пицца", name_ky="Жер жемиштер м/н пицца", name_en="Vegetable Pizza",
                 desc_ru="Моцарелла, красный лук, болгарский перец, древесные грибы, оливки",
                 desc_ky="Моцарелла быштагы, кызыл пияз, болгар калемпири, козу карын, зайтун",
                 desc_en="Mozzarella, red onion, bell pepper, wood-ear mushrooms, olives",
                 price=550, photo="pizza_ovoshnaya"),
            dict(name_ru="Мексиканская острая", name_ky="Мексика пиццасы", name_en="Spicy Mexican Pizza",
                 desc_ru="Курица, моцарелла, кукуруза, халапеньо, болгарский перец",
                 desc_ky="Тоок эти, моцарелла быштагы, жүгөрү, халапеньо, болгар калемпири",
                 desc_en="Chicken, mozzarella, corn, jalapeño, bell pepper",
                 price=620, photo="pizza_mexico"),
            dict(name_ru="Пицца Цезарь", name_ky="Цезарь пиццасы", name_en="Caesar Pizza",
                 desc_ru="Соус цезарь, курица, капуста, помидор, пармезан, соус песто",
                 desc_ky="Цезар соусу, тоок эти, капуста, кызанак, пармезан быштагы, песто соусу",
                 desc_en="Caesar sauce, chicken, cabbage, tomato, parmesan, pesto",
                 price=620, photo="pizza_tsezar"),
            dict(name_ru="Пицца ДУА", name_ky="Пицца Дуа", name_en="DUA Pizza",
                 desc_ru="Соус песто, моцарелла, курица, руккола, сыр, грецкий орех, помидор",
                 desc_ky="Песто соусу, моцарелла быштагы, тоок эти, руккола, быштак, жаңгак, кызанак",
                 desc_en="Pesto sauce, mozzarella, chicken, arugula, cheese, walnuts, tomato",
                 price=680, photo="pizza_dua"),
            dict(name_ru="Пепперони", name_ky="Пепперони", name_en="Pepperoni Pizza",
                 desc_ru="Моцарелла, пепперони", desc_ky="Моцарелла быштагы, пепперони",
                 desc_en="Mozzarella, pepperoni",
                 price=620, photo="pizza_pepperoni"),
            dict(name_ru="Сырный цыплёнок", name_ky="Тоок эти м/н быштак", name_en="Cheesy Chicken Pizza",
                 desc_ru="Соус бешамель, курица, моцарелла", desc_ky="Бешамел соусу, тоок эти, моцарелла быштагы",
                 desc_en="Béchamel sauce, chicken, mozzarella",
                 price=620, photo="pizza_sirniy_tsyplenok"),
            dict(name_ru="Мясная пицца", name_ky="Эттүү пицца", name_en="Meat Lovers Pizza",
                 desc_ru="Томатный соус, говядина, курица, колбаса",
                 desc_ky="Кызанак соусу, мал эти, тоок эти, колбаса",
                 desc_en="Tomato sauce, beef, chicken, sausage",
                 price=680, photo="pizza_myasnaya"),
            dict(name_ru="Маргарита", name_ky="Маргарита", name_en="Margherita Pizza",
                 desc_ru="Томатный соус, моцарелла",
                 desc_ky="Кызанак соусу, моцарелла быштагы",
                 desc_en="Tomato sauce, mozzarella",
                 price=520, photo="pizza_margarita"),
            dict(name_ru="Кофте пицца", name_ky="Кофте пицца", name_en="Köfte Pizza",
                 desc_ru="Томатный соус, рубленое мясо, моцарелла",
                 desc_ky="Кызанак соусу, мал эти, моцарелла быштагы",
                 desc_en="Tomato sauce, minced meat, mozzarella",
                 price=580, photo="pizza_kofte"),
            dict(name_ru="Мега Пепперони", name_ky="Мега пепперони", name_en="Mega Pepperoni Pizza",
                 desc_ru="Моцарелла, двойная порция пепперони",
                 desc_ky="Моцарелла быштагы, пепперони",
                 desc_en="Mozzarella, extra pepperoni",
                 price=660, photo="pizza_pepperoni_mega"),
        ],
    },
    # ── 8. Лепёшки и лахмажун ────────────────────────────────────────────────
    {
        "name_ru": "Лепёшки и лахмажун", "name_ky": "Лахмажун жана нандар", "name_en": "Flatbreads & Lahmajun",
        "items": [
            dict(name_ru="Лахмажун", name_ky="Лахмажун", name_en="Lahmajun",
                 desc_ru="Тонкая лепёшка со специями и мясным фаршем, зелень, подаётся с овощами и лимоном",
                 desc_ky="Ичи эт менен даярдалган ичке нан, жашылчалар жана лимон менен берилет",
                 desc_en="Thin flatbread topped with spiced minced meat and herbs, served with vegetables and lemon",
                 price=300, photo="lahmajun"),
            dict(name_ru="Турецкий лаваш", name_ky="Түрк лавашы", name_en="Turkish Lavash Bread",
                 desc_ru="Печёный лаваш с кунжутом", desc_ky="Кунжут менен бышырылган түрк лавашы",
                 desc_en="Sesame-topped baked lavash bread",
                 price=200, photo="turk_lavash"),
            dict(name_ru="Хайдари", name_ky="Хайдари", name_en="Haydari (Yogurt & Herb Dip)",
                 desc_ru="Сузьма (процеженный йогурт), зелень, специи", desc_ky="Сүзмө, көк өнүм, даам берүүчү заттар",
                 desc_en="Strained yogurt dip with herbs and spices",
                 price=200, photo="haydari"),
            dict(name_ru="Нан лепёшка", name_ky="Нан лепешка", name_en="Nan Flatbread",
                 desc_ru="Свежая лепёшка с кунжутом", desc_ky="Кунжут менен таза бышырылган нан",
                 desc_en="Fresh sesame-topped flatbread",
                 price=50, photo="nan_lepeshka"),
        ],
    },
    # ── 9. Бургеры и шаурма ──────────────────────────────────────────────────
    {
        "name_ru": "Бургеры и шаурма", "name_ky": "Бургер жана шаурма", "name_en": "Burgers & Shawarma",
        "items": [
            dict(name_ru="Бургер с курицей", name_ky="Тоок этинен бургер", name_en="Chicken Burger",
                 desc_ru="Куриная котлета, овощи, соус. По желанию — с сыром (+50 сом)",
                 desc_ky="Тоок эти, жашылчалар, соус. Каалосуна жараша быштагы менен (+50 сом)",
                 desc_en="Chicken patty, vegetables, sauce. Add cheese for +50 som",
                 price=260, photo="burger_kuritsa"),
            dict(name_ru="Бургер с говядиной", name_ky="Мал этинен бургер", name_en="Beef Burger",
                 desc_ru="Говяжья котлета, овощи, соус. По желанию — с сыром (+50 сом)",
                 desc_ky="Мал эти, жашылчалар, соус. Каалосуна жараша быштагы менен (+50 сом)",
                 desc_en="Beef patty, vegetables, sauce. Add cheese for +50 som",
                 price=280, photo="burger_govyadina"),
            dict(name_ru="Шаурма с курицей", name_ky="Тоок этинен шаурма", name_en="Chicken Shawarma",
                 desc_ru="Курица гриль, овощи, соус, в лаваше. По желанию — с сыром (+50 сом)",
                 desc_ky="Тоок эти, жашылчалар, соус, лавашта. Каалосуна жараша быштагы менен (+50 сом)",
                 desc_en="Grilled chicken, vegetables, sauce, wrapped in lavash. Add cheese for +50 som",
                 price=280, photo="shaurma_kuritsa"),
            dict(name_ru="Шаурма с говядиной", name_ky="Мал этинен шаурма", name_en="Beef Shawarma",
                 desc_ru="Говядина гриль, овощи, соус, в лаваше. По желанию — с сыром (+50 сом)",
                 desc_ky="Мал эти, жашылчалар, соус, лавашта. Каалосуна жараша быштагы менен (+50 сом)",
                 desc_en="Grilled beef, vegetables, sauce, wrapped in lavash. Add cheese for +50 som",
                 price=300, photo="shaurma_govyadina"),
        ],
    },
    # ── 10. Гарниры ──────────────────────────────────────────────────────────
    {
        "name_ru": "Гарниры", "name_ky": "Гарнирлер", "name_en": "Side Dishes",
        "items": [
            dict(name_ru="Рис", name_ky="Күрүч", name_en="Rice",
                 desc_ru="Рассыпчатый рис с обжаренным луком", desc_ky="Күйгүзүлгөн пияз менен күрүч",
                 desc_en="Fluffy rice with fried onion",
                 price=70, photo="ris_garnir"),
            dict(name_ru="Картофель фри", name_ky="Картошка фри", name_en="French Fries",
                 desc_ru="Подаётся с кетчупом", desc_ky="Кетчуп менен берилет", desc_en="Served with ketchup",
                 price=200, photo="kartoshka_fri"),
            dict(name_ru="Картофельные крокеты", name_ky="Картошка крокеттери", name_en="Potato Croquettes",
                 desc_ru="Хрустящие картофельные шарики, подаются с кетчупом",
                 desc_ky="Кетчуп менен берилген картошка топтору",
                 desc_en="Crispy potato balls, served with ketchup",
                 price=280, photo="kartoshka_krokety"),
            dict(name_ru="Картофель по-деревенски", name_ky="Чон кесилген картошка", name_en="Country-Style Potato Wedges",
                 desc_ru="Запечённый картофель дольками со специями",
                 desc_ky="Даам берүүчү заттар менен бышырылган картошка",
                 desc_en="Oven-roasted potato wedges with spices",
                 price=300, photo="kartoshka_selsky"),
        ],
    },
    # ── 11. Десерты ──────────────────────────────────────────────────────────
    {
        "name_ru": "Десерты", "name_ky": "Таттуулар", "name_en": "Desserts",
        "items": [
            dict(name_ru="Фирменный десерт ДУА", name_ky="Дуадан өзгөчө таттуу", name_en="Signature DUA Dessert",
                 desc_ru="Молочный десерт с апельсином, шоколадным соусом и мятой",
                 desc_ky="Апельсин, шоколад соусу жана жалбыз менен сүт таттуусу",
                 desc_en="Milk pudding with orange, chocolate sauce and mint",
                 price=250, photo="dua_desert"),
            dict(name_ru="Сутлач (рисовый пудинг)", name_ky="Сутлач", name_en="Sütlaç (Rice Pudding)",
                 desc_ru="Традиционный турецкий рисовый пудинг с корицей",
                 desc_ky="Даары менен даярдалган түрк рис пудинги",
                 desc_en="Traditional Turkish rice pudding with cinnamon",
                 price=230, photo="sutlach"),
            dict(name_ru="Пончики в ассортименте (1 шт)", name_ky="Пончиктер", name_en="Assorted Donuts (1 pc)",
                 desc_ru="С шоколадной или белой глазурью, орехами, ягодами",
                 desc_ky="Шоколад же ак глазурь, жаңгак, жемиштер менен",
                 desc_en="Chocolate or white glaze, topped with nuts or berries",
                 price=150, photo="ponchiki"),
            dict(name_ru="Чизкейк Нью-Йорк", name_ky="Нью-Йорк чизкейки", name_en="New York Cheesecake",
                 desc_ru="Классический сливочный чизкейк", desc_ky="Классикалык каймактуу чизкейк",
                 desc_en="Classic creamy baked cheesecake",
                 price=280, photo="cheesecake_assorti"),
            dict(name_ru="Сан Себастьян", name_ky="Сан-Себастьян чизкейки", name_en="San Sebastian Cheesecake",
                 desc_ru="Баскский обожжённый чизкейк", desc_ky="Баск ыкмасында күйдүрүлгөн чизкейк",
                 desc_en="Basque-style burnt cheesecake",
                 price=280, photo="cheesecake_assorti"),
            dict(name_ru="Чизкейк мисте (фисташковый)", name_ky="Фисташка чизкейки", name_en="Pistachio Cheesecake",
                 desc_ru="Чизкейк с фисташковым кремом", desc_ky="Фисташка кремдүү чизкейк",
                 desc_en="Cheesecake with pistachio cream",
                 price=280, photo="cheesecake_assorti"),
            dict(name_ru="Сникерс", name_ky="Сникерс торту", name_en="Snickers Cake",
                 desc_ru="Торт с карамелью, арахисом и шоколадом",
                 desc_ky="Карамель, жердецик жаңгак жана шоколад менен торт",
                 desc_en="Cake with caramel, peanuts and chocolate",
                 price=280, photo="cheesecake_assorti"),
            dict(name_ru="Манго-маракуйя", name_ky="Манго-маракуйя торту", name_en="Mango-Passionfruit Cake",
                 desc_ru="Лёгкий фруктовый торт с манго и маракуйей",
                 desc_ky="Манго жана маракуйя менен жеңил жемиш торту",
                 desc_en="Light fruit cake with mango and passionfruit",
                 price=280, photo="cheesecake_assorti"),
            dict(name_ru="Шоколадно-блинный торт", name_ky="Шоколаддуу блин торту", name_en="Chocolate Crepe Cake",
                 desc_ru="Тонкие блины, прослоенные шоколадным кремом",
                 desc_ky="Шоколад кремдүү жука ойрон катмарлары",
                 desc_en="Layers of thin crepes with chocolate cream",
                 price=280, photo="cheesecake_assorti"),
            dict(name_ru="Манго-малина", name_ky="Манго-малина торту", name_en="Mango-Raspberry Cake",
                 desc_ru="Фруктовый торт с манго и малиной", desc_ky="Манго жана таш бөлүк менен жемиш торту",
                 desc_en="Fruit cake with mango and raspberry",
                 price=280, photo="cheesecake_assorti"),
            dict(name_ru="Чизкейк с голубикой", name_ky="Голубика чизкейки", name_en="Blueberry Cheesecake",
                 desc_ru="Чизкейк с голубичным топпингом", desc_ky="Голубика менен чизкейк",
                 desc_en="Cheesecake topped with blueberry",
                 price=280, photo="cheesecake_assorti"),
            dict(name_ru="Ягодный чизкейк", name_ky="Жемиштүү чизкейк", name_en="Berry Cheesecake",
                 desc_ru="Чизкейк с ягодным топпингом", desc_ky="Жемиштер менен чизкейк",
                 desc_en="Cheesecake topped with mixed berries",
                 price=280, photo="cheesecake_assorti"),
        ],
    },
    # ── 12. Элитные чаи ──────────────────────────────────────────────────────
    {
        "name_ru": "Элитные чаи", "name_ky": "Өзгөчө чайлар", "name_en": "Premium Teas",
        "items": [
            dict(name_ru="Карак чай", name_ky="Карак чай", name_en="Karak Tea",
                 desc_ru="Пряный молочный чай со специями", desc_ky="Даам берүүчү заттар менен сүттүү чай",
                 desc_en="Spiced milk tea",
                 price=400, photo="tea_amber"),
            dict(name_ru="Бергамот", name_ky="Бергомот", name_en="Bergamot Tea",
                 price=120, photo="tea_amber"),
            dict(name_ru="Жасмин", name_ky="Жасмин", name_en="Jasmine Tea",
                 price=120, photo="tea_green"),
            dict(name_ru="Чабрец", name_ky="Кийик от", name_en="Thyme Tea",
                 price=120, photo="tea_green"),
            dict(name_ru="Молочный улун", name_ky="Сүттүү улун", name_en="Milk Oolong Tea",
                 price=120, photo="tea_amber"),
            dict(name_ru="Фирменный чай ДУА", name_ky="Дуадан өзгөчө чай", name_en="Signature DUA Tea",
                 price=250, photo="tea_red"),
            dict(name_ru="Солнечный поцелуй", name_ky="Күн өбүшү", name_en="Sun Kiss Tea",
                 price=250, photo="tea_amber"),
            dict(name_ru="Глинтвейн", name_ky="Глинтвейн", name_en="Mulled Tea", price=250, photo="tea_red"),
            dict(name_ru="Смородиновый чай", name_ky="Карагат", name_en="Blackcurrant Tea",
                 price=250, photo="tea_red"),
            dict(name_ru="Имбирный чай", name_ky="Имбирь", name_en="Ginger Tea", price=240, photo="tea_amber"),
            dict(name_ru="Малиновый чай", name_ky="Малина", name_en="Raspberry Tea", price=180, photo="tea_red"),
            dict(name_ru="Облепиховый чай", name_ky="Чычырканак", name_en="Sea Buckthorn Tea",
                 price=240, photo="tea_amber"),
            dict(name_ru="Молочный чай", name_ky="Сүттүү чай", name_en="Milk Tea", price=240, photo="tea_amber"),
        ],
    },
    # ── 13. Кофе ─────────────────────────────────────────────────────────────
    {
        "name_ru": "Кофе", "name_ky": "Кофелер", "name_en": "Coffee",
        "items": [
            dict(name_ru="Эспрессо двойной", name_ky="Эспрессо 2х", name_en="Double Espresso",
                 desc_ru="200 мл", desc_ky="200 мл", desc_en="200 ml", price=180, photo="coffee_hot"),
            dict(name_ru="Американо", name_ky="Американо", name_en="Americano",
                 desc_ru="200 мл", desc_ky="200 мл", desc_en="200 ml", price=180, photo="coffee_hot"),
            dict(name_ru="Капучино", name_ky="Капучино", name_en="Cappuccino",
                 desc_ru="200 мл", desc_ky="200 мл", desc_en="200 ml", price=180, photo="coffee_hot"),
            dict(name_ru="Латте", name_ky="Латте", name_en="Latte",
                 desc_ru="300 мл", desc_ky="300 мл", desc_en="300 ml", price=200, photo="coffee_hot"),
            dict(name_ru="Флэт уайт", name_ky="Флэт уайт", name_en="Flat White",
                 desc_ru="200 мл", desc_ky="200 мл", desc_en="200 ml", price=200, photo="coffee_hot"),
            dict(name_ru="Мокко", name_ky="Мокко", name_en="Mocha",
                 desc_ru="200 мл", desc_ky="200 мл", desc_en="200 ml", price=180, photo="coffee_hot"),
            dict(name_ru="Раф классический", name_ky="Раф классический", name_en="Classic Raf",
                 desc_ru="300 мл", desc_ky="300 мл", desc_en="300 ml", price=230, photo="coffee_hot"),
            dict(name_ru="Какао", name_ky="Какао", name_en="Hot Chocolate",
                 desc_ru="300 мл", desc_ky="300 мл", desc_en="300 ml", price=150, photo="coffee_hot"),
        ],
    },
    # ── 14. Холодный кофе ────────────────────────────────────────────────────
    {
        "name_ru": "Холодный кофе", "name_ky": "Муздак кофелер", "name_en": "Iced Coffee",
        "items": [
            dict(name_ru="Айс Американо", name_ky="Айс американо", name_en="Iced Americano",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="iced_americano"),
            dict(name_ru="Айс Капучино", name_ky="Айс капучино", name_en="Iced Cappuccino",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=200, photo="iced_cappuccino"),
            dict(name_ru="Айс Латте", name_ky="Айс латте", name_en="Iced Latte",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=200, photo="iced_cappuccino"),
            dict(name_ru="Айс Раф", name_ky="Айс раф", name_en="Iced Raf",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=240, photo="iced_cappuccino"),
            dict(name_ru="Айс Капучино мисте (фисташка)", name_ky="Айс капучино мисте", name_en="Iced Pistachio Cappuccino",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=240, photo="iced_cappuccino"),
            dict(name_ru="Айс Банан Латте", name_ky="Айс банан латте", name_en="Iced Banana Latte",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=200, photo="iced_cappuccino"),
            dict(name_ru="Айс Раф Кокос", name_ky="Айс раф кокос", name_en="Iced Coconut Raf",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=240, photo="iced_cappuccino"),
            dict(name_ru="Гляссе", name_ky="Гляссе", name_en="Café Glacé (Coffee with Ice Cream)",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=200, photo="glace"),
        ],
    },
    # ── 15. Лимонады ─────────────────────────────────────────────────────────
    {
        "name_ru": "Лимонады", "name_ky": "Лимонадтар", "name_en": "Lemonades",
        "items": [
            dict(name_ru="Фиолетовый вайб", name_ky="Фиолетовый вайб", name_en="Purple Vibe",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="lemonade_purple"),
            dict(name_ru="Коко манго", name_ky="Коко манго", name_en="Coco Mango",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="lemonade_orange"),
            dict(name_ru="Красный бриз", name_ky="Кызыл бриз", name_en="Red Breeze",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="lemonade_red"),
            dict(name_ru="Солнечный микс", name_ky="Солнечный микс", name_en="Sunny Mix",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="lemonade_orange"),
            dict(name_ru="Летний удар", name_ky="Летный удар", name_en="Summer Splash",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="lemonade_orange"),
            dict(name_ru="Золотой мохито", name_ky="Алтын мохито", name_en="Golden Mojito",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="lemonade_orange"),
            dict(name_ru="Мохито классика", name_ky="Мохито классика", name_en="Classic Mojito",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="lemonade_purple"),
            dict(name_ru="Мохито Океан", name_ky="Мохито океан", name_en="Ocean Mojito",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="lemonade_purple"),
            dict(name_ru="Манго Маракуйя", name_ky="Манго маракуя", name_en="Mango Passionfruit",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="lemonade_orange"),
        ],
    },
    # ── 16. Смузи ────────────────────────────────────────────────────────────
    {
        "name_ru": "Смузи", "name_ky": "Смузи", "name_en": "Smoothies",
        "items": [
            dict(name_ru="Фирменный смузи", name_ky="Өзгөчө", name_en="Signature Smoothie",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=280, photo="smoothie_red"),
            dict(name_ru="Банановый смузи", name_ky="Банан", name_en="Banana Smoothie",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=200, photo="smoothie_yellow"),
            dict(name_ru="Зелёная волна", name_ky="Жашыл толкун", name_en="Green Wave Smoothie",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=200, photo="smoothie_green"),
            dict(name_ru="Клубничный смузи", name_ky="Кулпунай", name_en="Strawberry Smoothie",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=220, photo="smoothie_red"),
        ],
    },
    # ── 17. Матча ────────────────────────────────────────────────────────────
    {
        "name_ru": "Матча", "name_ky": "Матча", "name_en": "Matcha",
        "items": [
            dict(name_ru="Фирменная матча ДУА", name_ky="Дуадан өзгөчө матча", name_en="Signature DUA Matcha",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=260, photo="matcha_green"),
            dict(name_ru="Голубая матча", name_ky="Көк матча", name_en="Blue Matcha",
                 desc_ru="300 мл", desc_ky="300 мл", desc_en="300 ml", price=180, photo="matcha_blue"),
            dict(name_ru="Зелёная матча", name_ky="Жашыл матча", name_en="Green Matcha",
                 desc_ru="300 мл", desc_ky="300 мл", desc_en="300 ml", price=180, photo="matcha_green"),
            dict(name_ru="Айс голубая матча", name_ky="Көк матча муз м/н", name_en="Iced Blue Matcha",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="matcha_blue"),
            dict(name_ru="Айс зелёная матча", name_ky="Жашыл матча муз м/н", name_en="Iced Green Matcha",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=180, photo="matcha_green"),
        ],
    },
    # ── 18. Коктейли ─────────────────────────────────────────────────────────
    {
        "name_ru": "Коктейли", "name_ky": "Коктейлдер", "name_en": "Milkshakes",
        "items": [
            dict(name_ru="Фирменный коктейль", name_ky="Өзгөчө", name_en="Signature Milkshake",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=240, photo="cocktail_white"),
            dict(name_ru="Банановый коктейль", name_ky="Банан", name_en="Banana Milkshake",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=220, photo="cocktail_yellow"),
            dict(name_ru="Классический коктейль", name_ky="Классика", name_en="Classic Milkshake",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=200, photo="cocktail_white"),
            dict(name_ru="Шоколадный коктейль", name_ky="Шоколад", name_en="Chocolate Milkshake",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=220, photo="cocktail_white"),
            dict(name_ru="Клубничный коктейль", name_ky="Кулпунай", name_en="Strawberry Milkshake",
                 desc_ru="400 мл", desc_ky="400 мл", desc_en="400 ml", price=220, photo="cocktail_pink"),
        ],
    },
    # ── 19. Напитки ──────────────────────────────────────────────────────────
    {
        "name_ru": "Напитки", "name_ky": "Суусундуктар", "name_en": "Drinks",
        "items": [
            dict(name_ru="Айран 1 л", name_ky="Айран 1л", name_en="Ayran 1 L", price=150, photo="ayran"),
            dict(name_ru="Айран (стакан)", name_ky="Айран стакан", name_en="Ayran (glass)", price=50, photo="ayran"),
            dict(name_ru="Bona Aqua 0,5 л", name_ky="Бонаква 0,5л", name_en="Bona Aqua 0.5 L",
                 price=70, photo="soft_drink_water"),
            dict(name_ru="Bona Aqua 1 л", name_ky="Бонаква 1л", name_en="Bona Aqua 1 L",
                 price=100, photo="soft_drink_water"),
            dict(name_ru="Coca-Cola 0,5 л", name_ky="Кола 0,5л", name_en="Coca-Cola 0.5 L",
                 price=100, photo="soft_drink_cola"),
            dict(name_ru="Coca-Cola 1 л", name_ky="Кола 1л", name_en="Coca-Cola 1 L",
                 price=180, photo="soft_drink_cola"),
            dict(name_ru="Coca-Cola (банка)", name_ky="Кола баночка", name_en="Coca-Cola (can)",
                 price=120, photo="soft_drink_cola"),
            dict(name_ru="Coca-Cola (стекло 0,3 л)", name_ky="Кола стекло 0,3л", name_en="Coca-Cola (glass bottle 0.3 L)",
                 price=100, photo="soft_drink_cola"),
            dict(name_ru="Компот 1 л", name_ky="Компот 1л", name_en="Fruit Compote 1 L", price=150, photo="kompot"),
            dict(name_ru="Компот (стакан)", name_ky="Компот стакан", name_en="Fruit Compote (glass)", price=50, photo="kompot"),
            dict(name_ru="Сок в ассортименте 1 л", name_ky="Сок ассортименте 1л", name_en="Assorted Juice 1 L",
                 price=190, photo="juice"),
            dict(name_ru="Sprite 0,5 л", name_ky="Спрайт 0,5л", name_en="Sprite 0.5 L",
                 price=100, photo="soft_drink_sprite"),
            dict(name_ru="Sprite 1 л", name_ky="Спрайт 1л", name_en="Sprite 1 L",
                 price=180, photo="soft_drink_sprite"),
            dict(name_ru="Fanta 0,5 л", name_ky="Фанта 0,5л", name_en="Fanta 0.5 L",
                 price=100, photo="soft_drink_fanta"),
            dict(name_ru="Fanta 1 л", name_ky="Фанта 1л", name_en="Fanta 1 L",
                 price=180, photo="soft_drink_fanta"),
            dict(name_ru="Чай Fuzetea 0,5 л", name_ky="Чай фюсти 0,5л", name_en="Fuzetea 0.5 L", price=100, photo="fuzetea"),
            dict(name_ru="Чай Fuzetea 1 л", name_ky="Чай фюсти 1л", name_en="Fuzetea 1 L", price=180, photo="fuzetea"),
            dict(name_ru="Турецкий чай (чайник)", name_ky="Чай турецкий чайник", name_en="Turkish Tea (teapot)",
                 price=80, photo="turkish_tea"),
            dict(name_ru="Турецкий чай (чашка)", name_ky="Чай турецкий чашка", name_en="Turkish Tea (cup)",
                 price=20, photo="turkish_tea"),
            dict(name_ru="Чай чёрный", name_ky="Чай черный", name_en="Black Tea", price=60, photo="tea_black_cup"),
            dict(name_ru="Чай зелёный", name_ky="Чай зеленый", name_en="Green Tea", price=60, photo="tea_green_cup"),
        ],
    },
]
