# -*- coding: utf-8 -*-
"""
Полные данные по услугам полиграф-центра "Ош Принт" — фото + переводы (KY/EN)
+ описания на 3 языках. Ключ словаря — точное name_ru с продакшна (сверено с
https://webordo.kg/ru/printshop/Osh_print/b/1/). Сопоставление в скрипте
регистронезависимое, так что регистр ключа не критичен.

Похожие варианты (разный размер/материал/крепление) сознательно используют
ОДНО представительное фото — см. комментарий в attach_printshop_photos.py.
"""

ITEMS = {
    # ── Бумажный ──────────────────────────────────────────────────────────
    "Визитки": dict(photo="business_cards", name_ky="Визиткалар", name_en="Business Cards",
        desc_ru="Полноцветная печать, плотная бумага 300–350г, ламинация по желанию",
        desc_ky="Толук түстүү басма, калың кагаз 300–350г, каалаган түрдө ламинация",
        desc_en="Full-color printing, 300–350g cardstock, optional lamination"),
    "Листовки А6": dict(photo="flyers", name_ky="Баракчалар А6", name_en="Flyers A6",
        desc_ru="Формат А6, полноцветная печать, плотность бумаги от 130г",
        desc_ky="А6 формат, толук түстүү басма, кагаз калыңдыгы 130г баштап",
        desc_en="A6 format, full-color print, paper weight from 130g"),
    "Флаеры А6": dict(photo="flyers", name_ky="Флаерлер А6", name_en="A6 Flyers",
        desc_ru="Формат А6, яркая полноцветная печать для рекламных акций",
        desc_ky="А6 формат, жарнама үчүн жарык толук түстүү басма",
        desc_en="A6 format, vivid full-color printing for promotions"),
    "Буклеты": dict(photo="brochure", name_ky="Буклеттер", name_en="Brochures",
        desc_ru="Сложенная в 2–3 части печатная продукция для презентации услуг",
        desc_ky="Кызматтарды тартуулоо үчүн 2–3 бүктөлгөн басма продукция",
        desc_en="Folded (bi-/tri-fold) print piece for presenting services"),
    "Каталог А4": dict(photo="catalog", name_ky="Каталог А4", name_en="Catalog A4",
        desc_ru="Многостраничный каталог формата А4, сшивка на скрепку",
        desc_ky="А4 форматындагы көп баракчалуу каталог, скрепка менен тигилген",
        desc_en="Multi-page A4 catalog, staple-bound"),
    "Каталог А3": dict(photo="catalog", name_ky="Каталог А3", name_en="Catalog A3",
        desc_ru="Многостраничный каталог формата А3",
        desc_ky="А3 форматындагы көп баракчалуу каталог",
        desc_en="Multi-page A3 catalog"),
    "Блокноты": dict(photo="notepad", name_ky="Блокноттор", name_en="Notepads",
        desc_ru="Блокнот на пружине или склейке, любой формат",
        desc_ky="Пружиналуу же желимделген блокнот, каалаган формат",
        desc_en="Spiral or glue-bound notepad, any format"),
    "Календарь перекидной": dict(photo="flip_calendar", name_ky="Кыдырма календарь", name_en="Flip Calendar",
        desc_ru="Настенный перекидной календарь на 12 месяцев",
        desc_ky="12 айга эсептелген дубал кыдырма календары",
        desc_en="12-month wall flip calendar"),

    # ── Брендирование ─────────────────────────────────────────────────────
    "нанесение лого на кепку": dict(photo="cap", name_ky="Кепкага лого басуу", name_en="Logo Printing on Cap",
        desc_ru="Нанесение вашего логотипа на кепку методом вышивки или печати",
        desc_ky="Кепкага логотипиңизди кестелөө же басма ыкмасы менен түшүрүү",
        desc_en="Applying your logo to a cap via embroidery or print"),
    "нанесение лого на футболку": dict(photo="tshirt", name_ky="Футболкага лого басуу", name_en="Logo Printing on T-Shirt",
        desc_ru="Нанесение логотипа на футболку методом шелкографии или DTF",
        desc_ky="Футболкага логотипди шелкография же DTF ыкмасы менен түшүрүү",
        desc_en="Logo printing on a t-shirt via screen print or DTF"),
    "ручка с логотипом": dict(photo="pen", name_ky="Логотиптүү ручка", name_en="Pen with Logo",
        desc_ru="Пластиковая или металлическая ручка с нанесением логотипа",
        desc_ky="Логотип түшүрүлгөн пластик же метал ручка",
        desc_en="Plastic or metal pen with your logo printed"),
    "флаг настольный с лого": dict(photo="table_tent", name_ky="Логотиптүү үстөл желеги", name_en="Desk Flag with Logo",
        desc_ru="Настольный флажок с печатью логотипа компании",
        desc_ky="Компаниянын логотиби басылган үстөл желеги",
        desc_en="Desk flag printed with your company logo"),
    "календарь перекидной с лого": dict(photo="flip_calendar", name_ky="Логотиптүү кыдырма календарь", name_en="Flip Calendar with Logo",
        desc_ru="Перекидной календарь с брендированием логотипом",
        desc_ky="Логотип менен брендделген кыдырма календарь",
        desc_en="Flip calendar branded with your logo"),
    "Перекидной календарь": dict(photo="flip_calendar", name_ky="Кыдырма календарь", name_en="Flip Calendar",
        desc_ru="Настенный перекидной календарь без брендирования",
        desc_ky="Брендсиз дубал кыдырма календары",
        desc_en="Plain (unbranded) wall flip calendar"),
    "кружки с лого": dict(photo="mug", name_ky="Логотиптүү кружка", name_en="Mug with Logo",
        desc_ru="Керамическая кружка с нанесением логотипа",
        desc_ky="Логотип түшүрүлгөн керамика кружка",
        desc_en="Ceramic mug printed with your logo"),
    "термосы с лого": dict(photo="thermos", name_ky="Логотиптүү термос", name_en="Thermos with Logo",
        desc_ru="Термос из нержавеющей стали с нанесением логотипа",
        desc_ky="Логотип түшүрүлгөн дат баспас болоттон жасалган термос",
        desc_en="Stainless steel thermos printed with your logo"),
    "нанесение лого на блокноты": dict(photo="notepad", name_ky="Блокнотко лого басуу", name_en="Logo Printing on Notepads",
        desc_ru="Нанесение логотипа на обложку блокнота",
        desc_ky="Блокноттун мукабасына логотип түшүрүү",
        desc_en="Logo printing on notepad cover"),
    "блокнот с лого": dict(photo="notepad", name_ky="Логотиптүү блокнот", name_en="Notepad with Logo",
        desc_ru="Готовый блокнот с фирменным логотипом на обложке",
        desc_ky="Мукабасында фирмалык логотиби бар даяр блокнот",
        desc_en="Ready-made notepad with your logo on the cover"),
    "нанесение лого на часы": dict(photo="watch", name_ky="Саатка лого басуу", name_en="Logo Printing on Watches",
        desc_ru="Нанесение логотипа на циферблат или корпус часов",
        desc_ky="Саат бетине же корпусуна логотип түшүрүү",
        desc_en="Logo printing on a watch face or case"),
    "нанесение лого на сумку": dict(photo="bag", name_ky="Баштыкка лого басуу", name_en="Logo Printing on Bags",
        desc_ru="Нанесение логотипа на тканевую или кожаную сумку",
        desc_ky="Кездеме же булгаары баштыкка логотип түшүрүү",
        desc_en="Logo printing on a fabric or leather bag"),
    "пакеты с лого": dict(photo="cardboard_bag", name_ky="Логотиптүү пакеттер", name_en="Branded Paper Bags",
        desc_ru="Бумажные пакеты с печатью логотипа",
        desc_ky="Логотиби басылган кагаз пакеттер",
        desc_en="Paper bags printed with your logo"),
    "штамп с лого": dict(photo="stamp", name_ky="Логотиптүү мөөр", name_en="Stamp with Logo",
        desc_ru="Автоматический штамп с реквизитами и логотипом компании",
        desc_ky="Компаниянын реквизиттери жана логотиби менен автоматтык мөөр",
        desc_en="Self-inking stamp with company details and logo"),
    "брелок с лого": dict(photo="keychain", name_ky="Логотиптүү брелок", name_en="Keychain with Logo",
        desc_ru="Сувенирный брелок с нанесением логотипа",
        desc_ky="Логотип түшүрүлгөн эстелик брелок",
        desc_en="Souvenir keychain printed with your logo"),
    "бейджик с лого": dict(photo="badge_lanyard", name_ky="Логотиптүү бейджик", name_en="Badge with Logo",
        desc_ru="Именной бейджик сотрудника с логотипом компании",
        desc_ky="Компаниянын логотиби менен кызматкердин ысымдык бейджиги",
        desc_en="Employee name badge with your company logo"),
    "ленты с лого": dict(photo="badge_lanyard", name_ky="Логотиптүү лента", name_en="Lanyard with Logo",
        desc_ru="Лента (ланъярд) для бейджа с печатью логотипа",
        desc_ky="Бейджик үчүн логотиби басылган лента (ланъярд)",
        desc_en="Lanyard for a badge, printed with your logo"),
    "платежная табличка с лого": dict(photo="payment_sign", name_ky="Логотиптүү төлөм тактайчасы", name_en="Payment Sign with Logo",
        desc_ru="Табличка «Оплата картой» с логотипом компании",
        desc_ky="Компаниянын логотиби менен «Карта менен төлөө» тактайчасы",
        desc_en="\"Card payment accepted\" sign with your logo"),
    "пакеты картонные": dict(photo="cardboard_bag", name_ky="Картон пакеттер", name_en="Cardboard Bags",
        desc_ru="Плотные бумажные пакеты с ручками",
        desc_ky="Туткасы бар калың кагаз пакеттер",
        desc_en="Sturdy paper bags with handles"),
    "папки с боковой кармашкой": dict(photo="folder", name_ky="Капталында кабы бар папка", name_en="Folder with Side Pocket",
        desc_ru="Картонная папка с боковым карманом для визиток",
        desc_ky="Визиткалар үчүн капталында чөнтөгү бар картон папка",
        desc_en="Cardboard folder with a side pocket for business cards"),
    "папки с нижней кармашкой": dict(photo="folder", name_ky="Астында кабы бар папка", name_en="Folder with Bottom Pocket",
        desc_ru="Картонная папка с карманом снизу",
        desc_ky="Астыңкы жагында чөнтөгү бар картон папка",
        desc_en="Cardboard folder with a bottom pocket"),
    "Брендирование автомобилей": dict(photo="car_branding", name_ky="Автоунааларды брендирлөө", name_en="Vehicle Branding",
        desc_ru="Оклейка автомобиля виниловой плёнкой с рекламой",
        desc_ky="Унааны жарнамалык винил плёнка менен каптоо",
        desc_en="Vehicle vinyl wrap advertising"),
    "каталог А4": dict(photo="catalog", name_ky="Каталог А4", name_en="Catalog A4",
        desc_ru="Многостраничный каталог формата А4",
        desc_ky="А4 форматындагы көп баракчалуу каталог",
        desc_en="Multi-page A4 catalog"),
    "каталог А3": dict(photo="catalog", name_ky="Каталог А3", name_en="Catalog A3",
        desc_ru="Многостраничный каталог формата А3",
        desc_ky="А3 форматындагы көп баракчалуу каталог",
        desc_en="Multi-page A3 catalog"),

    # ── Таблички ──────────────────────────────────────────────────────────
    "Пластиковая табличка для двери": dict(photo="door_sign", name_ky="Эшик үчүн пластик тактайча", name_en="Plastic Door Plate",
        desc_ru="Табличка на дверь кабинета из пластика",
        desc_ky="Кабинет эшигине пластиктен жасалган тактайча",
        desc_en="Plastic office door nameplate"),
    "Табличка прозрачная 3д": dict(photo="acrylic_3d_sign", name_ky="Тунук 3Д тактайча", name_en="Transparent 3D Sign",
        desc_ru="Прозрачная акриловая табличка с объёмными буквами",
        desc_ky="Көлөмдүү тамгалары бар тунук акрил тактайча",
        desc_en="Clear acrylic sign with 3D lettering"),
    "Пластиковая табличка А4": dict(photo="door_sign", name_ky="Пластик тактайча А4", name_en="Plastic Sign A4",
        desc_ru="Информационная табличка формата А4",
        desc_ky="А4 форматындагы маалымат тактайчасы",
        desc_en="A4-size plastic information sign"),
    "Пластиковая табличка А3": dict(photo="door_sign", name_ky="Пластик тактайча А3", name_en="Plastic Sign A3",
        desc_ru="Информационная табличка формата А3",
        desc_ky="А3 форматындагы маалымат тактайчасы",
        desc_en="A3-size plastic information sign"),
    "Платёжная табличка А5": dict(photo="payment_sign", name_ky="Төлөм тактайчасы А5", name_en="Payment Sign A5",
        desc_ru="Табличка со способами оплаты формата А5",
        desc_ky="А5 форматындагы төлөм ыкмалары көрсөтүлгөн тактайча",
        desc_en="A5 sign showing accepted payment methods"),
    "Платёжная табличка круглая А5": dict(photo="payment_sign", name_ky="Тегерек төлөм тактайчасы А5", name_en="Round Payment Sign A5",
        desc_ru="Круглая табличка со способами оплаты",
        desc_ky="Тегерек формадагы төлөм тактайчасы",
        desc_en="Round-shaped payment sign"),
    "Платёжная табличка с 3Д буквами": dict(photo="acrylic_3d_sign", name_ky="3Д тамгалуу төлөм тактайчасы", name_en="Payment Sign with 3D Letters",
        desc_ru="Табличка со способами оплаты с объёмными буквами",
        desc_ky="Көлөмдүү тамгалары бар төлөм тактайчасы",
        desc_en="Payment sign with raised 3D lettering"),
    "Прайс лист из акрила А4": dict(photo="price_list", name_ky="Акрил прайс-лист А4", name_en="Acrylic Price List A4",
        desc_ru="Прайс-лист на акриловой подложке формата А4",
        desc_ky="А4 форматындагы акрил негиздеги прайс-лист",
        desc_en="A4 price list mounted on acrylic"),
    "таблички из пластика": dict(photo="door_sign", name_ky="Пластик тактайчалар", name_en="Plastic Signs",
        desc_ru="Информационные таблички из пластика любого формата",
        desc_ky="Каалаган формадагы пластик маалымат тактайчалары",
        desc_en="Plastic information signs, any size"),

    # ── Сувенирная продукция ──────────────────────────────────────────────
    "кружка белая": dict(photo="mug", name_ky="Ак кружка", name_en="White Mug",
        desc_ru="Классическая белая керамическая кружка под печать",
        desc_ky="Басма үчүн классикалык ак керамика кружка",
        desc_en="Classic white ceramic mug for printing"),
    "кружка хамелеон": dict(photo="mug_chameleon", name_ky="Хамелеон кружка", name_en="Chameleon (Color-Changing) Mug",
        desc_ru="Кружка, меняющая цвет при заливке горячего напитка",
        desc_ky="Ысык суусундук куюлганда түсү өзгөргөн кружка",
        desc_en="Mug that changes color with a hot drink"),
    "журнал А4 в стиле Вог": dict(photo="catalog", name_ky="Мода стилиндеги А4 журнал", name_en="Fashion-Style A4 Magazine",
        desc_ru="Персональный журнал в стиле модного издания, формат А4",
        desc_ky="Мода журналы стилиндеги жеке журнал, А4 формат",
        desc_en="Personalized fashion-magazine-style booklet, A4"),
    "Фотоколлаж А4": dict(photo="photo_collage", name_ky="Фотоколлаж А4", name_en="Photo Collage A4",
        desc_ru="Печать коллажа из ваших фото формата А4",
        desc_ky="Сиздин сүрөттөрүңүздөн А4 форматындагы коллаж басуу",
        desc_en="A4 print collage made from your photos"),
    "Фотоколлаж А3": dict(photo="photo_collage", name_ky="Фотоколлаж А3", name_en="Photo Collage A3",
        desc_ru="Печать коллажа из ваших фото формата А3",
        desc_ky="Сиздин сүрөттөрүңүздөн А3 форматындагы коллаж басуу",
        desc_en="A3 print collage made from your photos"),
    "Парные футболки": dict(photo="tshirt", name_ky="Жуп футболкалар", name_en="Matching Couple T-Shirts",
        desc_ru="Парные футболки с индивидуальным принтом",
        desc_ky="Жеке принти бар жуп футболкалар",
        desc_en="Matching t-shirts with a custom print"),
    "Парные кепки": dict(photo="cap", name_ky="Жуп кепкалар", name_en="Matching Caps",
        desc_ru="Парные кепки с индивидуальным принтом",
        desc_ky="Жеке принти бар жуп кепкалар",
        desc_en="Matching caps with a custom print"),
    "Светильник настольный": dict(photo="desk_lamp", name_ky="Үстөл лампасы", name_en="Desk Lamp",
        desc_ru="Настольный светильник с фотопечатью на плафоне",
        desc_ky="Плафонунда фотобасма бар үстөл лампасы",
        desc_en="Desk lamp with a photo-printed shade"),
    "Футболка с принтом": dict(photo="tshirt", name_ky="Принттүү футболка", name_en="Printed T-Shirt",
        desc_ru="Футболка с печатью любого изображения",
        desc_ky="Каалаган сүрөт басылган футболка",
        desc_en="T-shirt printed with any image"),
    "ручка именная": dict(photo="pen", name_ky="Ысымдык ручка", name_en="Personalized Pen",
        desc_ru="Ручка с гравировкой имени",
        desc_ky="Ысым чегилген ручка",
        desc_en="Pen engraved with a name"),
    "блокнот именной набор": dict(photo="notepad", name_ky="Ысымдык блокнот топтому", name_en="Personalized Notepad Set",
        desc_ru="Набор именных блокнотов с гравировкой",
        desc_ky="Чегилген ысымдык блокноттор топтому",
        desc_en="Set of personalized engraved notepads"),
    "термос именной": dict(photo="thermos", name_ky="Ысымдык термос", name_en="Personalized Thermos",
        desc_ru="Термос с гравировкой имени",
        desc_ky="Ысым чегилген термос",
        desc_en="Thermos engraved with a name"),
    "фотомозаика 40*60см": dict(photo="photo_mosaic", name_ky="Фотомозаика 40*60см", name_en="Photo Mosaic 40×60cm",
        desc_ru="Настенная фотомозаика из множества ваших фото, 40×60 см",
        desc_ky="Көптөгөн сүрөттөрүңүздөн турган дубал фотомозаикасы, 40×60 см",
        desc_en="Wall photo mosaic made from many of your photos, 40×60 cm"),
    "фотомозаика 50*70см": dict(photo="photo_mosaic", name_ky="Фотомозаика 50*70см", name_en="Photo Mosaic 50×70cm",
        desc_ru="Настенная фотомозаика из множества ваших фото, 50×70 см",
        desc_ky="Көптөгөн сүрөттөрүңүздөн турган дубал фотомозаикасы, 50×70 см",
        desc_en="Wall photo mosaic made from many of your photos, 50×70 cm"),
    "фотомозаика 60*80см": dict(photo="photo_mosaic", name_ky="Фотомозаика 60*80см", name_en="Photo Mosaic 60×80cm",
        desc_ru="Настенная фотомозаика из множества ваших фото, 60×80 см",
        desc_ky="Көптөгөн сүрөттөрүңүздөн турган дубал фотомозаикасы, 60×80 см",
        desc_en="Wall photo mosaic made from many of your photos, 60×80 cm"),
    "фотомозаика 80*100см": dict(photo="photo_mosaic", name_ky="Фотомозаика 80*100см", name_en="Photo Mosaic 80×100cm",
        desc_ru="Настенная фотомозаика из множества ваших фото, 80×100 см",
        desc_ky="Көптөгөн сүрөттөрүңүздөн турган дубал фотомозаикасы, 80×100 см",
        desc_en="Wall photo mosaic made from many of your photos, 80×100 cm"),
    "автодокументница": dict(photo="car_document_holder", name_ky="Авто документ кабы", name_en="Car Document Holder",
        desc_ru="Кожаная обложка для автомобильных документов",
        desc_ky="Автоунаа документтери үчүн булгаары кап",
        desc_en="Leather cover for vehicle documents"),
    "автодокументница с портмоне": dict(photo="car_document_holder", name_ky="Портмонелуу авто документ кабы", name_en="Car Document Holder with Wallet",
        desc_ru="Обложка для автодокументов со вставкой портмоне",
        desc_ky="Портмоне салынган автодокумент кабы",
        desc_en="Vehicle document holder with a wallet insert"),
    "брелок номер машины": dict(photo="license_plate_keychain", name_ky="Унаа номери брелогу", name_en="License Plate Keychain",
        desc_ru="Брелок с гравировкой номера автомобиля",
        desc_ky="Унаанын номери чегилген брелок",
        desc_en="Keychain engraved with your car's license plate number"),
    "фотокамень квадратный": dict(photo=None, name_ky="Чарчы фотокамень", name_en="Square Photo Stone",
        desc_ru="Квадратный камень с гравировкой фото",
        desc_ky="Сүрөт чегилген чарчы таш",
        desc_en="Square engraved photo stone"),
    "фотокамень круглый": dict(photo=None, name_ky="Тегерек фотокамень", name_en="Round Photo Stone",
        desc_ru="Круглый камень с гравировкой фото",
        desc_ky="Сүрөт чегилген тегерек таш",
        desc_en="Round engraved photo stone"),

    # ── Тейбл тенды ───────────────────────────────────────────────────────
    "Тейбл тенд А3": dict(photo="table_tent", name_ky="Тейбл тенд А3", name_en="Table Tent A3",
        desc_ru="Настольная табличка-стойка формата А3 для меню/рекламы",
        desc_ky="Меню/жарнама үчүн А3 форматындагы үстөл тургузмасы",
        desc_en="A3 table tent stand for menus/promotions"),
    "Тейбл тенд А4": dict(photo="table_tent", name_ky="Тейбл тенд А4", name_en="Table Tent A4",
        desc_ru="Настольная табличка-стойка формата А4",
        desc_ky="А4 форматындагы үстөл тургузмасы",
        desc_en="A4 table tent stand"),
    "Тейбл тенд А5": dict(photo="table_tent", name_ky="Тейбл тенд А5", name_en="Table Tent A5",
        desc_ru="Настольная табличка-стойка формата А5",
        desc_ky="А5 форматындагы үстөл тургузмасы",
        desc_en="A5 table tent stand"),
    "Ценникодержатель из акрила": dict(photo="price_list", name_ky="Акрил баа кармагыч", name_en="Acrylic Price Tag Holder",
        desc_ru="Держатель для ценника из прозрачного акрила",
        desc_ky="Баа тагын кармоочу тунук акрил кармагыч",
        desc_en="Clear acrylic price tag holder"),

    # ── Продукция для ресторанов (+ дублируются в категории "Бейджики") ────
    "Салфетница с плотным объемом": dict(photo="napkin_holder", name_ky="Көп сыйымдуу сальфетница", name_en="Napkin Holder (Thick)",
        desc_ru="Салфетница большой вместимости для ресторана",
        desc_ky="Ресторан үчүн көп сыйымдуу сальфетница",
        desc_en="Large-capacity restaurant napkin holder"),
    "Салфетница с тонким объемом": dict(photo="napkin_holder", name_ky="Ичке сальфетница", name_en="Napkin Holder (Thin)",
        desc_ru="Салфетница компактного размера",
        desc_ky="Компакттуу өлчөмдөгү сальфетница",
        desc_en="Compact-size napkin holder"),
    "Салфетница мини размера": dict(photo="napkin_holder", name_ky="Мини сальфетница", name_en="Mini Napkin Holder",
        desc_ru="Салфетница минимального размера для маленьких столов",
        desc_ky="Кичине столдор үчүн мини сальфетница",
        desc_en="Minimal-size napkin holder for small tables"),
    "Счётница из фанеры": dict(photo="bill_holder", name_ky="Фанера эсептегич", name_en="Plywood Bill Holder",
        desc_ru="Держатель для чеков из фанеры",
        desc_ky="Фанерадан жасалган чек кармагыч",
        desc_en="Plywood bill/receipt holder"),
    "Таблички Резерв": dict(photo="reserved_sign", name_ky="«Резерв» тактайчасы", name_en="\"Reserved\" Table Sign",
        desc_ru="Табличка «Стол зарезервирован» для ресторана",
        desc_ky="Ресторан үчүн «Стол брондолгон» тактайчасы",
        desc_en="\"Table Reserved\" sign for restaurants"),
    "Бейджики из пластика с булавкой": dict(photo="badge_lanyard", name_ky="Пластик бейджик (ийне менен)", name_en="Plastic Badge with Pin",
        desc_ru="Пластиковый бейджик, крепление на булавке",
        desc_ky="Ийне менен бекитилүүчү пластик бейджик",
        desc_en="Plastic badge with a pin fastener"),
    "Бейджики из пластика на магните": dict(photo="badge_lanyard", name_ky="Пластик бейджик (магнит менен)", name_en="Plastic Badge with Magnet",
        desc_ru="Пластиковый бейджик, крепление на магните",
        desc_ky="Магнит менен бекитилүүчү пластик бейджик",
        desc_en="Plastic badge with a magnetic fastener"),
    "Бейджик из пластика со сменным именем с булавкой": dict(photo="badge_lanyard", name_ky="Алмаштырылуучу ысымдуу пластик бейджик (ийне)", name_en="Plastic Badge with Changeable Name, Pin",
        desc_ru="Бейджик со сменной вставкой имени, крепление на булавке",
        desc_ky="Ысымы алмашылуучу, ийне менен бекитилген бейджик",
        desc_en="Badge with a replaceable name insert, pin fastener"),
    "Бейджик из пластика со сменным именем на магните": dict(photo="badge_lanyard", name_ky="Алмаштырылуучу ысымдуу пластик бейджик (магнит)", name_en="Plastic Badge with Changeable Name, Magnet",
        desc_ru="Бейджик со сменной вставкой имени, крепление на магните",
        desc_ky="Ысымы алмашылуучу, магнит менен бекитилген бейджик",
        desc_en="Badge with a replaceable name insert, magnetic fastener"),
    "Бейджик металлический с булавкой": dict(photo="badge_lanyard", name_ky="Металл бейджик (ийне менен)", name_en="Metal Badge with Pin",
        desc_ru="Металлический бейджик, крепление на булавке",
        desc_ky="Ийне менен бекитилүүчү металл бейджик",
        desc_en="Metal badge with a pin fastener"),
    "Бейджик из фанеры с булавкой": dict(photo="badge_lanyard", name_ky="Фанера бейджик (ийне менен)", name_en="Plywood Badge with Pin",
        desc_ru="Бейджик из фанеры, крепление на булавке",
        desc_ky="Ийне менен бекитилүүчү фанера бейджик",
        desc_en="Plywood badge with a pin fastener"),
    "Бейджик из фанеры на магните": dict(photo="badge_lanyard", name_ky="Фанера бейджик (магнит менен)", name_en="Plywood Badge with Magnet",
        desc_ru="Бейджик из фанеры, крепление на магните",
        desc_ky="Магнит менен бекитилүүчү фанера бейджик",
        desc_en="Plywood badge with a magnetic fastener"),
}
