# Generated by Django 6.0.1 on 2026-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0005_karaokevenue_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaokemenucategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='karaokemenuitem',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='karaokemenuitem',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='karaokeroom',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='karaokeroom',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Название кабинки (EN)'),
        ),
        migrations.AddField(
            model_name='karaokevenue',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='karaokevenue',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='karaokevenue',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Слоган (EN)'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название категории (EN)'),
        ),
    ]
