# Generated by Django 6.0.1 on 2026-01-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='branch',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_ky',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_ky',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
