# Generated by Django 6.0.1 on 2026-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_branch_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_open_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
