# Generated by Django 6.0.1 on 2026-01-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_close_time_branch_is_open_24h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='branches/covers/'),
        ),
    ]
