# Generated by Django 6.0.1 on 2026-02-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branch_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='about_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='about_ky',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='about_ru',
            field=models.TextField(blank=True, default=''),
        ),
    ]
