# Generated by Django 6.0.1 on 2026-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaurant_about_en_restaurant_about_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='map_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на карту'),
        ),
    ]
