# Generated by Django 6.0.1 on 2026-02-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch_map_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'членство', 'verbose_name_plural': 'членствы'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
    ]
