# Generated by Django 6.0.1 on 2026-03-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_rating_to_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='free_delivery_from',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = не действует', max_digits=10, verbose_name='Бесплатная доставка от (сом)'),
        ),
    ]
