# Generated by Django 6.0.1 on 2026-03-31 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_free_delivery_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Доступ к ресторану', 'verbose_name_plural': 'Доступы к ресторанам'},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'restaurant', 'branch')},
        ),
    ]
