# Generated by Django 6.0.1 on 2026-03-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_membership_unique_and_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='promo_photo',
            field=models.ImageField(blank=True, null=True, upload_to='branches/promo/', verbose_name='Фото для акции (фон карусели)'),
        ),
    ]
