# Generated by Django 6.0.1 on 2026-03-31 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_promo_photo_to_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('free_delivery', 'Бесплатная доставка'), ('percent', 'Скидка в процентах'), ('fixed', 'Скидка фиксированной суммой')], max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Для % — число (10 = 10%). Для суммы — сом (500). Для бесплатной доставки — 0.', max_digits=10, verbose_name='Размер скидки')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = без ограничений', verbose_name='Макс. использований')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Использован раз')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='core.branch')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'unique_together': {('branch', 'code')},
            },
        ),
    ]
