# Generated by Django 6.0.1 on 2026-04-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='Если заполнено — кнопка «Открыть меню» будет вести на этот адрес', verbose_name='Внешний сайт / приложение'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='Если заполнено — кнопка «Перейти к заказу» будет вести на этот сайт', verbose_name='Ссылка на сайт / приложение'),
        ),
    ]
