# Generated by Django 6.0.1 on 2026-04-05 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'Главная'), ('markets', 'Рынки'), ('shops', 'Магазины'), ('hotels', 'Отели'), ('pharmacy', 'Аптеки'), ('restaurant', 'Рестораны / меню'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Раздел')),
                ('path', models.CharField(max_length=500, verbose_name='URL')),
                ('ip_hash', models.CharField(max_length=64, verbose_name='Хэш IP')),
                ('session_key', models.CharField(blank=True, default='', max_length=64, verbose_name='Сессия')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
                'indexes': [models.Index(fields=['section', 'timestamp'], name='core_pagevi_section_b1cc75_idx')],
            },
        ),
    ]
