# Generated by Django 6.0.1 on 2026-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_branch_pay_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='section',
            field=models.CharField(choices=[('home', 'Главная'), ('markets', 'Рынки'), ('shops', 'Магазины'), ('hotels', 'Отели'), ('pharmacy', 'Аптеки'), ('legal', 'Юристы'), ('eco', 'Эко-проекты'), ('restaurant', 'Рестораны / меню'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Раздел'),
        ),
    ]
