# Generated by Django 6.0.1 on 2026-05-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_branch_lat_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='work_days',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Рабочие дни'),
        ),
    ]
