# Generated by Django 6.0.1 on 2026-07-12 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ky', models.CharField(blank=True, default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('subtitle_ru', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle_ky', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=200)),
                ('icon', models.CharField(blank=True, default='', max_length=200, verbose_name='Иконка (эмодзи или URL)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_catalog', models.BooleanField(default=True, verbose_name='Есть каталог (меню/товары)')),
                ('supports_ordering', models.BooleanField(default=True, verbose_name='Есть заказ')),
                ('supports_booking', models.BooleanField(default=False, verbose_name='Есть бронирование')),
                ('item_noun_ru', models.CharField(default='Блюда', max_length=50, verbose_name='Позиции (рус)')),
                ('item_noun_ky', models.CharField(blank=True, default='', max_length=50, verbose_name='Позиции (кыр)')),
                ('item_noun_en', models.CharField(blank=True, default='', max_length=50, verbose_name='Позиции (eng)')),
            ],
            options={
                'verbose_name': 'Категория платформы',
                'verbose_name_plural': 'Категории платформы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/covers/', verbose_name='Обложка (для списка заведений)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='place_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='core.placecategory', verbose_name='Категория платформы'),
        ),
    ]
