# Generated by Django 6.0.1 on 2026-09-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_entertainment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='section',
            field=models.CharField(choices=[('home', 'Главная'), ('markets', 'Рынки'), ('shops', 'Магазины'), ('hotels', 'Отели'), ('pharmacy', 'Аптеки'), ('legal', 'Юристы'), ('eco', 'Эко-проекты'), ('restaurant', 'Рестораны / меню'), ('barbershop', 'Барбершопы'), ('karaoke', 'Караоке'), ('simracing', 'Симрейсинг'), ('printshop', 'Полиграфия'), ('realty', 'Недвижимость'), ('agency', 'Агентства'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Раздел'),
        ),
    ]
