# Generated by Django 6.0.1 on 2026-09-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_pageview_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото')),
                ('name_ru', models.CharField(max_length=150, verbose_name='Имя (рус)')),
                ('name_ky', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя (кырг)')),
                ('name_en', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя (англ)')),
                ('role_ru', models.CharField(default='Директор и CEO', max_length=150, verbose_name='Должность (рус)')),
                ('role_ky', models.CharField(blank=True, default='', max_length=150, verbose_name='Должность (кырг)')),
                ('role_en', models.CharField(blank=True, default='', max_length=150, verbose_name='Должность (англ)')),
                ('bio_ru', models.TextField(blank=True, default='', verbose_name='О себе (рус)')),
                ('bio_ky', models.TextField(blank=True, default='', verbose_name='О себе (кырг)')),
                ('bio_en', models.TextField(blank=True, default='', verbose_name='О себе (англ)')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('whatsapp_url', models.URLField(blank=True, default='', verbose_name='WhatsApp (ссылка)')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Команда — сотрудник',
                'verbose_name_plural': 'Команда',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
