# Generated by Django 6.0.1 on 2026-04-05 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон / WhatsApp')),
                ('working_hours', models.CharField(blank=True, default='', help_text='Пример: Пн–Пт: 09:00–18:00', max_length=200, verbose_name='Часы работы')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='legal/logos/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Юр. организация',
                'verbose_name_plural': 'Юр. организации',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена (сом)')),
                ('price_note', models.CharField(blank=True, default='', help_text='Например: от, за консультацию, за час', max_length=100, verbose_name='Примечание к цене')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='legal.legalorg', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
