# Generated by Django 6.0.1 on 2026-04-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalorg',
            name='map_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на карту'),
        ),
    ]
