# Generated by Django 6.0.1 on 2026-04-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_legalorg_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalorg',
            name='tg_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID чата/группы Telegram куда слать заявки. Пример: -1001234567890', max_length=50, verbose_name='TG Chat ID'),
        ),
        migrations.AddField(
            model_name='legalorg',
            name='tg_thread_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID топика если группа с темами', null=True, verbose_name='TG Thread ID (топик)'),
        ),
    ]
