# Generated by Django 6.0.1 on 2026-04-07 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_add_tg_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legalservice',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='legal/services/', verbose_name='Фото услуги / юриста'),
        ),
        migrations.CreateModel(
            name='LegalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='legal.legalorg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к юр. организации',
                'verbose_name_plural': 'Доступы к юр. организациям',
                'unique_together': {('user', 'org')},
            },
        ),
    ]
