# Generated by Django 6.0.1 on 2026-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_legalorg_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalorg',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='legalorg',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='legalservice',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание услуги (EN)'),
        ),
        migrations.AddField(
            model_name='legalservice',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Название услуги (EN)'),
        ),
    ]
