# Generated by Django 6.0.1 on 2026-03-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacies/logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pharmacy.pharmacy')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'unique_together': {('pharmacy', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=220)),
                ('name_ky', models.CharField(blank=True, default='', max_length=220)),
                ('name_en', models.CharField(blank=True, default='', max_length=220)),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_ky', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pharmacies/drugs/photos/')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='pharmacy.pharmacy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='pharmacies/branches/covers/')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='pharmacy.pharmacy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrugInCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_links', to='pharmacy.drugcategory')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='pharmacy.drug')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'unique_together': {('category', 'drug')},
            },
        ),
        migrations.CreateModel(
            name='BranchDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_drugs', to='pharmacy.drug')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_drugs', to='pharmacy.pharmacybranch')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'unique_together': {('branch', 'drug')},
            },
        ),
    ]
