# Generated by Django 6.0.1 on 2026-04-05 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacyorder_pharmacyorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер')], default='manager', max_length=20, verbose_name='Роль')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pharmacy.pharmacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к аптеке',
                'verbose_name_plural': 'Доступы к аптекам',
                'unique_together': {('user', 'pharmacy')},
            },
        ),
    ]
