# Generated by Django 6.0.1 on 2026-05-09 16:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0012_constructor_ingredient_branch_item'),
        ('core', '0023_branch_lat_lon'),
        ('orders', '0004_add_constructor_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('gr', 'г'), ('l', 'л'), ('ml', 'мл'), ('pcs', 'шт'), ('pkg', 'уп'), ('tbsp', 'ст.л.'), ('tsp', 'ч.л.')], default='gr', max_length=10, verbose_name='Ед. изм.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('move_type', models.CharField(choices=[('purchase', 'Закупка'), ('sale', 'Продажа'), ('writeoff', 'Списание'), ('manual_add', 'Инвентаризация (+)'), ('manual_sub', 'Инвентаризация (−)'), ('return', 'Возврат')], max_length=20, verbose_name='Тип')),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за ед.')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='techcards.ingredient')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
            ],
            options={
                'verbose_name': 'Движение склада',
                'verbose_name_plural': 'Движения склада',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_qty', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8, verbose_name='Выход (кол-во порций)')),
                ('cooking_time', models.PositiveSmallIntegerField(default=0, verbose_name='Время приготовления (мин)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания/описание')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_cards', to='core.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_cards', to='catalog.item')),
            ],
            options={
                'verbose_name': 'Технологическая карта',
                'verbose_name_plural': 'Технологические карты',
                'unique_together': {('item', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='TechCardIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Брутто (кол-во)')),
                ('waste_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Отходы/потери %')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('gr', 'г'), ('l', 'л'), ('ml', 'мл'), ('pcs', 'шт'), ('pkg', 'уп'), ('tbsp', 'ст.л.'), ('tsp', 'ч.л.')], default='gr', max_length=10, verbose_name='Ед. изм.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tc_lines', to='techcards.ingredient')),
                ('semi_finished', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_semi', to='techcards.techcard')),
                ('tech_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='techcards.techcard')),
            ],
            options={
                'verbose_name': 'Ингредиент техкарты',
                'verbose_name_plural': 'Ингредиенты техкарты',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TechCardStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(verbose_name='Описание шага')),
                ('tech_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='techcards.techcard')),
            ],
            options={
                'verbose_name': 'Шаг приготовления',
                'verbose_name_plural': 'Шаги приготовления',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='TechCardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(verbose_name='Снимок карты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tech_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='techcards.techcard')),
            ],
            options={
                'verbose_name': 'Версия техкарты',
                'verbose_name_plural': 'Версии техкарты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Остаток')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Цена за ед.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_stocks', to='core.branch')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='techcards.ingredient')),
            ],
            options={
                'verbose_name': 'Остаток ингредиента',
                'verbose_name_plural': 'Остатки ингредиентов',
                'unique_together': {('branch', 'ingredient')},
            },
        ),
    ]
