# Generated by Django 6.0.1 on 2026-07-04 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='printshop/logos/', verbose_name='Логотип')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Полиграфический центр',
                'verbose_name_plural': 'Полиграфические центры',
            },
        ),
        migrations.CreateModel(
            name='PrintOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например "Материал", "Ламинация"', max_length=150, verbose_name='Название группы')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный выбор')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='Множественный выбор (чекбоксы)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа доп. параметров',
                'verbose_name_plural': 'Группы доп. параметров',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PrintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='printshop.printcenter')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PrintBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название филиала')),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='printshop/banners/', verbose_name='Баннер')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=32, verbose_name='WhatsApp (если отличается)')),
                ('taplink_url', models.URLField(blank=True, default='', verbose_name='Taplink')),
                ('map_url', models.URLField(blank=True, default='', verbose_name='Ссылка на карту (Маршрут)')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта')),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. сумма заказа')),
                ('free_delivery_from', models.DecimalField(blank=True, decimal_places=2, help_text='Пусто или 0 = бесплатная доставка не действует', max_digits=10, null=True, verbose_name='Бесплатная доставка от')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('tg_chat_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Telegram Chat ID')),
                ('tg_thread_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telegram Thread ID')),
                ('is_open_24h', models.BooleanField(default=False, verbose_name='Круглосуточно')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('work_days', models.CharField(blank=True, default='', help_text='Например 0,1,2,3,4,5,6 (0=пн ... 6=вс), пусто = все дни', max_length=20, verbose_name='Рабочие дни')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='printshop.printcenter')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ('center', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='PrintOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например "Бумага", "Да"', max_length=150, verbose_name='Значение')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доплата')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='printshop.printoptiongroup')),
            ],
            options={
                'verbose_name': 'Значение параметра',
                'verbose_name_plural': 'Значения параметра',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('in_progress', 'В работе'), ('done', 'Завершен'), ('canceled', 'Отменен')], default='new', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('online', 'Онлайн')], default='cash', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='printshop.printbranch')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PrintProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='printshop/products/', verbose_name='Главное фото')),
                ('sku', models.CharField(blank=True, default='', max_length=64, verbose_name='Артикул')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='Используется, если у товара нет вариантов', max_digits=10, verbose_name='Базовая цена')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярное')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акция')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='printshop.printcategory')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='printshop.printcenter')),
            ],
            options={
                'verbose_name': 'Товар/услуга',
                'verbose_name_plural': 'Товары/услуги',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PrintOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий к позиции')),
                ('selection_snapshot', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='printshop.printorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printshop.printproduct')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='printoptiongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='printshop.printproduct'),
        ),
        migrations.CreateModel(
            name='PrintProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='printshop/products/gallery/', verbose_name='Фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='printshop.printproduct')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товара (галерея)',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PrintProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например "S", "1×1 м", "100 шт"', max_length=100, verbose_name='Название варианта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='printshop.printproduct')),
            ],
            options={
                'verbose_name': 'Вариант (размер/тираж)',
                'verbose_name_plural': 'Варианты (размер/тираж)',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PrintPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('free_delivery', 'Бесплатная доставка'), ('percent', 'Скидка в процентах'), ('fixed', 'Скидка фиксированной суммой')], max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Для % — число (10 = 10%). Для суммы — сом. Для бесплатной доставки — 0.', max_digits=10, verbose_name='Размер скидки')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = без ограничений', verbose_name='Макс. использований')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Использован раз')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='printshop.printbranch')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'unique_together': {('branch', 'code')},
            },
        ),
        migrations.AddField(
            model_name='printorder',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='printshop.printpromocode'),
        ),
        migrations.CreateModel(
            name='PrintMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер')], default='manager', max_length=20, verbose_name='Роль')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='printshop.printcenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printshop_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к полигр. центру',
                'verbose_name_plural': 'Доступы к полигр. центрам',
                'unique_together': {('user', 'center')},
            },
        ),
    ]
