# Generated by Django 6.0.1 on 2026-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printbranch',
            name='delivery_enabled',
            field=models.BooleanField(default=True, verbose_name='Доставка включена'),
        ),
    ]
