# Generated by Django 6.0.1 on 2026-07-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0002_printbranch_delivery_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='printbranch',
            name='telegram',
            field=models.CharField(blank=True, default='', help_text='Публичный контакт для кнопки «Telegram» на витрине (не путать с Chat ID для уведомлений)', max_length=120, verbose_name='Telegram (@username или ссылка)'),
        ),
    ]
