# Generated by Django 6.0.1 on 2026-08-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_entertainment_active'),
        ('printshop', '0003_printbranch_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcenter',
            name='place_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_centers', to='core.placecategory', verbose_name='Категория платформы'),
        ),
    ]
