# Generated by Django 6.0.1 on 2026-04-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (KY)')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotels/logos/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Рейтинг')),
                ('about_ru', models.TextField(blank=True, default='', verbose_name='О нас')),
                ('external_url', models.URLField(blank=True, default='', verbose_name='Внешний сайт')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['-rating', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='HotelBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (KY)')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('map_url', models.URLField(blank=True, default='', verbose_name='Ссылка на карту')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='hotels/covers/', verbose_name='Обложка')),
                ('external_url', models.URLField(blank=True, default='', verbose_name='Внешний сайт / приложение')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Филиал отеля',
                'verbose_name_plural': 'Филиалы отелей',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=100, verbose_name='Категория')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='hotels.hotelbranch')),
            ],
            options={
                'verbose_name': 'Категория номеров',
                'verbose_name_plural': 'Категории номеров',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название номера')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('amenities_ru', models.TextField(blank=True, default='', help_text='Каждый пункт с новой строки: WiFi, Завтрак, TV ...', verbose_name='Что включено')),
                ('price_per_night', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена за ночь (сом)')),
                ('max_guests', models.PositiveSmallIntegerField(default=2, verbose_name='Макс. гостей')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='hotels/rooms/', verbose_name='Фото 1 (главное)')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='hotels/rooms/', verbose_name='Фото 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='hotels/rooms/', verbose_name='Фото 3')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotelbranch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hotels.roomcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
