# Generated by Django 6.0.1 on 2026-04-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_extra_guest',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Пример: база 2000, доплата 1000 → 1 гость=2000, 2 гостя=3000, 3 гостя=4000', max_digits=10, verbose_name='Доплата за каждого доп. гостя / ночь (сом)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Базовая цена (1 гость) / ночь (сом)'),
        ),
    ]
