# Generated by Django 6.0.1 on 2026-04-04 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_add_price_per_extra_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_type', models.CharField(choices=[('booking', 'Бронирование'), ('checkin', 'Заселение')], default='booking', max_length=10, verbose_name='Тип')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('checkin_date', models.CharField(blank=True, max_length=20, verbose_name='Дата заезда')),
                ('nights', models.PositiveSmallIntegerField(default=1, verbose_name='Ночей')),
                ('guests', models.PositiveSmallIntegerField(default=1, verbose_name='Гостей')),
                ('price_per_night', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена/ночь')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Итого')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('checkedin', 'Заселён'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.hotelbranch')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='hotels.room')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер')], default='manager', max_length=20, verbose_name='Роль')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к отелю',
                'verbose_name_plural': 'Доступы к отелям',
                'unique_together': {('user', 'hotel')},
            },
        ),
    ]
