# Generated by Django 6.0.1 on 2026-05-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_add_membership_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbranch',
            name='tg_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID группы/канала для уведомлений о бронях', max_length=64, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='hotelbranch',
            name='tg_thread_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID темы (необязательно)', null=True, verbose_name='Telegram thread ID'),
        ),
    ]
