# Generated by Django 6.0.1 on 2026-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='checkout_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='checkin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заезда'),
        ),
    ]
