# Generated by Django 6.0.1 on 2026-09-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotelbooking_checkout_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='actual_checkin_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактически заселён'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='actual_checkout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактически выселен'),
        ),
    ]
