# Generated by Django 6.0.1 on 2026-09-02 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_hotelbooking_actual_checkin_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('kind', models.CharField(choices=[('cash', 'Наличная касса'), ('bank', 'Расчётный счёт'), ('card', 'Карта'), ('other', 'Другое')], default='cash', max_length=10, verbose_name='Тип')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Начальный остаток')),
                ('is_default', models.BooleanField(default=False, help_text='Сюда зачисляется автодоход от броней', verbose_name='Касса по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_accounts', to='hotels.hotelbranch')),
            ],
            options={
                'verbose_name': 'Счёт / касса',
                'verbose_name_plural': 'Счета / кассы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Статья')),
                ('flow', models.CharField(choices=[('in', 'Доход'), ('out', 'Расход')], default='out', max_length=3, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_categories', to='hotels.hotelbranch')),
            ],
            options={
                'verbose_name': 'Статья ДДС',
                'verbose_name_plural': 'Статьи ДДС',
                'ordering': ['flow', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход'), ('transfer', 'Перевод')], max_length=10, verbose_name='Тип')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Автооперация')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='txns', to='hotels.financeaccount', verbose_name='Счёт (откуда / куда)')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_txns', to='hotels.hotelbooking', verbose_name='Бронь')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_txns', to='hotels.hotelbranch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txns', to='hotels.financecategory', verbose_name='Статья')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='txns_in', to='hotels.financeaccount', verbose_name='Счёт зачисления (для перевода)')),
            ],
            options={
                'verbose_name': 'Операция ДДС',
                'verbose_name_plural': 'Операции ДДС',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
