# Generated by Django 6.0.1 on 2026-09-02 16:01

import django.db.models.deletion
from django.db import migrations, models
from django.utils.crypto import get_random_string


def gen_codes(apps, schema_editor):
    Room = apps.get_model('hotels', 'Room')
    alphabet = "abcdefghjkmnpqrstuvwxyz23456789"
    used = set(Room.objects.exclude(public_code__isnull=True).values_list('public_code', flat=True))
    for room in Room.objects.filter(public_code__isnull=True):
        while True:
            code = get_random_string(7, alphabet)
            if code not in used:
                used.add(code)
                break
        room.public_code = code
        room.save(update_fields=['public_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_financeaccount_financecategory_financetxn'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='public_code',
            field=models.CharField(blank=True, help_text='Ссылка/QR для гостя: заказ услуг в номер, вызов сотрудника', max_length=12, null=True, unique=True, verbose_name='Код для QR'),
        ),
        migrations.RunPython(gen_codes, migrations.RunPython.noop),
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('service', 'Услуги в номер'), ('lobby', 'Вызов сотрудника')], default='service', max_length=10, verbose_name='Тип')),
                ('guest_name', models.CharField(blank=True, max_length=120, verbose_name='Имя гостя')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('done', 'Выполнена')], default='new', max_length=10, verbose_name='Статус')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_requests', to='hotels.hotelbranch')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hotels.room')),
                ('services', models.ManyToManyField(blank=True, related_name='room_requests', to='hotels.hotelservice', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Заявка из номера',
                'verbose_name_plural': 'Заявки из номеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
