# Generated by Django 6.0.1 on 2026-09-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_room_public_code_roomrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='show_in_room',
            field=models.BooleanField(default=True, help_text='Услуга доступна для заказа на странице номера по QR', verbose_name='Показывать гостям в номере (QR)'),
        ),
    ]
