# Generated by Django 6.0.1 on 2026-05-04 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=300, verbose_name='Слоган')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='barbershop/logos/', verbose_name='Логотип')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='barbershop/covers/', verbose_name='Обложка')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, default='', help_text='996700123456 — без + и пробелов', max_length=30, verbose_name='WhatsApp (с кодом страны)')),
                ('working_hours', models.CharField(blank=True, default='', max_length=200, verbose_name='Часы работы')),
                ('map_url', models.URLField(blank=True, default='', verbose_name='Ссылка на карту')),
                ('tg_chat_id', models.CharField(blank=True, default='', max_length=50, verbose_name='TG Chat ID')),
                ('tg_thread_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='TG Thread ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Барбершоп',
                'verbose_name_plural': 'Барбершопы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='barbershop/barbers/', verbose_name='Фото')),
                ('experience', models.CharField(blank=True, default='', help_text='Например: 5 лет опыта', max_length=100, verbose_name='Опыт')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='barbershop.barbershop')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена (сом)')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, verbose_name='Длительность (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barbershop.barbershop')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='barbershop.barber')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='barbershop.service')),
            ],
            options={
                'verbose_name': 'Услуга мастера',
                'verbose_name_plural': 'Услуги мастера',
                'unique_together': {('barber', 'service')},
            },
        ),
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='barbers', through='barbershop.BarberService', to='barbershop.service', verbose_name='Услуги'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Услуга (снимок)')),
                ('barber_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Мастер (снимок)')),
                ('price_snapshot', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, verbose_name='Длительность (мин)')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон')),
                ('appt_date', models.DateField(verbose_name='Дата')),
                ('appt_time', models.TimeField(verbose_name='Время')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('done', 'Выполнена'), ('cancelled', 'Отменена'), ('no_show', 'Не пришёл')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн / Касса')], default='online', max_length=10, verbose_name='Источник')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('card', 'Карта'), ('other', 'Другое')], default='', max_length=20, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий клиента')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки администратора')),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='barbershop.barber')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barbershop.barbershop')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='barbershop.service')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-appt_date', '-appt_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='barbershop.barbershop')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='barbershop.servicecategory'),
        ),
        migrations.CreateModel(
            name='BarberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Начало работы')),
                ('end_time', models.TimeField(default='20:00', verbose_name='Конец работы')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='barbershop.barber')),
            ],
            options={
                'verbose_name': 'График мастера',
                'verbose_name_plural': 'Графики мастеров',
                'ordering': ['weekday'],
                'unique_together': {('barber', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='BarbershopMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='barbershop.barbershop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к барбершопу',
                'verbose_name_plural': 'Доступы к барбершопам',
                'unique_together': {('user', 'barbershop')},
            },
        ),
    ]
