# Generated by Django 6.0.1 on 2026-08-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
        ('core', '0031_entertainment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='place_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbershops', to='core.placecategory', verbose_name='Категория платформы'),
        ),
    ]
