# Generated by Django 6.0.1 on 2026-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_barbershop_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Слоган (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Категория (EN)'),
        ),
    ]
