# Generated by Django 6.0.1 on 2026-02-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_branch_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=120, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(blank=True, default='', max_length=120, verbose_name='Название (KY)')),
                ('name_en', models.CharField(blank=True, default='', max_length=120, verbose_name='Название (EN)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.branch')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('table', 'Стол'), ('cabin', 'Кабинка')], default='table', max_length=10, verbose_name='Тип')),
                ('title', models.CharField(max_length=60, verbose_name='Название/Номер')),
                ('seats', models.PositiveIntegerField(default=4, verbose_name='Кол-во мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('x', models.PositiveIntegerField(default=0, verbose_name='X (план)')),
                ('y', models.PositiveIntegerField(default=0, verbose_name='Y (план)')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='reservations.floor')),
            ],
            options={
                'verbose_name': 'Место (стол/кабинка)',
                'verbose_name_plural': 'Места (столы/кабинки)',
                'ordering': ('type', 'title', 'id'),
                'unique_together': {('floor', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Занято (бронь)'), ('cleared', 'Снято'), ('cancelled', 'Отменено')], default='active', max_length=12, verbose_name='Статус')),
                ('customer_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Имя')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=60, verbose_name='Телефон')),
                ('guests_count', models.PositiveIntegerField(default=2, verbose_name='Гостей')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.branch')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reservations.place')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ('-created_at', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('place',), name='uniq_active_booking_per_place')],
            },
        ),
    ]
