# Generated by Django 6.0.1 on 2026-02-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branch_cover_photo'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='uniq_active_booking_per_place',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'arrived'])), fields=('place',), name='uniq_active_booking_per_place'),
        ),
    ]
