# Generated by Django 6.0.1 on 2026-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_booking_uniq_active_booking_per_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Забронировано'), ('arrived', 'Гость пришёл'), ('cleared', 'Освободили'), ('cancelled', 'Отменено')], default='active', max_length=12, verbose_name='Статус'),
        ),
    ]
