# Generated by Django 6.0.1 on 2026-02-03 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='uniq_active_booking_per_place',
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='places/photos/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('arrived', 'Гость пришёл'), ('closed', 'Закрыта'), ('canceled', 'Отменена')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='floor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name_ky',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='floor',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='seats',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('table', 'Стол'), ('cabin', 'Кабинка')], default='table', max_length=10),
        ),
        migrations.AlterField(
            model_name='place',
            name='x',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='place',
            name='y',
            field=models.IntegerField(default=40),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_at',
        ),
    ]
