# Generated by Django 6.0.1 on 2026-02-03 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaurant_about_en_restaurant_about_ky_and_more'),
        ('reservations', '0004_alter_booking_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStaffToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_tokens', to='core.branch')),
            ],
        ),
    ]
