# Generated by Django 6.0.1 on 2026-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_branchstafftoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
