# Generated by Django 6.0.1 on 2026-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_booking_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
