# Generated by Django 6.0.1 on 2026-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_place_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('token',), name='uniq_place_token'),
        ),
    ]
