# Generated by Django 6.0.1 on 2026-02-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_place_token_place_uniq_place_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-id',), 'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажы'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Место'},
        ),
    ]
