# Generated by Django 6.0.1 on 2026-08-24 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0031_entertainment_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('district', models.CharField(blank=True, default='', max_length=120, verbose_name='Район')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('area', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Площадь, м²')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Комнат')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('floors_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этажность дома')),
                ('renovation', models.CharField(choices=[('none', 'Без ремонта'), ('cosmetic', 'Косметический'), ('euro', 'Евроремонт'), ('designer', 'Дизайнерский')], default='cosmetic', max_length=20, verbose_name='Ремонт')),
                ('price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Цена продажи (сом)')),
                ('status', models.CharField(choices=[('free', 'Свободна'), ('booked', 'Забронирована'), ('sold', 'Продана'), ('removed', 'Снята с продажи')], default='free', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='realestate/apartments/', verbose_name='Фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='realestate.apartment')),
            ],
            options={
                'verbose_name': 'Фото квартиры',
                'verbose_name_plural': 'Фото квартиры',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RealtyAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название агентства')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='realestate/logos/', verbose_name='Логотип')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='realestate/covers/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('phone', models.CharField(blank=True, default='', help_text='Резервный номер для кнопки «Купить», если у квартиры не указан риэлтор', max_length=50, verbose_name='Телефон / WhatsApp агентства')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('place_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realty_agencies', to='core.placecategory', verbose_name='Категория платформы')),
            ],
            options={
                'verbose_name': 'Риэлторское агентство',
                'verbose_name_plural': 'Риэлторские агентства',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='realestate.realtyagency'),
        ),
        migrations.CreateModel(
            name='RealtyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('director', 'Директор'), ('realtor', 'Риэлтор')], default='realtor', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, default='', help_text='На этот номер ведёт кнопка «Купить» на карточках его квартир', max_length=50, verbose_name='WhatsApp риэлтора')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='realestate.realtyagency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realty_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к агентству',
                'verbose_name_plural': 'Доступы к агентству',
                'unique_together': {('user', 'agency')},
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='realestate.realtymembership', verbose_name='Ответственный риэлтор'),
        ),
    ]
