# Generated by Django 6.0.1 on 2026-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='review_url_1',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ссылка на обзор 1'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='review_url_2',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ссылка на обзор 2'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Площадь, м²'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Цена продажи (сом)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='renovation',
            field=models.CharField(blank=True, choices=[('none', 'Без ремонта'), ('cosmetic', 'Косметический'), ('euro', 'Евроремонт'), ('designer', 'Дизайнерский')], default='', max_length=20, verbose_name='Ремонт'),
        ),
    ]
