# Generated by Django 6.0.1 on 2026-08-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_apartment_review_url_1_apartment_review_url_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtyagency',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Агентство недвижимости', 'verbose_name_plural': 'Агентства недвижимости'},
        ),
        migrations.AddField(
            model_name='apartment',
            name='currency',
            field=models.CharField(choices=[('KGS', 'сом'), ('USD', '$')], default='KGS', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена продажи'),
        ),
    ]
