# Generated by Django 6.0.1 on 2026-08-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_realtyagency_options_apartment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner_phone',
            field=models.CharField(blank=True, default='', help_text='Виден только в кабинете агентства, не показывается публично', max_length=50, verbose_name='Телефон хозяина квартиры'),
        ),
    ]
