# Generated by Django 6.0.1 on 2026-08-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_apartment_owner_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtymembership',
            name='phone',
        ),
    ]
