# Generated by Django 6.0.1 on 2026-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_remove_realtymembership_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='realtyagency',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='realtyagency',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название агентства (EN)'),
        ),
    ]
