# Generated by Django 6.0.1 on 2026-02-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200)),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('about_ru', models.TextField(blank=True, default='')),
                ('about_ky', models.TextField(blank=True, default='')),
                ('about_en', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200)),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('map_url', models.URLField(blank=True, default='')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='stores/branches/')),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='shops.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200)),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shops.store')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200)),
                ('name_ky', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_ky', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stores/products/')),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('l', 'л')], default='pcs', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shops.storecategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shops.storebranch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shops.storeproduct')),
            ],
            options={
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
