# Generated by Django 6.0.1 on 2026-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_storebranch_created_at_storebranch_delivery_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranch',
            name='tg_group_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storebranch',
            name='tg_manager_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storebranch',
            name='tg_thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
