# Generated by Django 6.0.1 on 2026-02-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_storebranch_tg_group_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='mode',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('in_store', 'В магазине')], default='delivery', max_length=20),
        ),
    ]
