# Generated by Django 6.0.1 on 2026-04-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_store_youtube_url_storebranch_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Штрих-код'),
        ),
    ]
