# Generated by Django 6.0.1 on 2026-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_add_barcode_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Instagram (1)'),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_url_2',
            field=models.URLField(blank=True, default='', verbose_name='Instagram (2)'),
        ),
    ]
