# Generated by Django 6.0.1 on 2026-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_store_instagram_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranch',
            name='city',
            field=models.CharField(choices=[('bishkek', 'Бишкек'), ('osh', 'Ош'), ('other', 'Другой город')], default='bishkek', max_length=20, verbose_name='Город'),
        ),
    ]
