# Generated by Django 6.0.1 on 2026-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_storebranch_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebranch',
            name='city',
            field=models.CharField(choices=[('bishkek', 'Бишкек'), ('osh', 'Ош'), ('other', 'Другой город')], default='osh', max_length=20, verbose_name='Город'),
        ),
    ]
