# Generated by Django 6.0.1 on 2026-04-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_storebranch_city_default_osh'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranch',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='storebranch',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
