# Generated by Django 6.0.1 on 2026-05-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_storebranch_lat_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='order_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон для индивидуальных заказов'),
        ),
    ]
