# Generated by Django 6.0.1 on 2026-05-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_store_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranch',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='storebranch',
            name='is_open_24h',
            field=models.BooleanField(default=False, verbose_name='Круглосуточно'),
        ),
        migrations.AddField(
            model_name='storebranch',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время открытия'),
        ),
        migrations.AddField(
            model_name='storebranch',
            name='work_days',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Рабочие дни'),
        ),
    ]
