# Generated by Django 6.0.1 on 2026-09-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_storeproduct_cost_price_warehouse_warehousestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranch',
            name='show_stock_qty',
            field=models.BooleanField(default=True, help_text='Если выключить — в витрине и карточке товара не будет видно остаток («В наличии: N»), только факт наличия/отсутствия.', verbose_name='Показывать количество товара покупателям'),
        ),
    ]
