# Generated by Django 6.0.1 on 2026-09-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_storebranch_show_stock_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stores/constructors/', verbose_name='Фото')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, help_text='Цена без учёта выбранных ингредиентов', max_digits=10, verbose_name='Базовая цена (сом)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructors', to='shops.store')),
            ],
            options={
                'verbose_name': 'Конструктор («Собери сам»)',
                'verbose_name_plural': 'Конструкторы («Собери сам»)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreConstructorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название шага')),
                ('min_select', models.PositiveSmallIntegerField(default=1, verbose_name='Минимум выбора')),
                ('max_select', models.PositiveSmallIntegerField(default=1, help_text='0 = без лимита', verbose_name='Максимум выбора')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='shops.storeconstructor')),
            ],
            options={
                'verbose_name': 'Группа конструктора',
                'verbose_name_plural': 'Группы конструктора',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreConstructorIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена (сом), если отличается от товара')),
                ('write_off_qty', models.DecimalField(decimal_places=3, default=1, help_text='Например, 1 роза = списать 1 шт розы со склада', max_digits=10, verbose_name='Кол-во списания со склада (на 1 выбор)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shops.storeconstructorgroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shops.storeproduct', verbose_name='Товар (списывается со склада)')),
            ],
            options={
                'verbose_name': 'Ингредиент конструктора',
                'verbose_name_plural': 'Ингредиенты конструктора',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreConstructorOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constructor_name_snapshot', models.CharField(blank=True, default='', max_length=300)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingredients_snapshot', models.JSONField(blank=True, default=list)),
                ('constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.storeconstructor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_items', to='shops.storeorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
