# Generated by Django 6.0.1 on 2026-09-13 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_storeconstructor_storeconstructorgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPrintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Печать включена')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('windows_printer', models.CharField(blank=True, default='', help_text='Точное имя как в списке принтеров Windows', max_length=200, verbose_name='Имя принтера в Windows')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Последний heartbeat')),
                ('print_mode', models.CharField(choices=[('image', 'Картинка (рекомендуется)'), ('text', 'Текст (ESC/POS)')], default='image', max_length=10, verbose_name='Режим печати')),
                ('codepage', models.CharField(default='cp866', max_length=20, verbose_name='Кодовая страница')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_config', to='shops.storebranch')),
            ],
            options={
                'verbose_name': 'Настройки печати (магазин)',
                'verbose_name_plural': 'Настройки печати (магазины)',
            },
        ),
        migrations.CreateModel(
            name='ShopPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое (plain text)')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'Печатается'), ('printed', 'Напечатан'), ('error', 'Ошибка')], default='new', max_length=20)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='shops.storebranch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='shops.storeorder')),
            ],
            options={
                'verbose_name': 'Задание печати (магазин)',
                'verbose_name_plural': 'Задания печати (магазины)',
                'ordering': ['created_at'],
            },
        ),
    ]
