# Generated by Django 6.0.1 on 2026-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_shopprintconfig_shopprintjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestock',
            name='is_stopped',
            field=models.BooleanField(default=False, help_text='Временно не продаётся в этом филиале (стоп-лист) — остаток при этом не обнуляется.', verbose_name='Стоп-лист'),
        ),
    ]
