# Generated by Django 6.0.1 on 2026-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_storestock_is_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='sell_direct',
            field=models.BooleanField(default=True, help_text='Если выключено — товар не показывается в витрине и в обычной сетке кассы, но остаётся доступен как ингредиент в «Собери сам» (например лента, упаковка).', verbose_name='Продаётся отдельно'),
        ),
    ]
