# Generated by Django 6.0.1 on 2026-09-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_storeproduct_sell_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='sell_out_of_stock',
            field=models.BooleanField(default=False, help_text='Товар остаётся в наличии для покупателей, даже если остаток на складе филиала равен нулю — полезно для товаров под заказ/предзаказ. Стоп-лист по-прежнему работает и имеет приоритет.', verbose_name='Продавать без остатка (под заказ)'),
        ),
    ]
