# Generated by Django 6.0.1 on 2026-09-17 10:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0021_storeproduct_sell_out_of_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Название')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('apply_to_all', models.BooleanField(default=False, verbose_name='На все товары')),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Скидка, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='shops.storecategory', verbose_name='Категории')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='shops.store')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['weekday', '-discount_percent'],
            },
        ),
    ]
