"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ 
import os
# from sanzhi.env import env
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, True),
)

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(n20sb6gvpyx^q5#)!6b4v_mi11qkas(=j+l41nn_gzrtpx@6w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ['online-menu-sanji.com', 'www.online-menu-sanji.com', '69.10.50.176', 'sanji.kg', 'www.sanji.kg','webordo.kg', 'www.webordo.kg']


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "public_site",
    "core",
    "catalog",
    "tables",
    "orders",
    "booking",
  "integrations.apps.IntegrationsConfig",
   "reservations",
   'shops',
   "pharmacy",
   "dashboard",
   "hotels",
   "markets",
   "legal",
   "eco",
   "agency",
   "karaoke",
   "barbershop",
   "techcards.apps.TechCardsConfig",
   "printing.apps.PrintingConfig",
]
# CELERY_TASK_ALWAYS_EAGER = True
# CELERY_TASK_EAGER_PROPAGATES = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.PageViewMiddleware',
]


ROOT_URLCONF = 'config.urls'
TELEGRAM_BOT_TOKEN = env("TELEGRAM_BOT_TOKEN", default="")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        # Держим соединение живым между запросами — критично при высоком пинге до БД
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "connect_timeout": 10,
            "options": "-c statement_timeout=30000",  # 30 сек макс на запрос
        },
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Bishkek'

USE_I18N = True

USE_TZ = True

USE_L10N = True

LANGUAGES = [
    ("ru", "Русский"),
    ("ky", "Кыргызча"),
    ("en", "English"),
]
LOCALE_PATHS = [BASE_DIR / "locale"]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = "/static/"

# если у тебя есть папка /static в корне проекта
STATICFILES_DIRS = [BASE_DIR / "static"]

# куда будет собираться статика командой collectstatic (для продакшена)
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024   # 20 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB



SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

# ── Сессии и куки (Safari / iOS / Mi Browser совместимость) ──────────────────
SESSION_ENGINE        = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE    = 60 * 60 * 24 * 30   # 30 дней
SESSION_SAVE_EVERY_REQUEST = True             # сохраняем даже если ничего не менялось
SESSION_COOKIE_HTTPONLY  = True
SESSION_COOKIE_SAMESITE  = "Lax"             # работает с Safari ITP
SESSION_COOKIE_SECURE    = True              # только HTTPS (сайт работает по https)

# CSRF
CSRF_COOKIE_SAMESITE  = "Lax"
CSRF_COOKIE_SECURE    = True
CSRF_TRUSTED_ORIGINS  = ["https://webordo.kg", "https://www.webordo.kg"]




REDIS_URL = env("REDIS_URL")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "TIMEOUT": 300,
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
            "socket_connect_timeout": 5,
            "socket_timeout": 5,
        },
    }
}


CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
}

TG_BOT_TOKEN = os.getenv("TG_BOT_TOKEN", "")



CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

TELEGRAM_BOT_TOKEN = "8295438366:AAGtTtBkNYol92E10B4xxhSBEnz8HZWGykc"
TELEGRAM_ADMIN_CHAT_ID = "PASTE_CHAT_ID_HERE"  # можно группу

# ─────────────────────────────────────────────────────────────────────────────
#  JAZZMIN — красивый админ
# ─────────────────────────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    # ── Шапка / брендинг ──────────────────────────────────────────────────────
    # ── Кастомный CSS / JS ────────────────────────────────────────────────────
    "custom_css": "css/admin_custom.css",
    "custom_js":  None,
    "use_google_fonts_cdn": False,   # не грузить шрифты с Google (производительность)

    # ── Шапка / брендинг ──────────────────────────────────────────────────────
    "site_title":        "Webordo Admin",
    "site_header":       "Webordo",
    "site_brand":        "Webordo",
    "site_logo":         "mini_logo.jpg",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon":         "mini_logo.jpg",
    "welcome_sign":      "Добро пожаловать в Webordo",
    "copyright":         "Webordo © 2025",

    # ── Поиск по моделям ──────────────────────────────────────────────────────
    "search_model": ["auth.user", "core.branch", "orders.order"],

    # ── Кнопки в верхней панели ───────────────────────────────────────────────
    "topmenu_links": [
        {"name": "Главная", "url": "admin:index"},
        {"name": "Меню (сайт)", "url": "/ru/", "new_window": True},
        {"model": "auth.user"},
    ],

    # ── Иконки для приложений и моделей ──────────────────────────────────────
    "icons": {
        # apps
        "auth":         "fas fa-users-cog",
        "core":         "fas fa-store",
        "catalog":      "fas fa-utensils",
        "orders":       "fas fa-receipt",
        "tables":       "fas fa-chair",
        "integrations": "fas fa-plug",
        "booking":      "fas fa-calendar-check",
        "reservations": "fas fa-bookmark",
        "karaoke":      "fas fa-microphone",
        "hotels":       "fas fa-hotel",
        "shops":        "fas fa-shopping-bag",
        "pharmacy":     "fas fa-pills",
        "markets":      "fas fa-store-alt",
        "legal":        "fas fa-gavel",
        "eco":          "fas fa-leaf",
        "agency":       "fas fa-briefcase",
        # models
        "auth.user":                   "fas fa-user",
        "auth.group":                  "fas fa-users",
        "core.restaurant":             "fas fa-store",
        "core.branch":                 "fas fa-map-marker-alt",
        "core.membership":             "fas fa-id-badge",
        "core.promocode":              "fas fa-tag",
        "core.banner":                 "fas fa-image",
        "catalog.menuset":             "fas fa-book-open",
        "catalog.category":            "fas fa-folder",
        "catalog.item":                "fas fa-hamburger",
        "catalog.branchitem":          "fas fa-dollar-sign",
        "catalog.dishconstructor":     "fas fa-puzzle-piece",
        "catalog.constructorgroup":    "fas fa-layer-group",
        "orders.order":                "fas fa-shopping-cart",
        "orders.orderitem":            "fas fa-list",
        "tables.table":                "fas fa-chair",
        "karaoke.karaokeroom":         "fas fa-music",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # ── Цвет кнопок Save/Delete (Bootstrap 5 theme color) ────────────────────
    "related_modal_active": True,

    # ── Боковое меню — скрываем малоиспользуемые приложения ──────────────────
    "hide_apps":   [],
    "hide_models": [],
    "order_with_respect_to": [
        "core", "catalog", "orders", "tables",
        "integrations", "karaoke", "hotels", "booking",
        "reservations", "shops", "pharmacy", "markets",
        "auth", "legal", "eco", "agency",
    ],

    # ── Кастомные ссылки в сайдбаре (вверху каждого приложения) ──────────────
    "custom_links": {
        "orders": [{
            "name":        "Новые заказы",
            "url":         "admin:orders_order_changelist",
            "icon":        "fas fa-fire",
            "permissions": ["orders.view_order"],
        }],
    },

    # ── Виджеты на главной странице ──────────────────────────────────────────
    "show_ui_builder":   False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user":  "collapsible",
        "auth.group": "vertical_tabs",
    },

    # ── Прочее ───────────────────────────────────────────────────────────────
    "show_sidebar":          True,
    "navigation_expanded":   True,
    "hide_admin_in_sidebar": False,
    "language_chooser":      False,
}

JAZZMIN_UI_TWEAKS = {
    # тема цветовой палитры Bootstrap 5
    "navbar_small_text":      False,
    "footer_small_text":      False,
    "body_small_text":        False,
    "brand_small_text":       False,
    "brand_colour":           "navbar-dark",
    "accent":                 "accent-primary",
    "navbar":                 "navbar-dark",
    "no_navbar_border":       True,
    "navbar_fixed":           True,    # липкий топбар на мобилке
    "layout_boxed":           False,
    "footer_fixed":           False,
    "sidebar_fixed":          True,
    "sidebar":                "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent":      True,
    "sidebar_nav_compact_style":     True,   # компактный список на мобилке
    "sidebar_nav_legacy_style":      False,
    "sidebar_nav_flat_style":        False,
    "theme":                  "flatly",      # чистая светлая тема (flatly/lumen/cosmo)
    "dark_mode_theme":        "darkly",      # при нажатии 🌙 переключается
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
    "actions_sticky_top": True,   # фиксируем Actions bar при прокрутке
}
