# Generated by Django 6.0.1 on 2026-04-05 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон / WhatsApp')),
                ('working_hours', models.CharField(blank=True, default='', help_text='Пример: Пн–Вс: 08:00–20:00', max_length=200, verbose_name='Часы работы')),
                ('map_url', models.URLField(blank=True, default='', verbose_name='Ссылка на карту')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='eco/logos/', verbose_name='Логотип / фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Эко-проект',
                'verbose_name_plural': 'Эко-проекты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EcoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена (сом)')),
                ('price_note', models.CharField(blank=True, default='', help_text='Например: за вывоз, за кг, бесплатно', max_length=100, verbose_name='Примечание к цене')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='eco.ecoproject', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
