# Generated by Django 6.0.1 on 2026-06-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_add_membership_and_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoapplication',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата создания'),
        ),
    ]
