# Generated by Django 6.0.1 on 2026-06-24 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0003_override_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoapplication',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
