# Generated by Django 6.0.1 on 2026-09-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0005_ecoproject_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoproject',
            name='tg_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID группы/канала Telegram, куда падают новые заявки. Пример: -1001234567890', max_length=50, verbose_name='TG Chat ID'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='tg_thread_id',
            field=models.PositiveIntegerField(blank=True, help_text='Необязательно. ID темы в супергруппе с топиками.', null=True, verbose_name='TG Thread ID (топик)'),
        ),
    ]
