# Generated by Django 6.0.1 on 2026-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0006_ecoproject_tg_chat_id_ecoproject_tg_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoproject',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='ecoservice',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание услуги (EN)'),
        ),
        migrations.AddField(
            model_name='ecoservice',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Название услуги (EN)'),
        ),
    ]
