# Generated by Django 6.0.1 on 2026-01-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_branch_close_time_branch_is_open_24h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('user', 'Личка'), ('group', 'Группа'), ('channel', 'Канал')], default='user', max_length=10)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('chat_id', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('message_thread_id', models.PositiveIntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_recipients', to='core.branch')),
            ],
            options={
                'ordering': ('-is_active', 'kind', 'id'),
                'unique_together': {('branch', 'chat_id')},
            },
        ),
    ]
