# Generated by Django 6.0.1 on 2026-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramrecipient',
            name='notify_new_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramrecipient',
            name='notify_status_changes',
            field=models.BooleanField(default=True),
        ),
    ]
