# Generated by Django 6.0.1 on 2026-02-01 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branch_cover_photo'),
        ('integrations', '0002_telegramrecipient_notify_new_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_orders', models.BooleanField(default=True)),
                ('notify_bookings', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_links', to='core.branch')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='integrations.telegramrecipient')),
            ],
            options={
                'unique_together': {('branch', 'recipient')},
            },
        ),
    ]
