# Generated by Django 6.0.1 on 2026-09-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_branchtelegramlink'),
        ('shops', '0018_shopprintconfig_shopprintjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('user', 'Личка'), ('group', 'Группа'), ('channel', 'Канал')], default='group', max_length=10, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Название')),
                ('chat_id', models.CharField(max_length=64, verbose_name='Chat ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('message_thread_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Topic ID (для супергрупп)')),
                ('notify_new_orders', models.BooleanField(default=True, verbose_name='Уведомлять о новых заказах')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_recipients', to='shops.storebranch', verbose_name='Филиал магазина')),
            ],
            options={
                'verbose_name': 'Telegram-получатель (магазин)',
                'verbose_name_plural': 'Telegram-получатели (магазины)',
                'ordering': ('-is_active', 'kind', 'id'),
                'unique_together': {('branch', 'chat_id')},
            },
        ),
    ]
