# Generated by Django 6.0.1 on 2026-09-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosalon', '0002_car_sold_at'),
        ('integrations', '0004_shoptelegramrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutosalonTelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('user', 'Личка'), ('group', 'Группа'), ('channel', 'Канал')], default='group', max_length=10, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Название')),
                ('chat_id', models.CharField(max_length=64, verbose_name='Chat ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('message_thread_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Topic ID (для супергрупп)')),
                ('notify_new_leads', models.BooleanField(default=True, verbose_name='Уведомлять о новых заявках')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_recipients', to='autosalon.autodealership', verbose_name='Автосалон')),
            ],
            options={
                'verbose_name': 'Telegram-получатель (автосалон)',
                'verbose_name_plural': 'Telegram-получатели (автосалоны)',
                'ordering': ('-is_active', 'kind', 'id'),
                'unique_together': {('dealership', 'chat_id')},
            },
        ),
    ]
