# Generated by Django 6.0.1 on 2026-02-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_name_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchcategory',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Категория филилла', 'verbose_name_plural': 'Категория филила'},
        ),
        migrations.AlterModelOptions(
            name='branchcategoryitem',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Порядок блюд внутри конкретной категории филиала.', 'verbose_name_plural': 'Порядок блюд внутри конкретной категории филиала.'},
        ),
        migrations.AlterModelOptions(
            name='branchitem',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиал'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'категория блюд в сете', 'verbose_name_plural': 'категория блюд в сете'},
        ),
        migrations.AlterModelOptions(
            name='menuset',
            options={'verbose_name': 'Меню сет', 'verbose_name_plural': 'Меню сеты'},
        ),
    ]
