# Generated by Django 6.0.1 on 2026-02-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_branchcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchitem',
            name='delivery_available',
            field=models.BooleanField(default=True),
        ),
    ]
