# Generated by Django 6.0.1 on 2026-02-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_branchitem_delivery_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchitem',
            options={'verbose_name': 'Блюдо Филиал', 'verbose_name_plural': 'Блюды Филиал'},
        ),
        migrations.AlterUniqueTogether(
            name='branchitem',
            unique_together=set(),
        ),
    ]
