# Generated by Django 6.0.1 on 2026-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_branchitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Кол-во заказов'),
        ),
    ]
