# Generated by Django 6.0.1 on 2026-04-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_item_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Рейтинг'),
        ),
    ]
