# Generated by Django 6.0.1 on 2026-04-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_item_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchitem',
            name='stock',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
