# Generated by Django 6.0.1 on 2026-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_constructor_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructoringredient',
            name='extra_price',
        ),
        migrations.AddField(
            model_name='constructoringredient',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='constructoringredient',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена (сом)'),
        ),
    ]
