# Generated by Django 6.0.1 on 2026-04-21 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_constructor_ingredient_price_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructoringredient',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Позиция конструктора', 'verbose_name_plural': 'Позиции конструктора'},
        ),
        migrations.AddField(
            model_name='constructoringredient',
            name='branch_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.branchitem', verbose_name='Блюдо из меню'),
        ),
        migrations.AlterField(
            model_name='constructoringredient',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название'),
        ),
    ]
