# Generated by Django 6.0.1 on 2026-05-17 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_constructor_ingredient_branch_item'),
        ('printing', '0001_cloud_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchcategory',
            name='printer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_categories', to='printing.printergroup', verbose_name='Принтер (группа)'),
        ),
    ]
