# Generated by Django 6.0.1 on 2026-07-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_item_printer_group'),
        ('techcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructoringredient',
            name='warehouse_ingredient',
            field=models.ForeignKey(blank=True, help_text='Какой ингредиент списывать при закрытии заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_lines', to='techcards.ingredient', verbose_name='Ингредиент склада'),
        ),
        migrations.AddField(
            model_name='constructoringredient',
            name='write_off_qty',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Сколько единиц ингредиента списывать за каждую единицу этой позиции', max_digits=10, verbose_name='Кол-во списания (на 1 шт)'),
        ),
    ]
