# Generated by Django 6.0.1 on 2026-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_constructor_ingredient_warehouse_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Калории, ккал'),
        ),
        migrations.AddField(
            model_name='item',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Углеводы, г'),
        ),
        migrations.AddField(
            model_name='item',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Жиры, г'),
        ),
        migrations.AddField(
            model_name='item',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Белки, г'),
        ),
    ]
