# Generated by Django 6.0.1 on 2026-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_item_calories_item_carbs_item_fat_item_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Заполните, чтобы запустить акцию: укажите прежнюю цену, а в поле «Цена» — новую. На сайте старая цена покажется зачёркнутой, новая — выделенной, на карточке появится бейдж.', max_digits=10, null=True, verbose_name='Старая цена (до акции)'),
        ),
        migrations.AddField(
            model_name='branchitem',
            name='promo_label',
            field=models.CharField(blank=True, default='', help_text='Например «Акция» или «Скидка». Если оставить пустым — «Акция».', max_length=20, verbose_name='Текст бейджа'),
        ),
    ]
