# Generated by Django 6.0.1 on 2026-09-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_branchitem_old_price_branchitem_promo_label'),
        ('core', '0033_teammember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchitem',
            unique_together={('branch', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('restaurant', 'name_ru')},
        ),
    ]
