# Generated by Django 6.0.1 on 2026-07-14 04:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('type', models.CharField(choices=[('kart_standard', 'Стандартный картинг'), ('kart_euro', 'Евроспор картинг'), ('simulator', 'Автосимулятор')], default='kart_standard', max_length=20, verbose_name='Тип')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='simracing/machines/', verbose_name='Фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='В работе')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SimRacingVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=300, verbose_name='Слоган')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='simracing/logos/', verbose_name='Логотип')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='simracing/covers/', verbose_name='Обложка')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, default='', help_text='996700123456 — без + и пробелов', max_length=30, verbose_name='WhatsApp')),
                ('working_hours', models.CharField(blank=True, default='', max_length=200, verbose_name='Часы работы')),
                ('map_url', models.URLField(blank=True, default='', verbose_name='Ссылка на карту')),
                ('tg_chat_id', models.CharField(blank=True, default='', max_length=50, verbose_name='TG Chat ID')),
                ('tg_thread_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='TG Thread ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Симрейсинг-площадка',
                'verbose_name_plural': 'Симрейсинг-площадки',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('kart_standard', 'Стандартный картинг'), ('kart_euro', 'Евроспор картинг'), ('simulator', 'Автосимулятор')], max_length=20, verbose_name='Тип машины')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена (сом)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_types', to='simracing.simracingvenue')),
            ],
            options={
                'verbose_name': 'Тип сессии (прайс)',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ['machine_type', 'sort_order', 'duration_minutes'],
                'unique_together': {('venue', 'machine_type', 'duration_minutes')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=80, verbose_name='Телефон')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена (сом)')),
                ('machine_type_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Касса')], default='online', max_length=10, verbose_name='Источник')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='active', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец (фактический)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='simracing.machine')),
                ('session_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simracing.sessiontype', verbose_name='Тип сессии')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='simracing.simracingvenue')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='simracing.simracingvenue'),
        ),
        migrations.CreateModel(
            name='SimRacingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simracing_memberships', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='simracing.simracingvenue')),
            ],
            options={
                'verbose_name': 'Доступ к симрейсингу',
                'verbose_name_plural': 'Доступы к симрейсингу',
                'unique_together': {('user', 'venue')},
            },
        ),
    ]
