# Generated by Django 6.0.1 on 2026-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simracing', '0007_racing_view_pct_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='simracingvenue',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='simracingvenue',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='simracingvenue',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Слоган (EN)'),
        ),
        migrations.AlterField(
            model_name='simracingprintconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simracingprintconfig',
            name='windows_printer',
            field=models.CharField(blank=True, default='', help_text='Точное имя как в списке принтеров Windows', max_length=200, verbose_name='Имя принтера в Windows'),
        ),
        migrations.AlterField(
            model_name='simracingprintjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
