# Generated by Django 6.0.1 on 2026-05-17 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Код группы')),
                ('display_name', models.CharField(max_length=100, verbose_name='Название')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_groups', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Группа принтеров',
                'verbose_name_plural': 'Группы принтеров',
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_name', models.CharField(help_text='Точное имя как в списке принтеров Windows', max_length=200, verbose_name='Имя принтера в Windows')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='core.restaurant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='printing.printergroup')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='ID заказа')),
                ('content', models.TextField(verbose_name='Содержимое (plain text)')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'Печатается'), ('printed', 'Напечатан'), ('error', 'Ошибка')], default='new', max_length=20)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='printing.printergroup')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Задание печати',
                'verbose_name_plural': 'Задания печати',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantPrintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Печать включена')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Последний heartbeat')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_config', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Настройки печати',
                'verbose_name_plural': 'Настройки печати',
            },
        ),
    ]
