# Generated by Django 6.0.1 on 2026-05-18 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_cloud_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprintconfig',
            name='receipt_printer_group',
            field=models.ForeignKey(blank=True, help_text='Этот принтер будет получать чеки при закрытии стола/заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='printing.printergroup', verbose_name='Принтер для итоговых чеков'),
        ),
    ]
