# Generated by Django 6.0.1 on 2026-02-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_order_payment_status'),
        ('reservations', '0007_place_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='reservations.place'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('dine_in', 'В заведении'), ('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='pickup', max_length=20),
        ),
    ]
