# Generated by Django 6.0.1 on 2026-04-21 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_constructor_order_item'),
        ('orders', '0003_order_table_place_alter_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constructor_name_snapshot', models.CharField(max_length=200)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingredients_snapshot', models.JSONField(default=list)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.dishconstructor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Позиция заказа (конструктор)',
                'verbose_name_plural': 'Позиции заказа (конструктор)',
            },
        ),
    ]
