# Generated by Django 6.0.1 on 2026-09-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='old_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Заполняется, если блюдо было по акции в момент заказа', max_digits=10, null=True, verbose_name='Старая цена на момент заказа'),
        ),
    ]
