# Generated by Django 6.0.1 on 2026-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_old_price_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка по промокоду (сом)'),
        ),
    ]
