# Generated by Django 6.0.1 on 2026-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_agency_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название агентства (EN)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Слоган (EN)'),
        ),
        migrations.AddField(
            model_name='agencyservice',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='agencyservice',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Название услуги (EN)'),
        ),
    ]
